### PR TITLE
Enh/noid/improve videos bottom bar

### PR DESCRIPTION
**Pull request by marcoambrosini**
https://user-images.githubusercontent.com/26852655/144424220-b84997e8-c71d-40fe-b178-80f574323a27.mov

### CODE REVIEW

**Comment by nickvergessen** [comment]
Names are still jumping:

* Be muted with video off: others see your name in the ⬅️ 
* Raise hand: others see your name in the ↔️ 
* As another person don't move your mouse so icons fade: name of user 1 jumps to the ➡️

**Comment by marcoambrosini** [comment]
should be fixed now

https://user-images.githubusercontent.com/26852655/148946250-80bbb57d-6102-4aee-87c8-e5823679707c.mov

**Comment by marcoambrosini** [comment]
Modified so that the raised hand is always on the left 

Screenshot 2022-01-12 at 13 20 05

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
