### PR TITLE
Public page improvements

### LINKED ISSUE #159: Allow guests to put in custom name
Currently we have the placeholder »Guest« for guests in rooms which were shared by link. To better identify people, we should offer the ability for guests to change this label to their actual name. Similar to how https://talky.io or Etherpad do it.

Only question is the placement, because the video controls are already in the nameIndicator element and work well there. We could put it in the top part of the own video.

The interaction should then be that clicking the name will allow you to change it. We can easily achieve it when the name display is basically an input field styled to look like text only, and it gets an input-like border around it on hover/focus.

### PR DESCRIPTION
**Pull request by Ivansss**
- [x] "Change guest's display name" feature -> Fix #159 
untitled

### CODE REVIEW

**Comment by Ivansss** [comment]
@jancborchardt could you please take a look? it is ready for review :)

**Comment by jancborchardt** [comment]
@Ivansss looks good! Only 2 improvements:
- [ ] can you make it so the name is also saved when clicking outside of the field?
- [ ] and we need a button with an .icon-confirm arrow icon for mouse users there. Just confirming by enter is not discoverable enough. You can check on the public share page in the »Add to your Nextcloud« field how it’s done :) I can help with positioning

**Comment by Ivansss** [comment]
Sounds good! I will change it.
Also @schiessle propose me to add the 'edit' icon next to the name, so users will notice that they can change the name.

**Comment by Ivansss** [comment]
After implementing the confirm button, I think it is good enough to send the new guest name only when pressing enter or clicking on the confirm button. 
If we also send the new guest name when clicking outside of the field, confirm button looks kind of useless.
Let me know what you think @jancborchardt 😉

**Comment by nickvergessen** [comment]
Seems to work 👍

**Comment by nickvergessen** [comment]
But you need to rebase:
> Conflicting files
js/app.js

**Comment by jancborchardt** [comment]
:+1: yeah, confirm button is enough :) Good stuff @Ivansss! :)

**Pull request merged**
