### PR TITLE
Cancel getparticipants requests once changing conversation

### PR DESCRIPTION
**Pull request by ma12-co**
Avoid duplicating getparticipants requests when quickly switching between conversations.

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Maybe when it's not the first visit in the conversation we could even delay this request a bit? It's okay to see an outdated but mostlikely unchanged page for some seconds, if everything is a lot quicker in response

**Comment by ma12-co** [comment]
mmm not sure, you could have visited it already in the same tab but some time ago?

**Comment by nickvergessen** [comment]
Yeah, but the next refresh (currently happening every 30s) will fix it, sounds good enough?
Or we use a timeout and refresh it manually once after ~5s, but not before the chat is loaded. that seems more important?

**Comment by ma12-co** [comment]
> sounds good enough

it doesn't to me.. It can be misleading. Imagine you expect someone to be there and you don't see it when going back to the conv. Then you try to add him and you get some kind of error (the participant is already in the conversation??) :P

> Or we use a timeout and refresh it manually once after ~5s, but not before the chat is loaded. that seems more important?

If we do this I think we should keep the list in a loading state until refreshed, for the same reason described above

**Comment by ma12-co** [comment]
So what do we do here @nickvergessen??

**Pull request merged**
