### PR TITLE
Fix sidebar's title alignment

### LINKED ISSUE #2565: Title in sidebar is not properly aligned
## Steps to reproduce
1. Install Spreed master
2. Click on "Talk updates room"
3. Notice that the title is not properly aligned in the sidebar

### Expected behaviour
It should be properly aligned.

Screenshot 2019-12-14 at 09 54 42

### PR DESCRIPTION
**Pull request by ma12-co**
Fix #2565

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Also conflict and there should not be package-lock.json changes in here

**Comment by ma12-co** [comment]
>Also, only the favorite should be aligned: nextcloud/nextcloud-vue#340 (comment)
Right actions/close are expected to be top right

I don't understand this part Barth

**Comment by skjnldsv** [comment]
> > Also, only the favorite should be aligned: [nextcloud/nextcloud-vue#340](https://github.com/nextcloud/nextcloud-vue/pull/340) (comment)
> > Right actions/close are expected to be top right

on the screenshot, the only issue is the favorite icon alignment with the title. 
To be fair, it looks weird, why is it bold? We never use bold in nextcloud it should be like the screenshots on https://github.com/nextcloud/nextcloud-vue/pull/340#issuecomment-482131260
Or like the current files sidebar.

I just tried it again on server (files, so 0.12.7), and it's all fine
Capture d’écran_2019-12-20_11-33-31

**Comment by nickvergessen** [comment]
Well we modified the heading to h2 in https://github.com/nextcloud/nextcloud-vue/pull/710 as per Jan's request. And it seems since then the padding is off

I guess https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppSidebar/AppSidebar.vue#L550 need adjusting to substract only like 8 or 9

**Comment by ma12-co** [comment]
>on the screenshot, the only issue is the favorite icon alignment with the title.

The issue is the text sliding down outside its container and being cut!

**Comment by nickvergessen** [comment]
> Conflicting files
src/components/RightSidebar/RightSidebar.vue


Please rebase on latest master

**Comment by skjnldsv** [comment]
> Nope, fix in globally in the vue components if it's needed please

Please forward this fix to the vue components.

**Comment by ma12-co** [comment]
But isn't this bold title version a talk only feature? Without changing that there's no need for this fix as you pointed out :)

**Comment by ma12-co** [comment]
But in general yes, there are a bunch of `v-deep` around and after 18 I'm going to forward the changes to the vue library

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/pull/2589#issuecomment-567925147

**Comment by skjnldsv** [comment]
> But isn't this bold title version a talk only feature?

Has this been validated by Jan? Why do we have bold title here?

**Comment by nickvergessen** [comment]
Its h2, its always bold

**Comment by skjnldsv** [comment]
Then it's an issue I think
cc @jancborchardt  :)

**Comment by nickvergessen** [comment]
Well its the headline of the sidebar, exactly what it should be?

**Comment by jancborchardt** [comment]
We did talk about making it bold as it helps people see what’s the focus here. It’s intended to be bold. :)

**Comment by skjnldsv** [comment]
Thanks a lot :)

**Pull request merged**
