### PR TITLE
Replace triangle sidebar trigger with dedicated icon, add icons to sidebar tabs and fix padding

### PR DESCRIPTION
**Pull request by jancborchardt**
Sidebar trigger icon:
screenshot from 2018-01-09 17-20-11

And in the sidebar:
screenshot from 2018-01-09 17-20-27

Please review @danxuliu @nickvergessen @Ivansss

### CODE REVIEW

**Comment by jancborchardt** [comment]
@danxuliu Yeah, when we are still not in the call / on white background we could even just remove the `icon-white icon-shadow` classes from the icons. :)

Let’s do that in a separate pull request though. Is there a class which lets us know if we are in a call or not?

**Comment by danxuliu** [comment]
>  Is there a class which lets us know if we are in a call or not?

The `incall` class is added to the `#app-content` element... in theory. I have just seen that it sometimes it is not added. Great... :-P

**Comment by nickvergessen** [comment]
Hmm not sure I like all these white icons on the white background (shadowed or not), I find them hard to see. Especially when the redshift kicks in. I'd say: either use grey/black like with all other icons, or stay with the triangle. (And yes, we can change the icon to white when you are switching into a call, so it's still visible on the black screen).

But 👍  for the icons on the tab headers.

**Comment by jancborchardt** [comment]
@nickvergessen yep, that's why I mentioned that we can simply show them as grey icons when on white background. :) Will do that, but in a separate PR.

**Comment by jancborchardt** [comment]
(Cause it's the same for the mute and video icons.)

**Comment by jancborchardt** [comment]
The dark icons are in https://github.com/nextcloud/spreed/pull/553 :)

**Pull request merged**
