### PR TITLE
Add guests app in CI runs that need it

### PR DESCRIPTION
**Pull request by PVince81**
The guests app checkout was missing in some of the integration-conversation runs.

Signed-off-by: Vincent Petry <vincent@nextcloud.com>

### CODE REVIEW

**Comment by PVince81** [comment]
ref to the failures that started popping up on master: https://drone.nextcloud.com/nextcloud/spreed/1247/10/4

no idea why they didn't pop up before... maybe just some luck/unluck

**Comment by PVince81** [comment]
wait, the build is not triggered because we didn't change any files...

**Comment by PVince81** [comment]
something fishy... `tests/drone-run-integration-tests.sh: line 11: [[: .drone.yml: syntax error: operand expected (error token is ".drone.yml")`

**Comment by PVince81** [comment]
seems we had a similar issue before: `tests/drone-run-integration-tests.sh: line 11: [[: appinfo/info.xml: syntax error: invalid arithmetic operator (error token is ".xml")`, seen in a test run from another PR: https://drone.nextcloud.com/nextcloud/spreed/1248/5/3

ok, so now to find out the correct syntax...

**Comment by PVince81** [comment]
ah! we were missing the `-c` to count the lines

**Review by nickvergessen — APPROVED** [review]
🙈

**Comment by PVince81** [comment]
further backports of only the file changes detection here: https://github.com/nextcloud/spreed/pull/5171

**Pull request merged**
