### PR TITLE
Add resource links

### LINKED ISSUE #226: Link Resources in NC-Appstore to github
In the nc-Appstore https://apps.nextcloud.com/apps/spreed
under **Resources** there should be at least a link to github
https://github.com/nextcloud/spreed

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #226

### CODE REVIEW

**Comment by jancborchardt** [comment]
@JSoko feel free to review as this fixes the issue you reported. :)

**Comment by JSoko** [comment]
Yes, it's fixed :-) Thank You
videocalls

**Comment by jancborchardt** [comment]
Thanks a lot for your help @JSoko! :) Reviewing pull requests is always very appreciated and helps a lot!

**Comment by jancborchardt** [comment]
@JSoko I also invited you to the Nextcloud organization here. And saw you are based in Frankfurt → you are very welcome at our monthly meetups https://www.meetup.com/nextcloud-rhein-main :)

**Comment by JSoko** [comment]
@jancborchardt thanks, we will see us at March, 15th... :-)

**Pull request merged**
