### PR TITLE
Move admin settings to src/ folder

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by nickvergessen** [comment]
the make clean I fixed. For the other thing... no idea what this is.

**Comment by nickvergessen** [comment]
```
Error resolving webpackConfig { Error: Cannot find module '/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/nextcloud-vue-collections/webpack.common.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.exports.resolve (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-import-resolver-webpack/index.js:66:27)
    at v2 (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-module-utils/resolve.js:94:23)
    at withResolver (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-module-utils/resolve.js:99:16)
    at fullResolve (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-module-utils/resolve.js:116:22)
    at Function.relative (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-module-utils/resolve.js:61:10)
    at remotePath (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/ExportMap.js:401:30)
    at captureDependency (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/ExportMap.js:442:15)
    at /home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/ExportMap.js:480:7
    at Array.forEach (<anonymous>)
    at Function.ExportMap.parse (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/ExportMap.js:461:12)
    at Function.ExportMap.for (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/ExportMap.js:353:25)
    at Function.ExportMap.get (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/ExportMap.js:315:23)
    at processBodyStatement (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/rules/namespace.js:67:47)
    at Array.forEach (<anonymous>)
    at Program (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint-plugin-import/lib/rules/namespace.js:96:14)
    at listeners.(anonymous function).forEach.listener (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/linter.js:747:15)
    at Linter._verifyWithoutProcessors (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/linter.js:899:31)
    at preprocess.map.textBlock (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/linter.js:955:35)
    at Array.map (<anonymous>)
    at Linter.verify (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/linter.js:954:42)
    at Linter.verifyAndFix (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/linter.js:1047:29)
    at processText (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/cli-engine.js:197:32)
    at CLIEngine.executeOnText (/home/nickv/Nextcloud/18/server/appsbabies/spreed/node_modules/eslint/lib/cli-engine.js:690:40) code: 'MODULE_NOT_FOUND' }
```

**Comment by juliushaertl** [comment]
@nickvergessen Looks like this is an issue of the eslint-plugin-import-webpack package that is for some reason trying to resolve a webpack file in the nextcloud-vue-collections package. Looks related to https://github.com/benmosher/eslint-plugin-import/issues/666

I would suggest to just use the nextcloud eslint config (which actually was there already for the vue/ folder https://github.com/nextcloud/spreed/pull/2331/files#diff-cecd8ef8b42693e7881b49f1e1525efe)

Otherwise you could enforce the webpack resolver to just take your apps config into account:

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index 02f83b17..833c00ed 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -1,3 +1,5 @@
+const path = require('path')
+
 module.exports = {
        root: true,
        env: {
@@ -31,7 +33,7 @@ module.exports = {
        settings: {
                'import/resolver': {
                        webpack: {
-                               config: 'webpack.common.js'
+                               config: path.resolve('webpack.common.js')
                        },
                        node: {
                                paths: ['src'],
```

**Comment by nickvergessen** [comment]
Oh right, I just forgot to adjust the eslintrc file after installing the package. That also solves the issue.

**Pull request merged**
