### PR TITLE
New button to disable lobby in sidebar

### PR DESCRIPTION
**Pull request by PVince81**
image

Fixes https://github.com/nextcloud/spreed/issues/4981
Fixes https://github.com/nextcloud/spreed/issues/4982

Note: I tried adding more information like the remaining time until meeting start, but it would take too much space and make the sidebar look too crowded. Also the moment library doesn't generate nice compact human readable texts for remaining durations. So if we do want this: needs further research.

### CODE REVIEW

**Comment by ma12-co** [comment]
I don't think this button should be there. We could create a new action button in the moderation menu when the lobby is activated. That would make it for a 2 click operation, wouldn't it be enough? If not I would say we add a circular unlabeled button beside the moderation menu (only when the lobby is enabled)

**Review by ma12-co — CHANGES_REQUESTED** [review]
I don't think this button should be there. We could create a new action button in the moderation menu when the lobby is activated. That would make it for a 2 click operation, wouldn't it be enough? If not I would say we add a circular unlabeled button beside the moderation menu (only when the lobby is enabled)

**Comment by PVince81** [comment]
@ma12-co we should also fulfil https://github.com/nextcloud/spreed/issues/4982 which requires a way to find out whether the lobby is enabled without extra clicks. The button being present would already be a sign.

**Comment by nickvergessen** [comment]
> I don't think this button should be there.

Only the disable is there and that must be. It must be really prominent and is mostly the next thing to be done in meetings.

**Comment by ma12-co** [comment]
What about 
> circular unlabeled button beside the moderation menu (only when the lobby is enabled)

**Comment by PVince81** [comment]
> What about
> 
> > circular unlabeled button beside the moderation menu (only when the lobby is enabled)

unlabeled with what icon ?

**Review by nickvergessen — APPROVED** [review]
Works and good enough for now

**Comment by ma12-co** [comment]
> unlabeled with what icon ?

Maybe message lock?

**Comment by nickvergessen** [comment]
It needs to be super obvious. So if it's only an icon, it needs to be primary to make sure it's right into the eye.
But I think a labeled button is much better and more obvious.

**Comment by ma12-co** [comment]
> it needs to be primary

I'd have suggested yellow (warning).

**Comment by nickvergessen** [comment]
> > unlabeled with what icon ?
> 
> Maybe message lock?

Or the lobby button, so it's obvious that it's the lobby...
https://github.com/nextcloud/spreed/blob/master/img/lobby.svg

**Comment by PVince81** [comment]
but clicking a button that looks like a bell doesn't tell me what the button does intuitively, so would need a tooltip to make it clear it's about disabling it, not enabling

**Comment by nickvergessen** [comment]
Well so as you can see in the ticket people have the sidebar open and check the participant list in such cases. So it's not arbitrary really.

**Comment by ma12-co** [comment]
> but clicking a button that looks like a bell doesn't tell me what the button does intuitively, so would need a tooltip to make it clear it's about disabling it, not enabling

Agree on that a bell doesn't work

**Review by wiswedel — APPROVED** [review]
Great implementation. Does exactly what it promises (and the wording refers 1:1 to the "enable" mechanism 👍).

**Comment by PVince81** [comment]
Let's move forward for now. We can iterate on the design later on when having another look bird's eye vue at the lobby feature.

**Comment by nickvergessen** [comment]
Icon in question is `RoomService` https://material.io/resources/icons/?search=service&icon=room_service&style=baseline

**Pull request merged**
