### PR TITLE
Also return the conversation data when the room exists already

### LINKED ISSUE #4186: Avatar -> call does not work
## Steps to reproduce
1. open up a conversation
2. click on another avatar in chat list -> "talk to mrs. y"
3. it opens https://cloudserver.com/apps/spreed/?callUser=mrsY
4. error 500

### Expected behaviour
redirect to conversation with that user

### Actual behaviour
error 500

## Talk app

**Talk app version:** our internal cloud

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #4186 

### Steps
1. Create one to one conversation with a user
2. Open the avatar menu of that user any where
3. Click on "Talk with X"
4. Be greeten by 500

### CODE REVIEW

**Comment by nickvergessen** [comment]
Regression from 31c20949b4132e0024446a30f0f3a423bf145906 and the follow-up fix in 4655784a713bbd2eb3eb910a35e03af636a5f999

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Pull request merged**
