### PR TITLE
Move room moderation actions to a menu

### PR DESCRIPTION
**Pull request by danxuliu**
Draft until #2122 is merged (first commit of this pull request is _Move checkbox to change between public and group room to a menu_)

This pull request provides [the groundwork needed to set the lobby state in the UI using a menu](https://github.com/nextcloud/spreed/pull/1926#issuecomment-506962798)

### CODE REVIEW

**Comment by nickvergessen** [comment]
>  Do not defer rendering CallInfoView again until the menu is inactive

That breaks exactly what it was protecting against:
1. As moderator 1 open the password field and start typing
2. As moderator 2 change the name of the conversation
3. As moderator 1 cry because the sidebar refreshed and the password you typed is gone again...

**Comment by danxuliu** [comment]
> That breaks exactly what it was protecting against

No, it does not for two reasons:
- As explained in the commit message `renderWhenInactive` was already broken for Nextcloud 17.
- `renderWhenInactive` is not even used when the room name changes; it was only used when the room type changed and when a password was set or removed. `CallInfoView` as a whole is not rendered again when the room name changes, only the label, so if moderator 2 changes the name of the conversation moderator 1 will not cry because the password is not gone.

**Comment by nickvergessen** [comment]
Ah the editable Name thing moved the event listener to another view...

**Comment by nickvergessen** [comment]
The moderator menu can not be opened via keyboard (it immediatelly closes again)

**Comment by danxuliu** [comment]
> The moderator menu can not be opened via keyboard (it immediatelly closes again)

You need https://github.com/nextcloud/server/pull/16863

**Comment by nickvergessen** [comment]
That fixes it, right :+1:

**Pull request merged**
