### PR TITLE
Passwords with hashtags are cut

### LINKED ISSUE #3088: Cannot set passwords starting with '#'
## Steps to reproduce
1. Create conversation
2. Share link
3. Set password starting with `#`

### Expected behaviour
Password should be set

### Actual behaviour
Password is not set. This message appears in the chat:

image

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Windows

**Browser name:** Chrome

**Browser version:**  80.0.3987.132

### Browser log

```
Nothing in the logs...
```

## Talk app

**Talk app version:** 8.0.5

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
**Operating system**: CentOS 7 

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2.27

**Nextcloud Version:** 18.0.2

**List of activated apps:**

```
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - groupfolders: 6.0.1
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.3
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.5
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.borntoberoot.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.borntoberoot.net",
        "dbtype": "mysql",
        "version": "18.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "defaultapp": "files",
        "skeletondirectory": "",
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Server log (data/nextcloud.log)
```
Nothing in the logs...
```

Can anyone confirm this issue?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #3088 

See issue for steps

### CODE REVIEW

**Comment by nocerainfo** [comment]
Let users now What type of passwords they can/cannot set in TALKS, i had to find out the hard way. a notification is a must!

**Comment by nickvergessen** [comment]
Well they should be able to set anything and it works again soon

**Comment by nickvergessen** [comment]
Backport in https://github.com/nextcloud/spreed/pull/3145

**Pull request merged**
