### PR TITLE
Fix flickering while dragging files on safari

### LINKED ISSUE #8917: Drag-n-drop modal on ChatView flickers on `mouseover`, `mouseleave` events
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a chat
2. Drag a file to the chat - Modal pops up
3. Try to move a file above borders and text

### Expected behaviour
Modal should be stable

### Actual behaviour
See video:
[drag-drop-flicker.webm](https://user-images.githubusercontent.com/93392545/222408221-8b6b4093-2570-402d-aad3-b278ac8e8773.webm)

## Talk app

**Talk app version:** (16 and below)

### PR DESCRIPTION
**Pull request by marcoambrosini**
fix #8917

### CODE REVIEW

**Comment by marcoambrosini** [comment]
@danxuliu please review with your brand new mac 😆

**Review by SystemKeeper — APPROVED** [review]
Tested and works much better now.

**Review by Antreesy — APPROVED** [review]
Don't need this stuff now, but still, works fine

https://github.com/nextcloud/spreed/blob/02cee972d67c0b539cd49144dbbbf6821cdf4a20/src/components/ChatView.vue#L197

**Comment by AndyScherzinger** [comment]
Might fix the drag&drop flickering for Safari for files @susnux @skjnldsv

**Comment by susnux** [comment]
> Might fix the drag&drop flickering for Safari for files

What is the problem on safari? Is there a ticket somewhere?

**Comment by Antreesy** [comment]
> What is the problem on safari? Is there a ticket somewhere?

They might refer to this:

https://github.com/nextcloud/spreed/assets/93392545/7a936ecf-7e92-4235-b5c0-b136a5c1ff1a

**Pull request merged**
