### PR TITLE
Fix participant type change with external signaling server

### PR DESCRIPTION
**Pull request by danxuliu**
The external signaling server expects to receive a `participants` message from the backend notifier when the participants in a room change. This message is in turn sent as a [participants update signaling message to the clients](https://github.com/nextcloud/spreed/blob/f5683d1771ff9f079653eb31c217e0568f812ecd/src/utils/signaling.js#L928), and the WebUI [updates the list of participants](https://github.com/nextcloud/spreed/blob/08b492054469f43e5c9cdcc2880bba19be723306/src/components/RightSidebar/Participants/ParticipantsTab.vue#L242) whenever that message is received.

However, when the type of a participant changes the backend notifier sent an `update` message instead, which is in turn sent as a [room list update signaling message to the clients](https://github.com/nextcloud/spreed/blob/f5683d1771ff9f079653eb31c217e0568f812ecd/src/utils/signaling.js#L925), but it does not trigger any update in the participants list of the WebUI.

Now a `participants` message is sent too by the backend notifier when the participants in a room change, so the WebUI updates the list of participants when handling the participants update signaling message; the WebUI could have been modified to rely on the room list update signaling message instead, but using the other message seemed more appropriate.

Note that the already existing `update` message sent by the backend notifier is kept for now, as removing it may break the clients in unexpected ways (although it should go away in the future).

This issue has been happening since always, but before Talk 8 it was mostly hidden due to how the UI was updated. In Talk 7 and previous [the participants were fetched again whenever there was a change in the participant list data from the conversation or the number of guests](https://github.com/nextcloud/spreed/blob/stable17/js/models/participantcollection.js#L54-L59). This caused an update of the participant models and a re-rendering.

The issue was only noticeable when a guest was promoted to a moderator, as in that case there was no change in the participant list data nor in the number of guests. A backport to _stable17_ would need to be done manually, and it is probably not worth it (although if needed it should be very easy to do).

@Ivansss @mario You may want to check whether the mobile clients need some adjustment or not when handling participant type changes to be able to properly filter the `forceMute` message of #3015.

## How to test
- Setup the external signaling server
- Create a group conversation as user A
- Add user B and user C
- In a private window, join the conversation as user B
- In another browser, join the conversation as user C
- Promote user B to moderator

### Result with this pull request
The participant list for user C is updated and user B is shown as a moderator.

### Result without this pull request
The participant list for user C is not updated and user B is not shown as a moderator in it until user C reloads the page.

### CODE REVIEW

**Comment by fancycode** [comment]
Code looks good, could you please also add a test in https://github.com/nextcloud/spreed/blob/master/tests/php/Signaling/BackendNotifierTest.php?

**Comment by danxuliu** [comment]
> could you please also add a test

Of course, I always happy to add more tests ;-)

**Comment by danxuliu** [comment]
Tests added.

**Pull request merged**
