### PR TITLE
Add system messages for group attendees

### LINKED ISSUE #5730: Adding or removing a group from a room does not show a system chat message
## Steps to reproduce
1. Add a group to a conversation
2. Remove a group from a conversation
3. Check the chat

### Expected behaviour
There should be a system message saying:
> You added group X
> You removed group X

### Actual behaviour
```
```

This only become relevant now that we track the groups

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5730

### CODE REVIEW

**Comment by nickvergessen** [comment]
Unit tests need adjusting

**Comment by PVince81** [comment]
code looks good so far, nice one!

**Comment by nickvergessen** [comment]
Ready to review

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
