### PR TITLE
Get rid of "[audio|video][On|Off]" datachannel messages.

### PR DESCRIPTION
**Pull request by fancycode**
Instead of sending something through the datachannels to all peers, a client locally detects if a remote peer is sending audio and/or video and updates the local UI accordingly.

This fixes / implements my suggestion from #397.

### CODE REVIEW

**Comment by nickvergessen** [comment]
For me this works only initial. But when I (un)mute my mic later on, the famous mic icon is not displayed above the username anymore.

**Comment by nickvergessen** [comment]
Moving to 3.1 because of timing reasons

**Comment by nickvergessen** [comment]
@Ivansss whats the status here?

**Comment by Ivansss** [comment]
Not consistent. Sometimes audio mute is detected (and the mute indicator is shown) some others not.

**Comment by fancycode** [comment]
With #911 we will have a single location containing the participant state and information if audio and/or video is published. We then wouldn't need the "[audio|video][On|Off]" events any longer.

**Comment by nickvergessen** [comment]
I'm closing this now, because with the upcoming replacement of the webrtc lib, this needs a major redo anyways. So we can also just redo it from scratch.

**Pull request closed without merging**
