### PR TITLE
Get password from session if not given when joining room

### PR DESCRIPTION
**Pull request by danxuliu**
This pull request was extracted from [the lobby pull request](https://github.com/nextcloud/spreed/pull/1926), as the change is not needed for the current lobby UI but it should be kept anyway.

As mentioned in [the lobby pull request](https://github.com/nextcloud/spreed/pull/1926#issuecomment-525259604):

> The commit itself introduced a regression when joining a password protected conversation as a logged in user (I have added an acceptance test that shows it); I fixed it for logged in users following the change you made for guests... but please check it :-)

Besides that I have added some acceptance tests that check that it is possible to join a password protected room again without having to enter again the password. @nickvergessen I am not sure if that is the expected behaviour (as [it is not exactly what you described](https://github.com/nextcloud/spreed/pull/1926#issuecomment-525287425) and it requires an additional change from what you originally did to not remove the password after joining the room), so please check that too; if that is not the expected behaviour the last fixup commit (the one that keeps the password after joining the room) needs to be dropped and the last acceptance tests adjusted to show that it is needed to authenticate again.

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Besides that I have added some acceptance tests that check that it is possible to join a password protected room again without having to enter again the password. 

That is no intended. It should re-ask when you completely finished joining the room. Just not if there happened an error in between the loading of the room and the joining (like there used to be the lobby reload to check if the lobby is still enabled).

Otherwise anyone can visit all your public rooms again as long as the session didn't time out (default 1h).

**Comment by nickvergessen** [comment]
Rebased and fixed up, now waiting for hours on drone again...

**Comment by danxuliu** [comment]
> That is no intended. It should re-ask when you completely finished joining the room.

Ah, OK; I was not sure because public shares do not need to authenticate again.

> Rebased and fixed up

Oops, I force pushed too :-S Anyway the differences are not important.

**Comment by nickvergessen** [comment]
So if we both did the some changes, I expect the tests to pass too => merging

**Pull request merged**
