### PR TITLE
Own video is too big, setting it to 22%

### PR DESCRIPTION
**Pull request by anstue**
#1442

### CODE REVIEW

**Comment by nickvergessen** [comment]
Thanks for your PR @anstue 
Sorry for leaving it open for so long at the moment.
My problem is, I think it makes your video unnecessary small on one-to-one and 3 people calls, while for other calls #1056 will kick in and clean up the UI so it's more usable.

**Comment by nickvergessen** [comment]
But well, I leave it up to @jancborchardt if we should merge this intermediate step.

**Comment by anstue** [comment]
Thanks for the update! Maybe a css solution which makes the div resizable would be nice?
e.g.:
div {
    resize: both;
    overflow: auto;
} 

I tested it in Firefox an it looks promising.

**Comment by jancborchardt** [comment]
Seems good as an intermediate step to https://github.com/nextcloud/spreed/issues/1056, thank you @anstue! You are also very welcome to look into #1056 then, if you are interested?

> Maybe a css solution which makes the div resizable would be nice?

We want to have stuff as automatic as possible, manual resizing should not be necessary. :)

**Pull request merged**
