### PR TITLE
chore: audit JS dependencies

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

Audit JS dependencies

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it

### CODE REVIEW

**Review by DorraJaouad — APPROVED** [review]

**Comment by Antreesy** [comment]
Audit bumps @nextcloud/capabilities to 1.2.0, which has `"npm": "^10.0.0"` against stable28 `"npm": "^9.0.0`, so I'm not so sure that we could do that

**Comment by DorraJaouad** [comment]
I think it's fine? there are also a couple of deps that have `"npm": "^10.0.0"` and everything looks okay :p. 
Or we can just bump npm too ?

**Comment by Antreesy** [comment]
> When doing dependency resolution, make sure that all the packages being installed will work with the running version of node.

Would be better to match the server. But I see in package-lock.json, that some other nextcloud libraries are already bumped to npm:^10 version, so one more wouldn't do more harm

**Comment by ShGKme** [comment]
> which has `"npm": "^10.0.0"` against stable28 `"npm": "^9.0.0`, so I'm not so sure that we could do that

We have too strict `engines` requirements which does not reflect actual requirement. We don't use anything from new `npm` versions, so it should be fine.

**Review by ShGKme — APPROVED** [review]

**Pull request merged**
