### PR TITLE
Provide multiple STUN servers to webrtc client

### PR DESCRIPTION
**Pull request by brknkfr**
- Provide multiple STUN servers to webrtc client when specified in the nextcloud backend instead of just 1 random one

### CODE REVIEW

**Review by danxuliu — CHANGES_REQUESTED** [review]
[As explained in the pull request for the TURN server settings](https://github.com/nextcloud/spreed/pull/5491#pullrequestreview-651553857) the returned `stunservers` object resembles the `RTCIceServer` dictionary, but it is just data passed to the clients which each client parses on its own way.

In the case of the STUN server the `url` parameter must be kept too (it is used by [the iOS client](https://github.com/nextcloud/talk-ios/blob/4508011d5d441b32e1296b3368769ac0674d3613/NextcloudTalk/NCSignalingController.m#L78) and [the Android client](https://github.com/nextcloud/talk-android/blob/bd8edbc17fb8c79bafe66658daef8e4321dc53d7/app/src/main/java/com/nextcloud/talk/controllers/CallController.java#L1063-L1066); the WebUI uses [the `stunservers` object as is](https://github.com/nextcloud/spreed/blob/d055d8f98717cdc8b8a979f3c7d04dd3ab120fd0/src/utils/webrtc/simplewebrtc/simplewebrtc.js#L181)). Moreover, note that the `url` parameter of the STUN server must be a string, not a list with a single element.

Similarly to the other pull request, composing the urls should be done in `SignalingController::getSettings`. In this case then it is probably not needed to have a `Config::getStunSettings` method, as it will just forward to `Config::getStunServers`. Although for simmetry with the TURN servers you could also add a `Config::getStunSettings` that returns a hardcoded `stun:` scheme, but I have no preference, as you prefer.

**Comment by nickvergessen** [comment]
> In the case of the STUN server the url parameter must be kept too (it is used by the iOS client and the Android client;

Same comment here as with the turn:
We can change that and break it (if it is any good and better or clearer or ....), as there is no compatibility possible between Talk 11 (conversations api v1-3) and Talk 12 (conversations api v4) as we can not make the multiple sessions compatible with uniqueness, we can also add a breaking signaling thing on top, especially when it's just about changing a single character

**Comment by brknkfr** [comment]
Thank you for the review.

> Similarly to the other pull request, composing the urls should be done in `SignalingController::getSettings`. In this case then it is probably not needed to have a `Config::getStunSettings` method, as it will just forward to `Config::getStunServers`. Although for simmetry with the TURN servers you could also add a `Config::getStunSettings` that returns a hardcoded `stun:` scheme, but I have no preference, as you prefer.

I completely removed `Config::getStunServer` and `Config::getStunSettings` and moved building of the urls to  `SignalingController::getSettings`.

**Comment by danxuliu** [comment]
Like explained in the other pull request I have added a fixup to keep the format, and I have extracted the format changes to [their own pull request](https://github.com/nextcloud/spreed/pull/5582).

Please remember to adjust the commit message after doing the fixup :-)

**Review by brknkfr — COMMENTED** [review]
https://github.com/nextcloud/spreed/pull/5582

**Review by brknkfr — COMMENTED** [review]
Unifying urls will be done #5582

**Pull request merged**
