### PR TITLE
Label button 'Start call' if none is in progress yet, fix #976

### LINKED ISSUE #976: If the room does not have an active call yet, button should say "Start call"
Currently the button says "Join call" in any case, which makes it seem like there’s always a call going on.

It would be better to label it "Start call", and only label it "Join call" when others already are in an active call.

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #976, please check @nickvergessen :)

### CODE REVIEW

**Comment by nickvergessen** [comment]
In the modelsEvent section please add:
```js
 			'change:hasCall': function() {
 				this.renderWhenInactive();
 			},
```

**Comment by jancborchardt** [comment]
@nickvergessen thanks, done :)

**Comment by nickvergessen** [comment]
Failing tests are because of the server change and should work after #992  right @danxuliu ?

**Comment by danxuliu** [comment]
@nickvergessen Right; rebasing onto master should make the error go away.

**Pull request merged**
