### PR TITLE
Move ChatView and RichObjectStringParser to precompiled Handlebars templates

### PR DESCRIPTION
**Pull request by danxuliu**
In Nextcloud 15 [the default Content Security Policy disallows unsafe eval expressions](https://github.com/nextcloud/server/commit/5b61ef9213df0ff67ebd5b9c88a8e1562f367351), so Handlebars templates can no longer be compiled at runtime.

For the time being [that default Content Security Policy was lifted for Talk](https://github.com/nextcloud/spreed/pull/1253) so `Handlebars.compile` could still be used. However, this only applies to Talk itself; when using Talk components in other apps they must abide to the Content Security Policy of those apps. As `ChatView` and, indirectly through the `ChatView`, `RichObjectStringParser`, are going to be used in the _Files_ app they have been moved to precompiled Handlebars templates (which are still compatible with the regular Talk UI, and even Nextcloud 14 if a backport was needed).

### CODE REVIEW

**Comment by nickvergessen** [comment]
Still needs the CSP eval stuff?

**Comment by danxuliu** [comment]
>  Still needs the CSP eval stuff?

No (for the ChatView and RichObjectStringParser), that is exactly the point of this pull request.

**Comment by nickvergessen** [comment]
Yeah but we still cant remove the hacks we have in place.

**Comment by danxuliu** [comment]
>  Yeah but we still cant remove the hacks we have in place.

Yes, I know. That is why I said _No (for the ChatView and RichObjectStringParser)_; the hacks will be able to be removed later.

**Comment by danxuliu** [comment]
>  Works

No, it does not if you change the namespace because at the point at where it is used it has not been defined yet...

**Comment by nickvergessen** [comment]
Fixed, but that should be in a different spot I guess

**Pull request merged**
