### PR TITLE
Prevent the chat from compressing too much on narrow screens

### PR DESCRIPTION
**Pull request by ma12-co**
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by danxuliu** [comment]
I have merged the two commits in a single one, done some further cleanups (remove spaces that were added by mistake, remove the `overflow-x: hidden` rule as [it is covered by `overflow: hidden`](https://github.com/nextcloud/spreed/blob/bf28b19c6e1a5a290db64f0b47c587b444a555e4/css/style.scss#L53), and remove the `display: block` rule as it had no effect, as [it was overriden by a rule defined in the server](https://github.com/nextcloud/server/blob/3c30d293fa1d52ff51581091e3d39a30ac7474d3/core/css/apps.scss#L617)), and added a more descriptive commit message.

There is still one issue, though. As the app content is no longer compressed the fullscreen button is not visible when the sidebar is open in narrow screens. It is not something terrible, as it can be used anyway just closing the sidebar, but could you take a look at how it could be done that the button is shown also when the sidebar is visible? I guess that you may need to move the button from `#app-content-wrapper` to `#app-sidebar-wrapper` (where the sidebar toggle is), but maybe there are other easier solutions.

Also, do you have access to Safari, Edge and/or Internet Explorer 11 (this last one is mostly curiosity, as there are other broken things on it already) to test these changes?

**Comment by ma12-co** [comment]
Ok Daniel, I'll take a look at the fullscreen button. Regarding the browsers, I have access to everything but Safari. How do you do your cross browser tests? Do you have any suggestion?

**Comment by danxuliu** [comment]
No good suggestions, unfortunately; until recently we only supported Firefox and Chromium, and that is what I tested with. Now that we support other browsers I usually test with Firefox and Chromium, and from time to time (or if the change seems "dangerous") I open the virtual machine and test with Edge (and if I am feeling brave Internet Explorer 11 :-P ); I do not have access to Safari either, but @Ivansss and @mario do.

**Comment by danxuliu** [comment]
Rebased on master.

As the fix is more important than the pending issue (the fullscreen button is not visible when the sidebar is open in narrow screens), and the pending issue will be solved more easily once some other changes are made in the layout I think that this should be merged even with the pending issue ;-)

**Comment by nickvergessen** [comment]
> the fullscreen button is not visible when the sidebar is open in narrow screens

I would even call this accepted behaviour 🤷

**Pull request merged**
