### PR TITLE
Start with sidebar

### PR DESCRIPTION
**Pull request by nickvergessen**
> bildschirmfoto vom 2017-09-08 15-50-38

### CODE REVIEW

**Comment by jancborchardt** [comment]
Ah so the Chat should also be in this sidebar then, right?

**Comment by nickvergessen** [comment]
I don't care about chat until it is here. Currently it holds only moderation features, so I would only show it for moderators. But we can change that in the future, once chat is there.
I guess it would just be another tab view then...

**Comment by jancborchardt** [comment]
I made some changes, however they are not taken into account since the file https://github.com/nextcloud/server/blob/master/apps/files_sharing/css/sharetabview.scss is not loaded in this app it seems. Can we make that happen somehow? A simple `@import '../../files_sharing/css/sharetabview.scss';` did not work because of:
```The resource from “http://localhost/nextcloud/apps/files_sharing/css/sharetabview.scss” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).```

Regarding the other things:
> -  Some marker for User is currently in this call

Sort the people currently in this call up top. People not in the call should additionally be half-transparent. Give the `li` element of participants not in the call the class `.participant-offline` and the CSS I added will display them accordingly. (See the example code I added.)

>  Some marker for User is a moderator/owner

Sort them at the very top (even if offline), give the `li` element of moderators the class `.participant-moderator` and put a `(moderator)` behind their name in a span called `.participant-moderator-indicator`. (See the example code I added.)



Some further questions:
- What does the "start/stop webinar" button exactly do?
- I guess we should move the actions from the left sidebar (Add person, Rename, Share link, Delete call) fully to the sidebar? And the 3-dot button will open the sidebar. Otherwise there will be duplication.

**Comment by nickvergessen** [comment]
Can you commit the `sharetabview.scss` then I can do the import

**Comment by nickvergessen** [comment]
> What does the "start/stop webinar" button exactly do?

It's the schedules call feature from: https://github.com/nextcloud/spreed/issues/347#issue-240589470

> I guess we should move the actions from the left sidebar (Add person, Rename, Share link, Delete call) fully to the sidebar? And the 3-dot button will open the sidebar. Otherwise there will be duplication.

I thought the same, but then you can not leave/delete rooms without having to join them. The three dot is available while you are in a different room/call. The sidebar is not. Also as said before, currently the side bar is moderators only. For normal users it would be pretty empty, or would you show the user list there too?

**Comment by jancborchardt** [comment]
@nickvergessen you mean just duplicate the sharetabview.scss here? Is there no way to call the original?

**Comment by nickvergessen** [comment]
I would just copy the necessary elements to a new file. Depending on another app is never a good idea.

**Comment by jancborchardt** [comment]
I'll move sharetabview to core then cause we shouldn't copypaste stuff all over.

**Comment by nickvergessen** [comment]
@Ivansss can you review this first step?

> bildschirmfoto vom 2017-09-08 15-50-38

I will then create a new issue for the remaining tasks

**Comment by nickvergessen** [comment]
Remaining todos: https://github.com/nextcloud/spreed/issues/399

**Comment by nickvergessen** [comment]
@Ivansss ping 🏓

**Comment by Ivansss** [comment]
Guests have no avatar and no name in the sidebar.

screen shot 2017-09-19 at 10 46 05

**Pull request merged**
