### PR TITLE
Fix bool logic for inCall flag

### PR DESCRIPTION
**Pull request by nickvergessen**
```php
var_dump(true & 1 !== 0); // int(1)
var_dump((true & 1) !== 0); // bool(true)
var_dump(true & (1 !== 0)); // int(1)
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
Well for the flag with 1 it works the same way, yes. But if you check flag 2 it fails:

```
var_dump(true & 2 !== 0); // int(1)
var_dump((true & 2) !== 0); // bool(false)
var_dump(true & (2 !== 0)); // int(1)
```

the problem is, that php first evaluates !== and then & if there are no brackets

**Comment by nickvergessen** [comment]
its the same in js, so fixed it there too:
```js
console.log(true & 1 !== 0);
console.log((true & 1) !== 0);
console.log(true & (1 !== 0));
1
true
1
```

**Comment by fancycode** [comment]
The first variable in your checks is a number (i.e. the flags), not `true`/`false` - or am I missing something?

**Comment by nickvergessen** [comment]
makes no difference:
```php
var_dump(1 & 2 !== 0); // int(1)
var_dump((1 & 2) !== 0); // bool(false)
var_dump(1 & (2 !== 0)); // int(1)
```

**Comment by fancycode** [comment]
You are right. I was testing the other way round (`2 & 1 !== 0`) which returned `false` (from `2 & true`), so I got confused :see_no_evil: Anyway, still lgtm :smiley:

**Pull request merged**
