### PR TITLE
Fix broken call menu

### LINKED ISSUE #231: Call menu input box positioning broken
Check this out:
capture du 2017-01-24 01-24-29
capture du 2017-01-24 01-24-09
Instead it should be like before:
- The share link input box below the »Share link« row, full width. Delete button on the same row as the »Share link« label, to the right. Copy button on the right in the input field.
- Rename input box should be full width too, with the confirm button on the right inside the input box
- Also the position is slightly off (too far left) and the top right border radius is missing

Also, the rename input box should have the current name prefilled and selected as a whole. cc @Ivansss

### PR DESCRIPTION
**Pull request by Ivansss**
- Fix #231

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Ivansss I fixed the position of the rename field arrow. Can you re-review? :)

**Comment by ArnY** [comment]
Hrm, still looks broken here. Both on firefox (47 & 51) and Chrome, both on linux and windows. Just cloned the master branch, built, untarred the artifacts files in my nextcloud instance's apps folder and the call menu still looks broken (assets pipelining's offin my config file). Actually 71d332b doesn't seem to change anything from previously:
spreedshot

**Comment by Ivansss** [comment]
@ArnY could you tell us which Nextcloud (core) version are you using?

**Comment by ArnY** [comment]
it's nextcloud 11.0.2

**Comment by Ivansss** [comment]
I was not able to reproduce this issue in a Nextcloud 11.0.2 instance.
Do you see any errors in your Javascript console?

**Comment by ArnY** [comment]
The problem's on my side. Sorry about that. Forgot to update our apps.css after the 11.0.2 upgrade (or even after upgrading to nextcloud 11...).

**Pull request merged**
