### PR TITLE
Fix dangling references to "collectionsintegration.js"

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #2289 

_js/collectionsintegration.js_ was renamed to _js/main.js_, but the name was not updated in several places.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Vue files are still not compiled. should we do this here?

**Comment by danxuliu** [comment]
Most acceptance test failures are legit and come from merging other pull requests too fast. I will fix them in follow-up pull requests.

**Pull request merged**
