### PR TITLE
make links in chat clickable

### PR DESCRIPTION
**Pull request by blizzz**
solves #533  

screenshot_20180111_155633

### CODE REVIEW

**Comment by danxuliu** [comment]
I have amended your commit to fix a lint issue (`OCP' is not defined`).

**Comment by danxuliu** [comment]
>  Also very nice that https:// gets cut but http:// does not to call attention to it. :)

@jancborchardt Is that the technical user in you talking? :-P A normal user does not know nor care about HTTP and HTTPS; in fact I would even dare to say that it is confusing that some links include the protocol while others do not.

Personally I would prefer the protocol to be kept. Maybe now it is the technical user in me talking, but I think that people can associate something that looks like _http://_ to a webpage, even if they may not be able to correctly type _http://_.

Having said that, I do not have a strong opinion on this either ;-)

**Comment by blizzz** [comment]
@Ivansss is your server up to date? needs master after https://github.com/nextcloud/server/pull/7680

**Comment by jancborchardt** [comment]
@danxuliu yes, it is slightly technical. However the underline is the important part which classifies it as a link. Anyhow I consider it detail. :)

**Pull request merged**
