### PR TITLE
Handle pasting screenshots to the chat message form

### LINKED ISSUE #2172: Copy paste image into the chat
We are using Riot for our teams and often we take screenshots, copy and paste them in the Riot chat directly. Such a useful little thing. Helps to report bugs and such. Would be fantastic to see it implemented.

### PR DESCRIPTION
**Pull request by guryanovev**
Fix #2172

### CODE REVIEW

**Comment by nickvergessen** [comment]
Thanks a lot for the patch @guryanovev 
We are currently very busy but will have a look later this week!

**Comment by nickvergessen** [comment]
I have to admit I find it a bit confusing that it only works inside the chat input, while drag n drop works everywhere.

**Comment by ediazcomellas** [comment]
Wow, great work!

**Comment by jancborchardt** [comment]
@guryanovev by the way, we have a Talk development chat for all contributors where we can invite you with a guest account – is it ok to add you there? Would be cool to have you :)

**Pull request merged**
