### PR TITLE
Fix MsTeams and Steam Matterbridge config

### PR DESCRIPTION
**Pull request by eneiluj**
As mentioned in #4719, `channel` is the key used for all services in `gateway` section.

MsTeams is now finally working.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
I guess we backport this?

Do existing configs have to be adjusted somehow?

**Comment by eneiluj** [comment]
Yes we can backport. Configs are generated when bridge is saved which happens when it's toggled. No special adjustments needed.

**Pull request merged**
