### PR TITLE
Allow single quote in date-separater for french translation

### LINKED ISSUE #1016: Typo in the date separator of a text chat
Hi,

I'm running NC 13.0.4 with the last stable version of Talk / Spreed.
My system is in french, as well as NC language.

I can see a typo on text discussions when the date is today, spelled **_Aujourd'hui_** in french :

image

I guess this should be corrected :)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1016

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review @GLLM as this fixes an issue you reported. :)

**Comment by GLLM** [comment]
@jancborchardt : I would gladly do so .... but I'm not sure how I shall proceed ! 
* deploy a new instance and test ? 
* just check what the code is doing ?
* what else, or what should I just do ?

Thanks

**Comment by nickvergessen** [comment]
You could try to find the code that is modified in https://github.com/nextcloud/spreed/pull/1048/files and add the green lines and see if after a forced refresh of your browser the `'` is now displayed correctly.

**Comment by nickvergessen** [comment]
@jancborchardt thanks for selecting french in the language dropdown quickly so we can merge this for the next release :sunglasses:

**Comment by nickvergessen** [comment]
Well you can't approve issues, because you are not part of the organization, but I will just merge this now, thanks for testing :)

**Comment by GLLM** [comment]
My pleasure. Happy to be able to help a very tiny bit ...

**Pull request merged**
