### PR TITLE
Better grouping and timestamps

### LINKED ISSUE #1799: Better message density & grouping
The density of the chat is too high I think.
It could benefit from shrinking a bit and having messages more close together.
As a comparison (some might argue this is not really readable), My irc screen have around 50 messages. Current talk is 9-10. Whatsapp is around 10 as well. Signal is ~12...

I would say merging a bit could be nice.

___ 

Default clickable area is 44px.
If we have the timestamp inline with the message and the avatar, it's one message = 44px.
My window is around 900px height, so it should be able to contain 20 messages.

Rough example: 
Capture d’écran_2019-05-09_11-36-25

@nextcloud/designers @jancborchardt any ideas to improve my bad mockup?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1799 

* timestamp is shown after 5 messages or 30 seconds
* author is shown after 20 messages or 1 hour

### CODE REVIEW

**Comment by jancborchardt** [comment]
I like the better grouping in the pull request (and I would improve more on it if that’s ok), but why is it mixed with removing the relative time stamp?

- We use relative time stamp basically everywhere, and it is much better to see when recent messages happened. Otherwise you always need to double check with a clock, or know what time it is.
- We could use relative for messages which are less than 24 hrs old, and timestamp for older than that.
- Even there, not even Slack, WhatsApp etc include the seconds, because it’s just too much unnecessary information. The order of messages is enough to show when what happened.

**Comment by nickvergessen** [comment]
I mixed the 2 things because it's changes in the same section and otherwise would require rebasing all the time...

> We use relative time stamp basically everywhere, and it is much better to see when recent messages happened. Otherwise you always need to double check with a clock, or know what time it is.

Well, let me quote from our instance:
> btw is it only me, or would anyone else prefer relative timestamps only for the last hour or not at all, and afterwards just show 15:36
> I just scrolled up to start reading up and though 22 .... yeah I didint work there, but actually it was hours ago, and I did actually work there

None of the existing chat programs/clients use relative timestamps... anywhere.

>We could use relative for messages which are less than 24 hrs old, and timestamp for older than that.

That is already the case, but still too confusing, see above.

> Even there, not even Slack, WhatsApp etc include the seconds, because it’s just too much unnecessary information. The order of messages is enough to show when what happened.

That is unchanged from current behaviour when the message is older than 24 hours? I prefer seconds to be shown and also have that enabled on all clients which support it. But well, fine to me to drop them too.

> I like the better grouping in the pull request (and I would improve more on it if that’s ok),

Just keep it simple, as we are mostlikely going to backport this, and also want to have improvements as 17 only ;)

**Comment by jancborchardt** [comment]
> None of the existing chat programs/clients use relative timestamps... anywhere.

Signal does it. ;) But yes, good point that no one else does it in chat. I’m ok with the timestamp but only without seconds. (As also no one else does it. ;)

**Comment by nickvergessen** [comment]
Seconds removed

**Comment by jancborchardt** [comment]
(The above said, I still think that relative time, at least for the last 24 hours, is a way better UX as it doesn't require you to do time maths in your head. But we can try out having just timestamps.)

**Comment by nickvergessen** [comment]
Rebased to check acceptance tests

**Pull request merged**
