### PR TITLE
Add abilitiy to select localvideo

### PR DESCRIPTION
**Pull request by ma12-co**
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by nickvergessen** [comment]
I can not select my own video nor mute myself or disable the video anymore in the promoted view.

**Comment by ma12-co** [comment]
Fixed @nickvergessen

**Comment by nickvergessen** [comment]
Now the only thing missing is being able to select your own video in promoted view

**Comment by ma12-co** [comment]
Also fixed :)

**Comment by nickvergessen** [comment]
You can click on your own field when you only have an avatar and it turns the screen black?

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
