### PR TITLE
Presentation support

### PR DESCRIPTION
**Pull request by leonklingele-work**
### Missing

- [x] Support for multiple presentations
- [x] Presentation control panel (switch between presentations)
- [ ] Presentation control panel (page number selection)
- [x] ~ODF presentation support~ We no longer want this for the first version
- [x] Resume support, i.e. loading the presentation for new participants which joined after the P was uploaded __TODO__: Sometimes it doesn't work, likely the case when the peer connection is not ready yet (?)
- [ ] Fix styling issues
- [x] Load Ps inside Iframe as a security precaution

### Testing the PR

- Make sure to use a version of Nextcloud server which includes this commit: https://github.com/nextcloud/server/commit/66a5a45c503269699666df61c605d67f3c72c7c0.patch, alternatively apply the patch manually

### CODE REVIEW

**Comment by leonklingele-work** [comment]
This adds support for https://github.com/nextcloud/spreed/issues/32

**Comment by nickvergessen** [comment]
I get the following error when clicking on the "upload" button.

```
Uncaught TypeError: propertyName.match is not a function
    at dav.Client.parseClarkNotation (client.js:442)
    at dav.Client.propFind (client.js:74)
    at Client.getFolderContents (client.js:436)
    at Object._fillFilePicker (oc-dialogs.js:790)
    at HTMLDocument.<anonymous> (oc-dialogs.js:217)
    at j (jquery.js:3099)
    at Object.add [as done] (jquery.js:3145)
    at a.fn.init.n.fn.ready (jquery.js:3378)
    at Object.<anonymous> (oc-dialogs.js:210)
    at Object.<anonymous> (jquery.js:3256)
```

Another thing: can you not commit the 3rdparty stuff and instead have it done via make?
Like a lot other apps already do it. This would keep the PR and code a bit more maintainable.

**Comment by leonklingele-work** [comment]
> I get the following error when clicking on the "upload" button.

Sorry, I forgot to mention you need to apply this patch: https://github.com/owncloud/davclient.js/pull/31

> can you not commit the 3rdparty stuff and instead have it done via make

Other 3rd party stuff is currently included as well, see https://github.com/nextcloud/spreed/tree/master/js/vendor

**Comment by nickvergessen** [comment]
Due to the many conflicts and the stale progress im closing this.

**Pull request closed without merging**
