### PR TITLE
fix(chat): Don't show OOO when it's not appliable

### LINKED ISSUE #11059: Only show out of office message when applicable
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set up OOO for upcoming (not current!) vacation 24th Dec to 8th Jan
2. Have DND user status (availability or manual)

### Expected behaviour
Nothing happens

### Actual behaviour
Bildschirmfoto vom 2023-11-30 22-34-39

THe OOO api endpoint returns start and end time. We should check it before displaying.

## Talk app

**Talk app version:** main

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Fix #11059 
* Steps to reproduce in the ticket

### CODE REVIEW

**Review by ChristophWurst — COMMENTED** [review]
Only works for people with the same timezone offset from UTC

**Comment by nickvergessen** [comment]
Replaced by the applicable `/now` endpoint in https://github.com/nextcloud/spreed/pull/11062

**Comment by Antreesy** [comment]
Seems to not required anymore with new endpoint

**Pull request closed without merging**
