### PR TITLE
Remove custom listitem styles

### PR DESCRIPTION
**Pull request by marcoambrosini**
Removes unwanted border on click and other custom styles

### CODE REVIEW

**Comment by nickvergessen** [comment]
Screenshots?

**Comment by Antreesy** [comment]
Styles will be messed up with vue-lib bump PR anyway, so not really necessary at the moment

**Comment by marcoambrosini** [comment]
At the moment there's an unwanted border on click around the list-item. At least we need to take that out.

**Comment by Antreesy** [comment]
Included in https://github.com/nextcloud/spreed/pull/10626/commits/5acdc265c9f80268f5b5b709b2fa5449ecd2526b

**Pull request closed without merging**
