### PR TITLE
Fix connection quality stats not reset when setting a new peer connection

### PR DESCRIPTION
**Pull request by danxuliu**
~~Still in draft; I need to check if there is a better place to reset the stats (for example, when the ICE connection state changes), and check if it also works as expected when switching devices.~~ - It is better to reset the stats just before the analysis is started. 

Regarding switching devices I found a different issue related to stats being reset when they should not (when it is sent to other participants whether audio and video is enabled or disabled), so this needs to be fixed first before being able to check switching devices. Anyway, this will be done in another pull request.

## How to test
- Setup the HPB
- Start a call
- In a private window, join the call
- Share the screen
- Wait 10-15 seconds and stop the screen share
- Share the screen again

### Result with this pull request
The connection quality warning will not be shown.

### Result without this pull request
The connection quality warning will be shown.

### CODE REVIEW

**Review by PVince81 — COMMENTED** [review]
Code makes sense. What's missing ?

**Comment by danxuliu** [comment]
> What's missing ?

As stated in the pull request description I needed to check if there was a better place to reset the stats (there was) and check if it also worked as expected when switching devices (it will be addressed in a different pull request if needed). Now it is ready for review ;-)

**Comment by PVince81** [comment]
> > What's missing ?
> 
> As stated in the pull request description I needed to check if there was a better place to reset the stats (there was) and check if it also worked as expected when switching devices (it will be addressed in a different pull request if needed). Now it is ready for review ;-)

My internal task parser doesn't work on plain text :sweat_smile:

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
