### PR TITLE
Disable the dashboard widget with proper API

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #8233 

- [x] Requires https://github.com/nextcloud/server/pull/34832

### Before
Log:
```
│[error] 2022-10-27T09:08:09.000 no app in contex Could not load lazy dashboard widget: OCA\Talk\Dashboard\TalkWidget   
```

### After
✨

### CODE REVIEW

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Comment by nickvergessen** [comment]
Psalm will fail until Sunday when the package is done, so will rebase on Monday

**Comment by danxuliu** [comment]
psalm fails, is it just that the server API package was not updated yet or something else needs to be adjusted?

**Review by vitormattos — APPROVED** [review]

**Comment by nickvergessen** [comment]
Cleanly rebased

**Pull request merged**
