### PR TITLE
Remove bridge bot from room when bridge is disabled

### PR DESCRIPTION
**Pull request by eneiluj**
The bot user was never removed from rooms. It is now done when the bridge is disabled.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Needs a rebase

**Review by nickvergessen — COMMENTED** [review]
Looks good otherwise

**Comment by eneiluj** [comment]
Rebased

**Review by jancborchardt — APPROVED** [review]
:+1: good change, didn’t test

**Comment by nickvergessen** [comment]
Rebased and ran tests locally. All pass

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
