### PR TITLE
Set focus to message only when anchor is set

### PR DESCRIPTION
**Pull request by PVince81**
Don't set focus on message element when scrolling to the first unread
message as this conflicts with focusInput() from the message form.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Doesn't seem to work here. For whatever recent reason the chat input is disabled for a second or two and so the focusing doesnt work

**Comment by PVince81** [comment]
> Doesn't seem to work here. For whatever recent reason the chat input is disabled for a second or two and so the focusing doesnt work

Not sure what is disabling the field now.

The current/old code for focussing the field is a bit naive and is applied on mount regardless of state, and hopes that after a delay everything is fine.

**Comment by PVince81** [comment]
Got it: we have new logic that disables the field with "Joining conversation..." here: https://github.com/nextcloud/spreed/blob/master/src/components/NewMessageForm/NewMessageForm.vue#L210

Now we could wait for the joining to finish and then move the focus, but depending how long it takes it might take the user out of context if they were typing elsewhere. I guess it's not too bad though, at least to fix the regression.

I'll try the latter approach.

**Comment by PVince81** [comment]
@nickvergessen I've pushed a fix, please retry

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
