### PR TITLE
Fix "Copy link" button not clickable (resend)

### LINKED ISSUE #4311: "Copy link" at middle of screen isn't clickable/doesn't work
This has spanned multiple major versions of nextCloud now, so this is a longer standing bug. When I start a call, there's a blue button "Copy link" in the middle of the window. Clicking on it never copies the link, it does nothing. I have to go to the 3-dot menu to get the link copied.

I'm on NC20, but this has happened in NC18 and earlier versions. Latest version of Talk and previous versions too.

### PR DESCRIPTION
**Pull request by PVince81**
Resend of https://github.com/nextcloud/spreed/pull/4617

Fixes #4311

### CODE REVIEW

**Review by Chartman123 — APPROVED** [review]
Works as stated in original PR

**Review by ma12-co — APPROVED** [review]
:elephant:

**Comment by nickvergessen** [comment]
Backport?

**Comment by Chartman123** [comment]
As it's a rather small change, I'd propose to baxkport it, too 👍🏻

**Pull request merged**
