### PR TITLE
Add app icons

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @nextcloud/spreed @mario @Ivansss :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Left is the icon in this pull request, right another proposal which is a bit of a mashup with the Nextcloud logo to make it look a bit less generic. But not sure if it’s better, and it forms an »O«. What do you think @nextcloud/designers @karlitschek?
Remember it needs to fit both the app bar in Nextcloud itself, and also work on home screens of Android and iOS.

favicon-touch favicon-touch-2

**Comment by MorrisJobke** [comment]
For me it looks quite similar to the signal app 🤔 https://de.wikipedia.org/wiki/Signal_(Messenger)

**Comment by MorrisJobke** [comment]
But on the other side it's better than the current one 👍

**Comment by nickvergessen** [comment]
There is a app for each variantion of a speaking bubble nower days...

**Comment by mario** [comment]
👍 
@jancborchardt does this means I'll get all the icons PR on the android repo too? :P

**Comment by jancborchardt** [comment]
@MorrisJobke yeah I know. But hey, it’s a speech bubble. :\ That’s why I also asked about the other option above: https://github.com/nextcloud/spreed/pull/451#issuecomment-339658406

What do you think?

**Comment by karlitschek** [comment]
I like both! Maybe the one with the hole is more Nextcloudish and less Signalish ;-)

**Comment by jancborchardt** [comment]
Will change to the circle-version then! :) As it looks less like Signal, and also the speech bubble seems a bit text-only, whereas the circle looks a bit more like a camera maybe. :)

**Comment by MariusBluem** [comment]
Is it possible to make the arrow a bit larger and the actual bubble a bit smaller ... otherwise there is no chance to see what this is, especially if you only have favicons :(

**Comment by skjnldsv** [comment]
Really like it too! :)

> (Stupid?) idea - change the shape to be more camera-like, but keep the arrow, so it's presents both "video" and "chat"...

Not stupid, it could represent a shutter, it could be a great idea :)
shuttercamera

**Comment by jancborchardt** [comment]
There’s tons of ways to do it, lots of drawbacks though. @skjnldsv the shutter looks too much like a camera app which only makes pictures. @pixelipo webcams like that are largely a thing of the past.

I’m merging this for now since the new version is nice, doesn’t look so similar to Signal, and has some similarity to the Nextcloud logo so works nicely next to the normal app icon. Besides, it will say »Nextcloud Talk« below. :)

**Comment by skjnldsv** [comment]
Okay then! ;)
LGTM!

**Pull request merged**
