### PR TITLE
Bump @nextcloud-vue to 3.5.1

### PR DESCRIPTION
**Pull request by PVince81**
Brings in the updated Avatar component which now uses Popover.

Fixes issue with dropdown menu overlap with other avatars in the
messages list.

Fixes https://github.com/nextcloud/spreed/issues/4147

### CODE REVIEW

**Review by nickvergessen — CHANGES_REQUESTED** [review]
- [x] Regressions: Icons are not inverted any longer on dark mode
- [ ] Instead of scrolling the popover now just overlaps the avatar. I think elipsis would be better

Bildschirmfoto von 2021-01-20 10-45-02

**Comment by nickvergessen** [comment]
> Regressions: Icons are not inverted any longer on dark mode

I guess this needs fixing in server, as https://github.com/nextcloud/server/blob/f04b182b9447231b32cd5b5f8060314dee4fd801/apps/accessibility/css/dark.scss#L63 no longer matches.

**Comment by PVince81** [comment]
> Regressions: Icons are not inverted any longer on dark mode

Seems the difference with the other popover menus is that in the popover menus we use "icon-x" classes for icons, but for this actions menu it's image URLs directly.

**Comment by PVince81** [comment]
> > Regressions: Icons are not inverted any longer on dark mode
> 
> I guess this needs fixing in server, as https://github.com/nextcloud/server/blob/f04b182b9447231b32cd5b5f8060314dee4fd801/apps/accessibility/css/dark.scss#L63 no longer matches.

Dark mode fixes here:
- [ ] add classes for more specific targetting (not wanting to target images in a non-menu inside popover): https://github.com/nextcloud/nextcloud-vue/pull/1674
- [ ] server changes to dark.css to make it look better (screenshots included there): https://github.com/nextcloud/server/pull/25229

**Comment by PVince81** [comment]
> Instead of scrolling the popover now just overlaps the avatar. I think elipsis would be better

Ellipsis means we'd need a tooltip also to be able to display the full row as there might be words behind the name like "sprechen" in German.

I looked at the actions menu and apparently it wraps there with a fixed max width, so we could do the same here:
image

Eventually once we switch to actions menu for avatars (see https://github.com/nextcloud/nextcloud-vue/pull/1670) this will be in place as well implicitly.

For now I'll manually adjust these to the avatar's popover menu.

**Comment by PVince81** [comment]
- [ ] long text fixes (screenshots included there): https://github.com/nextcloud/nextcloud-vue/pull/1675

**Comment by PVince81** [comment]
bumped to 3.5.1 now

**Comment by PVince81** [comment]
all merged, I've retested this PR and it works.

**Review by ma12-co — APPROVED** [review]

**Pull request merged**
