### PR TITLE
Dark theme fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
Before:
dark theme chat sidebar before 

After:
dark theme chat sidebar files

Please review @danxuliu @nextcloud/designers :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Fixed some additional things, and there’s also further issues which someone else needs to check out though:

- [ ] All icons in the sidebar which are on a background should be white, not black
  icons in sidebar should be white
- [ ] Same for the create conversation menu
   top icons in menu should be white
- [ ] And for the share menu (it is correct in the share dialog itself, and for the other icons)
   participant icons should be white
- [ ] Password protect icon should be white
   password icon should be white

**Comment by nickvergessen** [comment]
I'm not sure which share menu you are talking about?
If you talk about the "add participant" menu, that was fixed too by me, but I didnt tick it, since im not sure.

On the password thingy I don't know what's wrong. we use the correct class:
https://github.com/nextcloud/spreed/blob/95e69a322e1317ae5fc19312ede7b003f4dfd9e7/css/style.scss#L532
https://github.com/nextcloud/spreed/blob/79632c1562c1fd33aefb5538b4b5bec1e6a24fb6/js/views/callinfoview.js#L51

Also once a password is set, it works as expected too.

**Comment by nickvergessen** [comment]
Okay, found the problem. The regex in https://github.com/nextcloud/server/blob/20519434879dd0ee9278d0871d92e9c11295adfd/lib/private/Template/IconsCacher.php#L188 doesn't match if there is a transformation as well:
https://regex101.com/r/booyc4/1

I removed the transformation for now and adjusted the viewport, I guess it still looks the same, at least I couldn't see a difference. but maybe you @jancborchardt or @skjnldsv know more?

**Comment by skjnldsv** [comment]
@nickvergessen which icon are we talking about?
Also: yes we then need to adapt the regex :)
Could you help?

**Comment by nickvergessen** [comment]
The image is in https://github.com/nextcloud/spreed/pull/1451/commits/2ee1b413f67968d2b66f44e54620744b861fede1

I'm very bad at regexes, especially with look-ahead and stuff, but I can try

**Comment by jancborchardt** [comment]
Looks all good with your fixes @nickvergessen, thanks a lot! :) :+1:

**Comment by danxuliu** [comment]
Since 95e69a322e1317ae5fc19312ede7b003f4dfd9e7 non-avatar icons are shown in black instead of white with the normal theme. Is that intended?

Conversation list:
talk-icon-black-conversation-list

Create conversation:
talk-icon-black-create-conversation

Add participant:
talk-icon-black-add-participant

**Comment by nickvergessen** [comment]
Yes had to, the other apps do this since a long time already, i tried to block it because i think white looks more beautiful, but on dark mode nothing is visible otherwise

**Comment by jancborchardt** [comment]
Hmm, @nickvergessen I agree with you that white looks more beautiful (and is in line with our placeholder images with the initial).

On dark mode it should also be white – we probably need to add an exception in the dark theme so that icons in these circles are never inverted. (We have the same issue for icons in primary buttons, like for creating a new user in the user management. Icons in primary buttons should also be white in both normal and dark theme.)

@skjnldsv @juliushaertl what do you think? A rule in the color inversion to skip the icons inside other forms (at least if it’s standards like these avatar-like elements, or primary buttons) would probably be good?

**Pull request merged**
