### PR TITLE
fix: replace v-tooltip with native title

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix leftovers from v-tooltip usage

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image
image | image
image | image
image | image
image | image

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [x] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team

### CODE REVIEW

**Review by DorraJaouad — COMMENTED** [review]
You can also rename 
`MessageButtonsBar.vue` : `readInfo.*tooltip` (so are in `Message.vue`
`MessageBody.vue`: `sendingErrorIconTooltip` | `loadingIconTooltip `| `readInfo.*tooltip`
`NewMessageAudioRecorder.vue`: `*RecordingTooltip`
`TopBarMediaControls.vue`

**Comment by Antreesy** [comment]
Checked
image

**Review by ShGKme — APPROVED** [review]

**Review by DorraJaouad — APPROVED** [review]
all good

**Pull request merged**
