### PR TITLE
Add an integration test for the scaling tests

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
## Patches found

### Server
* https://github.com/nextcloud/server/pull/31106
* https://github.com/nextcloud/server/pull/31360
* https://github.com/nextcloud/server/pull/31363

### Notifications
* https://github.com/nextcloud/notifications/pull/1154
* https://github.com/nextcloud/notifications/pull/1157
* https://github.com/nextcloud/notifications/pull/1158

### Talk
* https://github.com/nextcloud/spreed/pull/6894
* https://github.com/nextcloud/spreed/pull/6929
* https://github.com/nextcloud/spreed/pull/6932
* https://github.com/nextcloud/spreed/pull/6935

**Comment by nickvergessen** [comment]
## Query count

Request | Baseline | Circles+Collectives
---|---|---|---
Total | 8137 | 8349 | 
Add group with 70 users | 457 | x |
Start call | 101 | x |
Join call | 27 | x |
End call for everyone | 162 | x | 

Impact of circles and collectives is basically gone (only done in the user check now) since the filesystem setup is not done anymore due to https://github.com/nextcloud/server/pull/31360

**Comment by nickvergessen** [comment]
## setupRootFS

* https://github.com/nextcloud/server/pull/31098
* https://github.com/nextcloud/server/pull/31401

Request | Baseline | Without patches
---|---|---
Total | 8137 | 8926
Add group with 70 users | 457 | 465
Start call | 101 | 110
Join call | 27 | 37
End call for everyone | 162 | 171

**Comment by nickvergessen** [comment]
# Chat patches
* https://github.com/nextcloud/spreed/pull/6958
* https://github.com/nextcloud/spreed/pull/6959

**Comment by nickvergessen** [comment]
Rebased, let's merge it so that follow up PRs can use it as a base.

**Review by danxuliu — APPROVED** [review]

**Pull request merged**
