### PR TITLE
Assign turn server protocols to template

### LINKED ISSUE #151: Undefined index errors in personal settings
Whenever I open my personal settings on current server master I get
```
{"reqId":"LWgCLDXx0OwNZVpbxteV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: server at \/nextcloud\/apps\/spreed\/templates\/settings-personal.php#16","level":0,"time":"2016-11-28T07:38:55+00:00","method":"GET","url":"\/settings\/personal","user":"user","version":"11.0.0.4"}
{"reqId":"LWgCLDXx0OwNZVpbxteV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: username at \/nextcloud\/apps\/spreed\/templates\/settings-personal.php#22","level":0,"time":"2016-11-28T07:38:55+00:00","method":"GET","url":"\/settings\/personal","user":"user","version":"11.0.0.4"}
{"reqId":"LWgCLDXx0OwNZVpbxteV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: password at \/nextcloud\/apps\/spreed\/templates\/settings-personal.php#28","level":0,"time":"2016-11-28T07:38:55+00:00","method":"GET","url":"\/settings\/personal","user":"user","version":"11.0.0.4"}
{"reqId":"LWgCLDXx0OwNZVpbxteV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: protocols at \/nextcloud\/apps\/spreed\/templates\/settings-personal.php#34","level":0,"time":"2016-11-28T07:38:55+00:00","method":"GET","url":"\/settings\/personal","user":"user","version":"11.0.0.4"}
{"reqId":"LWgCLDXx0OwNZVpbxteV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: protocols at \/nextcloud\/apps\/spreed\/templates\/settings-personal.php#37","level":0,"time":"2016-11-28T07:38:55+00:00","method":"GET","url":"\/settings\/personal","user":"user","version":"11.0.0.4"}
{"reqId":"LWgCLDXx0OwNZVpbxteV","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: protocols at \/nextcloud\/apps\/spreed\/templates\/settings-personal.php#40","level":0,"time":"2016-11-28T07:38:55+00:00","method":"GET","url":"\/settings\/personal","user":"user","version":"11.0.0.4"}
```

Spreed v1.0.21

### LINKED ISSUE #185: TURN settings should not show up for normal users
I see there's still a TURN setting for normal users... I guess that counts as a bug, right? No normal user would set up a TURN server, that's an admin's job and it does show up in the admin settings correctly.

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref #197 
```
Undefined index: turnServerProtocols at /var/www/nextcloud/apps/spreed/templates/settings-admin.php#35
Undefined index: turnServerProtocols at /var/www/nextcloud/apps/spreed/templates/settings-admin.php#38
Undefined index: turnServerProtocols at /var/www/nextcloud/apps/spreed/templates/settings-admin.php#41
```

Fix #151 
Fix #185 

@Ivansss @LukasReschke

### CODE REVIEW

**Comment by tx7** [comment]
Hi,

I couldn't find the link for the solution.

**Comment by jancborchardt** [comment]
@tx7 you could either manually apply the changes made – you can see them at https://github.com/nextcloud/spreed/pull/198/files
Or, if you got the app via git, just check out this branch by doing `git checkout issue-197-assign-turn-server-protocol-to-template`

**Comment by tx7** [comment]
Thanks.

**Comment by jancborchardt** [comment]
@tx7 can you test and confirm if it fixes the issue? :)

**Comment by jancborchardt** [comment]
@tx7 does that issue appear with Nextcloud 11 or with the Video calls app? If with Nextcloud, please open an issue at https://github.com/nextcloud/server/issues/ to help us fix it :)

**Comment by tx7** [comment]
“Too many redirects” is a NC issue. 
I probably have to re-install NextCloud tonight.

**Comment by tx7** [comment]
The above solution fixed it.

**Comment by nickvergessen** [comment]
@Ivansss can you review this?

**Comment by tx7** [comment]
Hi guys,

Just updated to NC11.0.1, and using the spreed video call from Github, but error persist.

`Undefined index: turnServerProtocols at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/apps/spreed/templates/settings-admin.php#41

Undefined index: turnServerProtocols at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/apps/spreed/templates/settings-admin.php#38

**Comment by nickvergessen** [comment]
We will publish a new version to the app store soon.
Since it doesn't happen here, I think you might have made some invalid changes ;)

**Comment by tx7** [comment]
This is inconsistent. 
I thought the package from Github should be the latest updates.

**Comment by nickvergessen** [comment]
Yes, but also your log is impossible, because line 38 is `<?php p($l->t('UDP and TCP')) ?>` and therefor can not cause `Undefined index: turnServerProtocols at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/apps/spreed/templates/settings-admin.php#38`

**Comment by tx7** [comment]
Do I need to change the STUN server's settings or left it by default?

**Comment by nickvergessen** [comment]
You only need to change stuff, when it's not working with the default values or you don't trust our service.

**Comment by tx7** [comment]
No offense, but I don't know if I should trust 3rd party service these days.
Too many hackers, and spy.....

**Comment by nickvergessen** [comment]
Yeah well that's all we can say.

STUN is not very critical, it's just used for IP resolution before connecting.
TURN (which has no default) pipes all the audio and video through it, so that is more critical to privacy and hacking.

**Comment by tx7** [comment]
In the meantime, you can post the solution here for us?

**Pull request merged**
