### PR TITLE
Transpile more deps for IE 11

### PR DESCRIPTION
**Pull request by PVince81**
In the listed order, every time I added a new exclude, a new one popped up. So I added them one by one.
Now in this PR we've reached a state where the Talk page loads in IE 11 but is missing some controls, likely due to the many JS errors happening in nextcloud-vue components (but no more syntax errors).

ie11-many-excludes

### CODE REVIEW

**Comment by PVince81** [comment]
the last error seems to say that `VPopover` expects a string instead of a number, and we do pass in a number. We pass it indirectly to `Popover` which then copies it over to `VPopover`. Not sure why the property requirements would be different/buggy with IE 11...

**Comment by PVince81** [comment]
in components/Popover.vue of the lib it **does** accept a number:
```
    delay: {
      type: [String, Number, Object],
      default: () => getDefault('defaultDelay'),
    },
```

**Comment by nickvergessen** [comment]
> Conflicting files
package-lock.json

**Comment by nickvergessen** [comment]
Allows chatting in IE11 again

**Comment by PVince81** [comment]
let me solve the conflict.

indeed the chat works for me, despite the million of errors in the console about data type validation in Vue properties...

**Review by nickvergessen — APPROVED** [review]
Fixes IE11 loading again

**Comment by nickvergessen** [comment]
Merge?

**Pull request merged**
