### PR TITLE
Add support for sending the password for a link share by Nextcloud Talk

### PR DESCRIPTION
**Pull request by danxuliu**
Requires #1267 
Required by nextcloud/server#11875

Regarding Talk the differences between protecting the password of an e-mail share or a link share are minimal; despite that, this pull request is required by the server changes. The reason is that link shares do not have a value in their `sharedWith` field (when got with the OCS enpoint they do, [although it is set by the `ShareAPIController`](https://github.com/nextcloud/server/blob/ea21aa3f7a12c5d1bd80eea329de3eb695fde4e5/apps/files_sharing/lib/Controller/ShareAPIController.php#L211), internally they have none), so without those changes when the room for the link share was created [the name of the room was set to `null`](https://github.com/nextcloud/spreed/blob/f81f5e0a7c17601a039f820b4d0fa59a561fe993/lib/Controller/PublicShareAuthController.php#L113). [When the call activity is generated the room name is expected to be a string](https://github.com/nextcloud/spreed/blob/bb9d9ab65eaf7f154568cd0cd2565489d48dc6ca/lib/Activity/Hooks.php#L94), but as the name was `null` PHP complained, no proper HTTP response was sent and the UI broke.

~~TODO:~~
- [x] The room name should be fixed. Currently it is set to the e-mail address or the target of the share (depending on the type of share), and [in the `RoomController` it is composed and returned as _Password request by {roomName}_](https://github.com/nextcloud/spreed/blob/e3d985da600404442973fcf1cb4cd04534cec023/lib/Controller/RoomController.php#L230).

  This was done [to show the room name in the language of the sharer](https://github.com/nextcloud/spreed/commit/55a983fd9f87cd61608e2283a798c6ccdffe5a0e), but now that the name needs to be different depending on the share type it would require to get the share object to check its type every time a room is formatted.

  It would be better to set the name once (and update it when needed, for example if the file name of a link share changes) than adding those extra queries, for example, every time that the list of rooms is got.

- [x] The notification sent for a link share should probably include the name of the file in its message; _Someone requested the password to access a share_ is too vague.

### CODE REVIEW

**Comment by danxuliu** [comment]
@nickvergessen Could you take over this to fix the pending issues? Thanks :-)

**Comment by nickvergessen** [comment]
I think it is good as is now

**Comment by danxuliu** [comment]
Mmm, when the file is added to the notification clicking on the notification to go to the call is no longer possible using the Notification app in the WebUI. This happens because [the file template generates a link to the file](https://github.com/nextcloud/notifications/blob/0fb58898baca4134af5d33b6314e2f25105733ec/src/templates/file.handlebars#L1), and [the link for the full subject is used only when the subject has no links](https://github.com/nextcloud/notifications/blob/341d74f6332b0008d5328345758ca309a1d24fcd/src/components/notification.vue#L72). In this case the link to the call is much more relevant than the link to the file, so... I am not sure what to do with that :-) Do as you wish ;-)

Regarding the room name I would prefer to keep the "namespaced" object types. I guess that they were changed to be able to use one text or the other in the `RoomController` without having to query the database for the share object every time that the room name is got. However, I would use `share:password:mail` and `share:password:link` instead of `share_mail` and `share_link`; once rooms in public share pages are introduced I expected to use something like `share:public` to differentiate them from `share:password` rooms.

However, I would rather keep the object type as `share:password` and add another field like `objectData` that in this case would include the type of the share, the name of the file and the e-mail address (when applicable) and compose the name based on those fields; this would make possible to provide more descriptive room names specifying both the e-mail and the file, just like in the notifications. Or, to keep things simple, just get the share from the database when the room name is formatted; after all those rooms exist only when there is a password request in progress, so it should not be too bad for the performance (I hope :-P ).

Another even simpler approach would be to use a generic text like _Password request: XXX_ where XXX is the e-mail or the file name, instead of _Password request by {email}_ and _Password request for {file}_; it would not have the more descriptive name with both the e-mail and file name, but after all there is not much space in the room list for long names, and this would make possible to keep the current `share:password` types while being fast and simple.

Besides all that, I have noticed that the file target of a share is not updated when the file name changes (I do not know if that is the expected behaviour or a bug in the server), so if the sharer renames the file after enabling the password request by Talk the room name will show the old file name (due to being based on the file target of the share); notifications are fine, as they get the file object everytime they are generated.

Also, the room name shown in the sidebar is the raw room name, that is, just the e-mail address or just the file name, without the formatting to add the _Password request_ part. This is caused by [using the `name` attribute instead of the `displayName`](https://github.com/nextcloud/spreed/blob/546526a89f7c7f417c7e73a4606662c6ae7ab520/js/views/callinfoview.js#L161); for `share:password` rooms the attribute to use should be `displayName` and the edition should be always disabled. I will fix that in a different pull request, as this happens too in Talk 4.0 with e-mail shares.

**Comment by danxuliu** [comment]
I have squashed the room name fix into the original commit to add support for link shares, and I have added another commit to remove an unused attribute from `PublicShareAuthController`.

@nickvergessen No notification is sent when using an undefined type for the rich object parameter (last commit); the problem seems to be that [when getting an undefined type an exception is thrown](https://github.com/nextcloud/server/blob/0913bc2157293acafa186afec4018ad25d7fbb22/lib/public/RichObjectStrings/Definitions.php#L429-L435), so [the validation of the parameter fails](https://github.com/nextcloud/server/blob/master/lib/private/RichObjectStrings/Validator.php#L90), and with this [the validation of the notification](https://github.com/nextcloud/server/blob/master/lib/private/Notification/Notification.php#L548-L552), and thus [the notification ends being ignored](https://github.com/nextcloud/server/blob/79b540ecc39202154d2374a96a1d255091b39f22/lib/private/Notification/Manager.php#L231-L233).

**Comment by danxuliu** [comment]
Tested and works :+1:

**Pull request merged**
