### PR TITLE
fix(techdebt) - add unified `TransitionWrapper` component for transitions

### LINKED ISSUE #9442: Remove css rules from sass variables module
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

The [sass variables module](https://github.com/nextcloud/spreed/blob/0adb88208d9bf3a65649eb37c8540c000059b3bb/src/assets/variables.scss) is supposed to be a built-time-only module with SASS variables. But it actually has css rules with classes for transitions (like fade, and slide).

As a result, each Vue component with imported SASS variables adds a new copy with scoped styles for transitions. Even if no `<transition>`/`<transition-group>` is used. Now we have 26 copies, including 18 useless copies of those styles in the bundle.

Proposal:
1. Add a new component for each `Transition`/`TransitionGroup` type aka `TransitionFade`, `TransitionSlide`.
2. Move transition styles to the new components
3. Use new components

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #9442
  * Amount of duplicated scoped styles was decreased (counting only talk-main.js - from 34 to 2 repeats + 5 from nextcloud-vue)

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image
image | image

### 🚧 Tasks

- [ ] Code review
- [ ] Visual check
- [ ] Known issues:
  - [ ] `<transition-group>` doesn't work properly for lists with added/removed items - not changed

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by ShGKme — CHANGES_REQUESTED** [review]
There are some issues around proxying props and events in the wrapper. It is not breaking anything now but makes a new `TransitionWrapper` not a transparent wrapper.

Everything else looks good, thanks for taking care of this!

**Comment by Antreesy** [comment]
Testing template for transitions:
```vue
<template>
<div style="display: flex">
	<button @click="shuffle">
		shuffle
	</button>
	<button @click="add">
		add
	</button>
	<button @click="remove">
		remove
	</button>
	<button @click="toggle = !toggle">
		toggle
	</button>
</div>

<TransitionWrapper tag="ul" name="toast" group>
	<li v-for="item in items" :key="item" class="item">
		<button>
			{{ 'button ' + item }}
		</button>
	</li>
</TransitionWrapper>
<span>------------------------------------------------</span>
<TransitionWrapper name="toast">
	<button v-if="toggle" class="item">
		{{ 'button toggle' }}
	</button>
</TransitionWrapper>
</template>

<script>
import { shuffle } from 'lodash'
const getInitialItems = () => [1, 2, 3, 4, 5]
let id = getInitialItems().length

	data() {
		return {
			items: getInitialItems(),
			toggle: false,
		}
	},
	
		methods: {
		randomIndex() {
			return Math.floor(Math.random() * this.items.length)
		},
		shuffle() {
			this.items = shuffle(this.items)
		},
		add() {
			this.items.splice(this.randomIndex(), 0, ++id)
		},
		remove() {
			this.items.splice(this.randomIndex(), 1)
		},
	},
</script>
```

**Review by ShGKme — APPROVED** [review]
Looks good to me. SCSS in the new wrapper component is large, but I don't see any other scoped solution without using CSS Modules (which I'm really a fun of, but we do not use in Nextcloud and don't have in Webpack config enabled).

**Review by DorraJaouad — CHANGES_REQUESTED** [review]
Tested in CallView and everything is fine there. 

The leftSidebar though
image

**Comment by Antreesy** [comment]
@DorraJaouad Align the components, please take a look

Screenshot from 2023-08-16 17-32-45

**Review by DorraJaouad — APPROVED** [review]

**Pull request merged**
