### PR TITLE
Update Talk action to Nextcloud blue

### PR DESCRIPTION
**Pull request by jancborchardt**
As discussed @juliushaertl 

Not tested just quickly changed. Nextcloud Talk should of course have the Nextcloud color (not themed), not a random "tomato" color. ;)

### CODE REVIEW

**Comment by blizzz** [comment]
if all actions have the same color, colors are not helpful anymore to identify the (configured) flows. we can drop this all along.

**Comment by jancborchardt** [comment]
> if all actions have the same color, colors are not helpful anymore to identify the (configured) flows. we can drop this all along.

They don’t have all the same color. The reason why I changed this around is because Talk was red and PDF was blue – that’s just switched.

**Comment by blizzz** [comment]
> DCO though!

we can ignore it in this less-than-one-liner

**Comment by jancborchardt** [comment]
> > if all actions have the same color, colors are not helpful anymore to identify the (configured) flows. we can drop this all along.
> 
> They don’t have all the same color. The reason why I changed this around is because Talk was red and PDF was blue – that’s just switched.

Btw @blizzz, could you make sure the Flow action for PDF uses the red color we also use for the PDF filetype icon? It’s `#dc5047` – thanks!

**Pull request merged**
