### PR TITLE
Make "End call for everyone" always available for moderators

### LINKED ISSUE #7518: Make "End meeting for all" always available for moderators
Currently it is limited to rooms where not everyone can start the call, but it would be quite handy when it is always available, especially (but not only) to kill guests and users which are AFK and don't quit the call.

- [ ] Always show the button for moderators
- [ ] Make the wording consistent #7905

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #7518 

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Bildschirmfoto vom 2023-02-17 10-03-30 | Bildschirmfoto vom 2023-02-17 10-26-52
Bildschirmfoto vom 2023-02-17 10-04-13 | Bildschirmfoto vom 2023-02-17 10-26-52

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]
Changes seem good.

Don't we want to apply a red color to this button? And maybe for "End call for everyone" Icon as well?

**Comment by nickvergessen** [comment]
> Don't we want to apply a red color to this button?

Be my guest, it's a regression from
https://github.com/nextcloud/spreed/blob/4e82455f49bbd7a772d3e9f37a1172d26fadbe39/src/components/TopBar/TopBar.vue#L407-L413

> And maybe for "End call for everyone" Icon as well?

Fine by me to fix that in a follow up?

**Comment by nickvergessen** [comment]
Raised as follow up in https://github.com/nextcloud/spreed/issues/8766

**Pull request merged**
