### PR TITLE
Add see-links to route files

### PR DESCRIPTION
**Pull request by nickvergessen**
Makes it a bit easier while debugging to jump from a known URL to the actual controller/code

### CODE REVIEW

**Review by vitormattos — COMMENTED** [review]
I tested locally, verified the settings and documentation about annotations of my IDE but don't worked to me. I think that is a problem on my IDE.

I checked the documentation of phpdoc about inline tag [@see](https://docs.phpdoc.org/guide/references/phpdoc/inline-tags/see.html) and looking it seems correct.

If work on your IDE, sounds a good idea.

And other routes files?

**Comment by nickvergessen** [comment]
> And other routes files?

Didn't want to create conflicts with other PRs, so step by step

**Comment by nickvergessen** [comment]
Bildschirmfoto von 2022-02-16 11-56-50

**Comment by vitormattos** [comment]
I think is a bug on extension of VSCodium, `@see` only work to me with class name, without method, when I put the method don't work more.

**Review by vitormattos — APPROVED** [review]

**Pull request merged**
