### PR TITLE
Less participant queries

### PR DESCRIPTION
**Pull request by nickvergessen**
Should reduce the number of those queries a lot:

```sql
SELECT * FROM `oc_talk_participants` WHERE (`user_id` = 'xxx') AND (`room_id` = '1234')
```

and will instead left join the participant on the initial query. That in itself is not a big help. But in case we ask for the same participant more than once (hint, happens every time), we save N-1 queries

it was 1122 queries of the 7873 in our query log

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Noice!

**Review by danxuliu — CHANGES_REQUESTED** [review]
Unit tests need to be adjusted.

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Pull request merged**
