### PR TITLE
feat(chat): Add changelog conversation entries for Talk 18

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

grafik

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]
Nothing regarding Dial-out?

**Comment by SystemKeeper** [comment]
> Nothing regarding Dial-out?

And recording consent ?

**Comment by nickvergessen** [comment]
Both features are primarily targetting bigger enterprises, so don't want to rub it in every user's face. We try to pick ~3 user facing features which are otherwise not too visible and or hard to discover (e.g. we don't talk about new vue version, etc either(.

**Comment by nickvergessen** [comment]
To be merged Thursday after RC1, so translators have time for translating

**Pull request merged**
