### PR TITLE
Сorrect hover styles for buttons in TopBar during a call

### LINKED ISSUE #8019: Call button hover contrast issues
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. ???
2. be in a call
3. hover buttons top right

### Expected behaviour

Contrast between button background color and icon

### Actual behaviour
Tell us what happens instead

|Default state|Hover state
|---|---|
| Bildschirmfoto vom 2022-09-26 13-38-34 | Bildschirmfoto vom 2022-09-26 13-38-36 |

## Talk app

**Talk app version:** Nextcloud 25 latest and greatest

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by Antreesy**
Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>

Fix #8019 

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Light / Dark themes difference | New appearance
image image | image image

to clarify changes:
```
	:deep(.action-item--open .action-item__menutoggle),
	:deep(.action-item__menutoggle:hover),
	:deep(.action-item--single:hover),
```
for NcActions elements (with open menu and on hover) - Screensharing, Conversation Settings, Chat

```
	:deep(.buttons-bar button:hover) {
```
for other buttons in LocalMediaControls - Microphone, Camera, etc

hover `background-color: rgba(0, 0, 0, 0.2)` was copied from left sidebar toggle button.
Changes are scoped inside `.top-bar.in-call` selector

### 🚧 TODO

- [ ] Code review (tested only in 1:1 calls, maybe some specific buttons were skipped)

### 🏁 Checklist

- [X] 📘 API documentation in `docs/` has been updated or is not required
- [X] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [X] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Thanks for addressing this!

**Comment by nickvergessen** [comment]
@Antreesy sounds good enough to be backported? Or does it not work on stable25 due to a different vue version?

**Comment by Antreesy** [comment]
@nickvergessen ,
In Vue 2 (before 2.7) we should use `::v-deep` with Sass,  `>>>` without Sass
In Vue 3 (and starting with 2.7) `::v-deep` and `>>>` are deprecated in favor of `:deep(.child-class)`

So with small changes (add ::v- prefix), we should be able to backport it.

**Comment by nickvergessen** [comment]
I meant the `@nextcloud/vue` lib. But yeah then let's backport it.

**Pull request merged**
