### PR TITLE
Fix backend url from CLI

### LINKED ISSUE #7436: occ talk:user:room - Failed to send message to signaling server
Just printed hundred times on our company cloud after being used by sysadmin:
```json
{
  "reqId": "lmHSSLZXGzcp9zhTbHQw",
  "level": 3,
  "time": "2022-05-31T10:18:05+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "spreed",
  "method": "",
  "url": "--",
  "message": "Failed to send message to signaling server",
  "userAgent": "--",
  "version": "24.0.1.1",
  "exception": {
    "Exception": "GuzzleHttp\\Exception\\ClientException",
    "Message": "Client error: `POST https://…/standalone-signaling/api/v1/room/…` resulted in a `403 Forbidden` response:\nAuthentication check failed\n\n",
    "Code": 403,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 69,
        "function": "create",
        "class": "GuzzleHttp\\Exception\\RequestException",
        "type": "::"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 204,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 153,
        "function": "callHandler",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "::"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php",
        "line": 48,
        "function": "GuzzleHttp\\Promise\\{closure}",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 248,
        "function": "run",
        "class": "GuzzleHttp\\Promise\\TaskQueue",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 224,
        "function": "invokeWaitFn",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 269,
        "function": "waitIfPending",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 226,
        "function": "invokeWaitList",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 62,
        "function": "waitIfPending",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 187,
        "function": "wait",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Http/Client/Client.php",
        "line": 289,
        "function": "request",
        "class": "GuzzleHttp\\Client",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 80,
        "function": "post",
        "class": "OC\\Http\\Client\\Client",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 134,
        "function": "doRequest",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 239,
        "function": "backendRequest",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Signaling/Listener.php",
        "line": 122,
        "function": "roomModified",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 251,
        "function": "OCA\\Talk\\Signaling\\{closure}",
        "class": "OCA\\Talk\\Signaling\\Listener",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 73,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 88,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Room.php",
        "line": 844,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Manager.php",
        "line": 392,
        "function": "setType",
        "class": "OCA\\Talk\\Room",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Command/User/Remove.php",
        "line": 72,
        "function": "removeUserFromAllRooms",
        "class": "OCA\\Talk\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/symfony/console/Command/Command.php",
        "line": 255,
        "function": "execute",
        "class": "OCA\\Talk\\Command\\User\\Remove",
        "type": "->"
      },
      {
        "file": "/var/www/html/core/Command/Base.php",
        "line": 168,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/symfony/console/Application.php",
        "line": 1009,
        "function": "run",
        "class": "OC\\Core\\Command\\Base",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/symfony/console/Application.php",
        "line": 273,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/symfony/console/Application.php",
        "line": 149,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Console/Application.php",
        "line": 211,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/console.php",
        "line": 99,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/occ",
        "line": 11,
        "args": [
          "/var/www/html/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php",
    "Line": 113,
    "CustomMessage": "Failed to send message to signaling server"
  }
}
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #7436

### CODE REVIEW

**Comment by nickvergessen** [comment]
Just for the record @fancycode 
if nextcloud is at `https://subdomain.domain.tld/path/to/nextcloud/` we return `https://subdomain.domain.tld/path/to/nextcloud/` and not `https://subdomain.domain.tld/`, correct?

**Comment by fancycode** [comment]
> Just for the record @fancycode if nextcloud is at `https://subdomain.domain.tld/path/to/nextcloud/` we return `https://subdomain.domain.tld/path/to/nextcloud/` and not `https://subdomain.domain.tld/`, correct?

Yeah, that should be the whole path, so the signaling server could differ between two instances running on the same host but with different subpaths.

**Pull request merged**
