### PR TITLE
Use internal client of signaling server for recording

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #8708
Requires #8725
Requires strukturag/nextcloud-spreed-signaling#421

[Internal clients are specific to the signaling server](https://github.com/strukturag/nextcloud-spreed-signaling/blob/69dfb0686fdcef5e77f0559aa9e9dd8ac734fcaa/docs/standalone-signaling-api-v1.md#client-type-internal) and do not have a counterpart Nextcloud user/session. Due to its special nature an internal client is able to join any call, so using an internal client makes possible to record calls other than public ones, which was a limitation of using a guest participant.

Besides that, this also fixes stopping a recording when the last participant leaves, as the recording participant was a regular participant and thus prevented the call from ending when the rest left.

Finally, the recording participant is no longer shown in the call for the rest of participants (although this might require a little change in the mobile apps to not show internal participants; this change should be done independently of the recording, though, to avoid showing other internal participants like the SIP bridge).

### How to test (without starting a recording)

- Start a call
- In a private window, open `{url of the call}/recording`
- In the browser console, execute (replacing the token of the conversation, secrets and server URL as needed):
```
signalingSettings = await OCA.Talk.signalingGetSettingsForRecording(
    'THE-TOKEN-OF-THE-CONVERSATION',
    '1234567890123456789012345678901234567890123',
    Array.from(new Uint8Array(await crypto.subtle.sign(
        'HMAC',
         await crypto.subtle.importKey(
            'raw',
            (new TextEncoder().encode('THE-SECRET-OF-THE-RECORDING-SERVER')).buffer,
            {
                name: 'HMAC',
                hash: { name: 'SHA-256', },
            },
            true,
            ['sign']
        ),
        new TextEncoder().encode('1234567890123456789012345678901234567890123')
    ))).map(b => b.toString(16).padStart(2, '0')).join('')
)

OCA.Talk.signalingJoinCallForRecording(
    'THE-TOKEN-OF-THE-CONVERSATION',
    signalingSettings,
    {
        random: '1234567890123456789012345678901234567890123',
        token: Array.from(new Uint8Array(await crypto.subtle.sign(
            'HMAC',
            await crypto.subtle.importKey(
                'raw',
                (new TextEncoder().encode('THE-INTERNAL-SECRET-OF-THE-SIGNALING-SERVER')).buffer,
                {
                    name: 'HMAC',
                    hash: { name: 'SHA-256', },
                },
                true,
                ['sign']
            ),
            new TextEncoder().encode('1234567890123456789012345678901234567890123')
        ))).map(b => b.toString(16).padStart(2, '0')).join(''),
        backend: 'THE-URL-OF-THE-NEXTCLOUD-SERVER',
    }
)

```

Note that there will be no sound, as the call is joined without any user interaction and therefore sounds are blocked. This is correctly handled when accessing the endpoint from the recording server.

### 🚧 TODO
- [X] Cleanup experimental code
- [X] Verify that [the signaling settings will not need to be updated](https://github.com/nextcloud/spreed/blob/e32afb6e5ebc8ec2097d980b4d82b40b02db4dd2/src/utils/webrtc/index.js#L104-L108) when authenticating as the internal client - It should not be needed, as the token only expires with version 2.0 of client type authentication, but not with internal type authentication (see `TokenExpired` in https://github.com/strukturag/nextcloud-spreed-signaling/blob/cbb6d9ca53b8c7ca416afeee3ae0074c7e39a24c/hub.go#L1016)
- [x] Make possible to get the signaling settings for a conversation without a user/session but with the recording secret (like in other endpoints used by the recording server), as getting the signaling settings without a specific token is a legacy behaviour.
- [x] Fix participants background. - As [explained below](https://github.com/nextcloud/spreed/pull/8756#issuecomment-1432692335) it will be probably fixed once the audio flag is removed for the internal client, although it might require some adjustments in the mobile clients.
- [x] Adjust to changes in https://github.com/strukturag/nextcloud-spreed-signaling/pull/421 to remove the audio flag for the internal client.

### CODE REVIEW

**Comment by SystemKeeper** [comment]
> * Fix participants background. It seems that all participants are treated as guests, probably because whether the participant is a user or a guest is decided based on the store data rather than the signaling data ([although that should not be the case, the signaling data should take priority](https://github.com/nextcloud/spreed/blob/master/src/components/CallView/shared/VideoVue.vue#L317-L320) 🤔)

The background color is only determined based on the displayname, not the userId: https://github.com/nextcloud/spreed/blob/d33205924ad29b7f55c43c32d484101d56a698bc/src/components/CallView/shared/VideoBackground.vue#L52-L56
Maybe displayname is missing?

**Comment by danxuliu** [comment]
> Maybe displayname is missing?

Mmm, right. If the problem is what I think it is (initial state not sent because the participant tries to establish a connection with the internal client, which never succeeds) it should automatically go away once the internal client is fixed to not have an audio flag (as if the participant is not sending any media [the initial state is sent as soon as the participant is found](https://github.com/nextcloud/spreed/blob/4c8d16a3f48c6f7b77c94771c6aee6970578fa0b/src/utils/webrtc/webrtc.js#L333-L344), rather than when the connection is established).

That might require some adjustments in the mobile apps, though, but let's see first if that is actually the problem ;-)

**Review by nickvergessen — APPROVED** [review]
Seems to work when testing it locally

**Comment by danxuliu** [comment]
> > although this might require a little change in the mobile apps to not show internal participants
> 
> On iOS the internal participant is indeed visible as a guest. What would be the best approach to identify an internal participant and hide it?

Oops, sorry, missed the question, but as far as I can see you figured out :-) Yes, it is done checking the [`internal` property of the participant in the signaling message](https://github.com/nextcloud/spreed/blob/e66bd05eb7f68008a4241d7679f491b4b6c5da46/src/utils/webrtc/webrtc.js#L322).

**Pull request merged**
