### PR TITLE
Improve Leave Call modal

### LINKED ISSUE #3144: "Leave call" modal improvements
The current "Leaving call" modal could be better:
Leave call modal needs better title and buttons
- [ ] Title in present form: "Leave call"
- [ ] The content text should be explanatory and include the room name: "Navigating away from the page will leave the call in Design team public."

---

- [ ] ~~The icon is not needed, it just makes the text strangely aligned.~~  nextcloud/server#20192
- [ ] ~~"No" button should be "Stay in call".~~ nextcloud/server#20192
- [ ] ~~"Yes" button should be "Leave call" and not primary colored but red, as it is destructive.~~  nextcloud/server#20192

@ma12-co if you point out where this needs to be changed, it would be a good first issue.

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #3144 

Closes #3181 

@Dids-Himanshu If you want, we could quickly get your PR merged first then merge this?

Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

**Comment by gary-kim** [comment]
> Fixed the translation (our bot does not detect the placeholder otherwise)

Whoops, forgot about that.

**Comment by Dids-Himanshu** [comment]
Unfortunately got late..my bad

**Comment by jancborchardt** [comment]
@Dids-Himanshu no worries! :) Still lots of good first issues available: https://github.com/nextcloud/mail/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Pull request merged**
