### PR TITLE
Fix wording and icons for screensharing options

### PR DESCRIPTION
**Pull request by Ivansss**
**Before**:

screen shot 2018-12-03 at 12 21 19

**After**:

screen shot 2018-12-03 at 12 19 38

When the user is sharing a screen or window:

screen shot 2018-12-03 at 12 22 41

### CODE REVIEW

**Comment by jancborchardt** [comment]
I would change the "Share your screen" to "Share whole screen" so it’s more clear that it’s everything.

Also, that should stay the same in the last screenshot, where currently it still uses the word "Show". Ok?

**Comment by Ivansss** [comment]
Text for the last screenshot is a bit more tricky.
It should mean something like "See what you are currently sharing"
Do you have any ideas for that text? @jancborchardt  :)

**Comment by jancborchardt** [comment]
What happens if you click it? Does it switch between the whole screen or one window? If so:
- When you currently "Share whole screen", it should show "Share single window"
- When you currently "Share single window", it should show "Share whole screen"

**Comment by jancborchardt** [comment]
Aaaaah right! And for me it would show "Show Jan’s screen", right?
Then I think the wording there is fine.

Just also change the "Share your screen" to "Share whole screen" so it’s more clear that it’s everything. – As mentioned above. :)

**Comment by jancborchardt** [comment]
@danxuliu make sure to open issues about those :)

**Pull request merged**
