### PR TITLE
Upstream our comments manager extensions to server

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/server/pull/23601

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by PVince81** [comment]
ok, so https://github.com/nextcloud/server/pull/23601 was merged yesterday and now on spreed master I get this, which I suppose is related:
```
TypeError: Argument 4 passed to OC\Comments\Manager::__construct() must implement interface OCP\AppFramework\Utility\ITimeFactory, instance of OC\InitialStateService given, called in /srv/www/htdocs/server/apps/spreed/lib/Chat/CommentsManager.php on line 48 and defined in /srv/www/htdocs/server/lib/private/Comments/Manager.php:77
```

switching to this PR solves the issue

let's get CI passing, I've restarted it

**Comment by PVince81** [comment]
hmmm
```
ERROR: UndefinedMethod - lib/Chat/AutoComplete/Sorter.php:60:44 - Method OCA\Talk\Chat\CommentsManager::getLastCommentDateByActor does not exist (see https://psalm.dev/022)
			$lastComments = $this->commentsManager->getLastCommentDateByActor
```

reproducible with a local run of psalm

but it's there:
https://github.com/nextcloud/server/pull/23601/files#diff-862a3988c96ee1f18bc17076a3152274d876dec178266a6b2d237b9ae7f03cd0R692

it seems the new interface has not been updated yet in composer's christophwurst/nextcloud/OCP/Comments/ICommentsManager

**Comment by PVince81** [comment]
okay, saw you just pushed the update. let's see :)

**Comment by nickvergessen** [comment]
https://github.com/ChristophWurst/nextcloud_composer/commit/b2289bc625ef59b11e2342aebe3afd8328431e9b

Bumped the library, should do it, but psalm still failed locally, maybe there is some caching some where involved?

**Comment by PVince81** [comment]
yeah, weird, the update is there:
```
% grep -re getLastCommentDateByActor vendor 
vendor/christophwurst/nextcloud/OCP/Comments/ICommentsManager.php:      public function getLastCommentDateByActor(
```

I've cleared the local caches with `psalm --clear-cache` and `psalm --clear-global-cache` but the psalm error still appears:
```
ERROR: UndefinedMethod - lib/Chat/AutoComplete/Sorter.php:60:44 - Method OCA\Talk\Chat\CommentsManager::getLastCommentDateByActor does not exist (see https://psalm.dev/022)
                        $lastComments = $this->commentsManager->getLastCommentDateByActor(

```

maybe it's another subtelty

**Comment by PVince81** [comment]
after adding ICommentsManager to the var it gets worse:
```
diff --git a/lib/Chat/AutoComplete/Sorter.php b/lib/Chat/AutoComplete/Sorter.php
index e9994e19c..102fbf4ff 100644
--- a/lib/Chat/AutoComplete/Sorter.php
+++ b/lib/Chat/AutoComplete/Sorter.php
@@ -23,12 +23,13 @@ declare(strict_types=1);
 
 namespace OCA\Talk\Chat\AutoComplete;
 
+use OCP\Comments\ICommentsManager;
 use OCA\Talk\Chat\CommentsManager;
 use OCP\Collaboration\AutoComplete\ISorter;
 
 class Sorter implements ISorter {
 
-       /** @var CommentsManager */
+       /** @var CommentsManager|ICommentsManager */
        protected $commentsManager;
 
        public function __construct(CommentsManager $commentsManager) {
```

I think since Psalm doesn't know the base class as it's ignored / not included, it cannot know about that method, so we must add the `ICommentsManager` bit.

Still, it gets worse:
```
ERROR: MissingDependency - lib/Chat/AutoComplete/Sorter.php:32:11 - OCA\Talk\Chat\CommentsManager depends on class or interface oc\comments\manager that does not exist (see https://psalm.dev/157)
        /** @var CommentsManager|ICommentsManager */
```

shouldn't Psalm ignore anything in the `OC` namespace ?

There is no other class that seems to be using `CommentsManager` directly. The few occurrences are only getting it injected without using any methods.

**Comment by PVince81** [comment]
ok, it seems we can simply use ICommentsManager for the Sorter class, I'll push that

**Comment by nickvergessen** [comment]
This is quite fragile now, we should really only use the talk wrapper. Otherwise someone copies and magically introduces a 1k char limit for chat messages.

**Comment by nickvergessen** [comment]
But let's get it in and open a PR that reverts this one commit and figure it out there.

**Pull request merged**
