### PR TITLE
Fix topbar buttons design and mobile layout

### LINKED ISSUE #6468: Fix localmediacontrols on mobile
Text | Screenshot
---|---
Okay for now due to timeline, but must fix before final: Buttons are overflowing on phone screen size |  Bildschirmfoto am 2021-11-10 um 14 50 10

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/6460#issuecomment-965192201_

### PR DESCRIPTION
**Pull request by marcoambrosini**
fixes #6468 

https://user-images.githubusercontent.com/26852655/141328061-74ed4200-5c2b-4dff-ac99-f87be5e9e964.mov

### CODE REVIEW

**Comment by nickvergessen** [comment]
Bildschirmfoto von 2021-11-12 13-43-13

Breaking point should be a tad earlier?

**Comment by nickvergessen** [comment]
Rebased due to end-meeting but and to not trigger update issues with 23/24

**Comment by marcoambrosini** [comment]
> Breaking point should be a tad earlier?

Done!

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
