### PR TITLE
7219: updated reaction bubble should overlay

### LINKED ISSUE #7219: Reactions bubble should overlay the unread messages horrizontal line
## Steps to reproduce
1. Open a conversation with unread messages
2. Hover over the message just above the unread messages indicator line
3. Watch the reactions bubble. It's *under* the unread messages indicator line

### Screenshot

talk-unread-reactions

### Expected behaviour
I guess it would look cleaner if the reactions bubble would overlay the unread messages indicator line.

## Talk app

cloud.nc.c instance

## Browser

**Operating system:** Linux

**Browser name:** Firefox

**Browser version:** 99

### PR DESCRIPTION
**Pull request by nikola-gladovic**
Signed-off-by: Nikola <nikola.gladovic@nextcloud.com>

Fixed #7219

### CODE REVIEW

**Review by marcoambrosini — COMMENTED** [review]
Could you please post before and after screenshots @nikola-gladovic

**Review by marcoambrosini — COMMENTED** [review]
Looking at the screenshot in the issue, this seems to be more related to the positioning of the buttons bar. It seems to be too low with respect to the message

**Comment by nickvergessen** [comment]
Other solution could be more offset on the read marker?

**Comment by nikola-gladovic** [comment]
Before
image

After:
image

**Review by marcoambrosini — CHANGES_REQUESTED** [review]
@nikola-gladovic the problem here is that the two elements intersect in the first place, so it's not so much a z-index issue. 
The `MessageBottomBar` element is positioned very low compared to other messages, and as Joas says, probably we need a little bit of margin on the read marker too

**Comment by marcoambrosini** [comment]
closing in favour of #7452

**Pull request closed without merging**
