### PR TITLE
Show chat view as main view when in a room but not in a call

### PR DESCRIPTION
**Pull request by danxuliu**
No changes were made to the layout of the chat view in this layout. Therefore, the messages are shown from newest to oldest and the new message input is shown at the top, even when shown as the main view, which is an uncommon layout. A follow up pull request will reverse the layout of the chat view to use a more common one.

In the same way, the local video is now hidden behind the chat view. When the chat view is shown as the main view the local video should appear in a sidebar tab; this will be done in another pull request too.

### CODE REVIEW

**Comment by nickvergessen** [comment]
can we refocus the input, after submitting text with enter?

**Comment by danxuliu** [comment]
There was a problem with the scroll bar in the main view; `height: 100%` was missing from the chat view, so the height of the list of messages was not limited and the scroll bar never appeared. [Fixed now](https://github.com/nextcloud/spreed/pull/544/commits/3cff47a2385cb9ded373679e64728e288e102a8d#diff-6a6a912d0c7b55b537768da778032849R152).

**Comment by danxuliu** [comment]
@nickvergessen 
>  can we refocus the input, after submitting text with enter?

Strange, that seems to be automatically done in Firefox, but not in Chromium. I will check what is going on.

**Comment by nickvergessen** [comment]
> Strange, that seems to be automatically done in Firefox, but not in Chromium. I will check what is going on.

right, odd

**Comment by danxuliu** [comment]
The focus issue was unrelated to the changes in this pull request, so it was fixed in a different one: #545

**Pull request merged**
