### PR TITLE
Only show quick conversation settings menu only when hovering or focu…

### PR DESCRIPTION
**Pull request by marcoambrosini**
…sing a conversation

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] verify that this is accessibility friendly (haven't tested yet)
   - need to be able to display that extra info also with keyboard
   - check if mobile devices also get access to that extra info

In my opinion we should keep the three dots instead of hover, like the avatar menu which we planned to contain more context information. Having it as a button makes it work for everybody.

**Comment by PVince81** [comment]
maybe put the three dots on the conversation icon as if it was the conversation's avatar ?

**Comment by ma12-co** [comment]
There's an ongoing discussion in the nc-vue repo for this, I'm just using this as a parking lot for now :)

**Comment by marcoambrosini** [comment]
Done in nextcloud vue lib

**Pull request closed without merging**
