### PR TITLE
Inject the preloaded user status into the avatar component

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Requires https://github.com/nextcloud/nextcloud-vue/pull/1733

### Steps
1. Create a conversation with 5 people
2. Reload the page with open network tab:
3. Before:
Bildschirmfoto von 2021-03-02 09-45-30
4. After:
Bildschirmfoto von 2021-03-02 09-45-14

### CODE REVIEW

**Review by ma12-co — APPROVED** [review]
Works!

**Comment by PVince81** [comment]
@nickvergessen rebase to be on the same level as the lib or simply merge ?

**Comment by nickvergessen** [comment]
Rebased

**Review by PVince81 — APPROVED** [review]
Tested, works :+1:

No more status requests, not even for users that never logged in!

**Pull request merged**
