### PR TITLE
fix(SharedItems): fetch after page reload + fix(Conversation): set warnings on max length

### LINKED ISSUE #11433: Sidebar spinning indefinitely when reloading 'Note to self'
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open "Note to self"
2. Make sure the right sidebar is open
3. Reload the page

### Expected behaviour
The right sidebar is open and shared items should be visible in the right sidebar.

### Actual behaviour
The right sidebar is open, but no shared items visible (only a loading spinner)

https://github.com/nextcloud/spreed/assets/1580193/1eb401d3-57e4-420a-bf42-558ffed8e2d2

## Talk app

**Talk app version:** Tested on main, but also happens on 28.0.2 rc2

### LINKED ISSUE #11659: long description is not saved when creating conversation
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a new conversation, add title and a looong description (~1000 words), add participants, click "create"
3. conversation is created but the description is not saved, error message (German) "Fehler bei der Aktualisierung der Beschreibung"

### Expected behaviour
There should be a warning that the description is too long, like when you edit a description of an existing conversation, it should show how many characters you have left or how many you are over the limit. The next step button at the bottom "add participants" should not be clickable until the description fits the limit.

### Actual behaviour
Long description (=a lot of time writing) not saved, frustrated users. 

## versions

**Talk app version: 17.1.5

**Nextcloud Version:** 27.1.6

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #11433 
* Fix #11659
* Fix big image fallback when creating new conversation with federated

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image
image | image
image | image

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible

### CODE REVIEW

**Review by DorraJaouad — APPROVED** [review]
I think it would be better if you show max length somewhere ( either in a counter or in error message) so if a user pastes a text, they can know how many characters they should reduce.

**Comment by Antreesy** [comment]
> I think it would be better if you show max length somewhere ( either in a counter or in error message) so if a user pastes a text, they can know how many characters they should reduce.

What about `t('spreed', 'Maximum length is exceeded by ({length}) characters')`, where {length} is a diff?

**Comment by DorraJaouad** [comment]
> What about `t('spreed', 'Maximum length is exceeded by ({length}) characters')`, where {length} is a diff?

Let's not depend on that, diff can be get to extreme cases easily (100000000000000000)

**Comment by alexanderdd** [comment]
Thank you!

Is it possible to backport this to earlier Nextcloud versions like 28, 27?

**Pull request merged**
