### PR TITLE
Prevent unwanted clickables for file names and others

### PR DESCRIPTION
**Pull request by nickvergessen**
In Talk we only parse URLs with a protocol to avoid undesired clickables like composer.json
Therefor the method and regex were copied from OCP.Comments and adjusted accordingly.

* `composer.json` => not clickable :heavy_check_mark: 
* `https://nextcloud.com/` => clickable as `nextcloud.com/` :heavy_check_mark: 
* `http://nextcloud.com/` => clickable as `http://nextcloud.com/`:heavy_check_mark: 
* `(see http://nextcloud.com/)` => clickable as `http://nextcloud.com/` :heavy_check_mark: 
* `https://en.wikipedia.org/wiki/Android_(OS)` => clickable as `https://en.wikipedia.org/wiki/Android_(OS)` :heavy_check_mark: 

cc @blizzz up to you, if we copy the behaviour back to the comments API.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ready to review

**Comment by danxuliu** [comment]
I have added an initial commit that embeds the unmodified `OCP.Comments.plainToRich` in ChatView for easier tracking of changes, and converted the ` ↗` hint to CSS instead of hardcoding it in the link.

**Comment by nickvergessen** [comment]
> Tested and apparently works, although the lack of unit tests for regular expressions make me shiver.

Same here, but I dont feel comfortable to start workign on JS unit tests before the rewrite

> `(http://www.nextcloud.com)` does not work, though, but it was not listed in the pull request message.

That's already the case before, it happens, because () and some other chars are only valid after the first / in a URL, since they can't be part of the domain/tld

**Pull request merged**
