### PR TITLE
Spelling: by a user that has since been deleted :)

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by nickvergessen** [comment]
Can you please sign your commits? See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work for more information.

You can do this manually for now:
```
git commit --amend -s
git push --force origin <your branch>
```

Also tests are failing, care to adjust?

**Comment by danxuliu** [comment]
The _A (now) deleted user_ strings were based on [the ones in the Comments app](https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/apps/comments/lib/Notification/Notifier.php#L108-L112), so it would be great if you could change those too for consistency :-)

Thanks!

**Comment by jancborchardt** [comment]
Shorter and simpler wording would be:

> You were mentioned in a group chat by a deleted user

@comradekingu can you adjust, in the Comments app too as @danxuliu mentioned?

**Comment by nickvergessen** [comment]
We could also just get rid of the `(now)`, same words as now just in a different order...

**Comment by nickvergessen** [comment]
But too late for such changes now, since it breaks all translations

**Comment by nickvergessen** [comment]
Fixed tests

**Pull request merged**
