### PR TITLE
Notify standalone signaling server about sessions to remove from room.

### PR DESCRIPTION
**Pull request by fancycode**
Btw, that is the expected behaviour when a user is removed? For now I can simply reconnect and will be in the room again.

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Btw, that is the expected behaviour when a user is removed? For now I can simply reconnect and will be in the room again.

For a public room? Yes. For a private one? No.

Something like "ban" is missing, yes, but it's also not easy because banning by IP is useless so it would only work for normal users too

**Comment by fancycode** [comment]
> For a public room? Yes. For a private one? No.

Ok, this is the behaviour I'm seeing. Only tested public calls before. In a private room, the user is disconnected and loads the Talk app afterwards. I guess I got a bit confused as there is no feedback to the participant that he got kicked.

So this is ready to review (basically triggers the event to the signaling server, so that can close the connection to the client).

**Comment by nickvergessen** [comment]
> I guess I got a bit confused as there is no feedback to the participant that he got kicked.

https://github.com/nextcloud/spreed/issues/857

**Comment by fancycode** [comment]
But isn't #857 about a deleted room and the UI that gets stuck, or do I miss something?

Both doesn't happen here: a user is kicked, and the browser reloads for him, showing the Talk app where he can switch to a different room / create one. But no information that he got kicked.

**Pull request merged**
