### PR TITLE
allow brave

### PR DESCRIPTION
**Pull request by szaimen**
### ☑️ Resolves 

* Fix https://github.com/nextcloud/spreed/issues/8966

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not required
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]

**Comment by solracsf** [comment]
@szaimen v24 is affected too.

**Comment by szaimen** [comment]
https://github.com/nextcloud/spreed/pull/9172

**Pull request merged**
