### PR TITLE
Cache hasAvatar to avoid call background flickering

### PR DESCRIPTION
**Pull request by PVince81**
Whenever the speaker changes, the avatar background can flicker due to
HTTP calls. This fix improves it a bit by caching the information
whether the user has an avatar or not, so allows a less delayed loading of
the avatar background.

This only affects the avatar background.
For the avatar itself, you also need https://github.com/nextcloud/nextcloud-vue/pull/1457 in place.
Best is to test both together.

### CODE REVIEW

**Review by ma12-co — COMMENTED** [review]
I get this artifact both when switching videos manually and when doing it by activating/deactivating the mics of other users with fake streams on, thereby changing the current promoted person: 

Peek 2020-10-15 20-14

**Comment by PVince81** [comment]
@ma12-co this PR is only about the background and that one looks stable/fine in your video.

For the avatar's "white circle" please also check out https://github.com/nextcloud/nextcloud-vue/pull/1457.

Make sure to repeat the operations multiple times: the first time you'll still see artifacts and after the cache is populated, switching should not show any glitch (except for "stop following" which I observed locally)

**Comment by PVince81** [comment]
Adjusted to use browser storage. However I'm not using the `BrowserStorage` service as it's in the "talk" namespace.
Need to use the "nextcloud" namespace as this is also where the Avatar vue stores the same state: https://github.com/nextcloud/nextcloud-vue/pull/1457

**Review by ma12-co — APPROVED** [review]

**Comment by PVince81** [comment]
backport to stable20 here https://github.com/nextcloud/spreed/pull/4514

**Pull request merged**
