### PR TITLE
Fix volume indicator shown when audio is not available

### PR DESCRIPTION
**Pull request by danxuliu**
Bug from #2021

## How to test
- Start a call
- Do not grant access to the microphone

### Results with this pull request ###
The volume indicator is not shown

### Results without this pull request ###
The volume indicator is shown

### CODE REVIEW

**Comment by nickvergessen** [comment]
For me the indicator is already hidden?

**Comment by Ivansss** [comment]
Should we also hide the volume indicator when user is muted?

**Comment by nickvergessen** [comment]
> Should we also hide the volume indicator when user is muted?

I can see it being useful in both ways. Either you can check the sensitivity of your mic, or you dont get the feeling it's sending something although you are muted.

**Comment by nickvergessen** [comment]
> For me the indicator is already hidden?

Doh, I was already on your PR.... yeah makes sense...

**Comment by danxuliu** [comment]
> Should we also hide the volume indicator when user is muted?

I would keep it visible, but with a different colour. I am on it ;-)

**Comment by danxuliu** [comment]
CI failures are unrelated (the strange unclean _package-lock.json_ issue and a known failure in the acceptance tests) -> merge.

**Pull request merged**
