### PR TITLE
 fix(conversations): Remove call-permissions

### LINKED ISSUE #13012: Remove call permissions
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

When developing permissions we added default and call permissions. Call permissions were meant to be a temporary default that resets when the call ends.
Since this never made it to any client and is also complex to handle UI-wise, we should simply drop the backend parts of it

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Based on #13072
* Fix #13012 

The permission only existed on API level and it's too complicated
to figure out a good UX for it. So the functionality to change it
are removed here. It's still kept in the database and response to
avoid breakage of existing clients

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by danxuliu — COMMENTED** [review]
[`forcePermissions` parameter in `joinCall`](https://github.com/nextcloud/spreed/blob/4d73f9bdb6a4fbcada24571fa84eb4ef021287f0/lib/Controller/CallController.php#L119) should be deprecated, as [it is used to set the now deprecated call permissions](https://github.com/nextcloud/spreed/blob/4d73f9bdb6a4fbcada24571fa84eb4ef021287f0/lib/Controller/CallController.php#L169-L171).

Same for [the whole `setAllAttendeesPermissions` endpoint](https://github.com/nextcloud/spreed/blob/77efdf6b189736a85930f6e47793bde9c8f636d7/lib/Controller/RoomController.php#L2174-L2175) (which it is in the docs, although it would be good to mark it too in the code documentation so it is picked by OpenAPI).

**Comment by nickvergessen** [comment]
> [forcePermissions parameter in joinCall](https://github.com/nextcloud/spreed/blob/4d73f9bdb6a4fbcada24571fa84eb4ef021287f0/lib/Controller/CallController.php#L119)

It never made it to the normal docs :D So I will remove it, but not deprecate it (as additional send parameters don't break anyway)

**Review by danxuliu — APPROVED** [review]
Code looks good :+1:

**Pull request merged**
