### PR TITLE
Use the token instead of the id to identify the room objects

### LINKED ISSUE #1001: Send token instead of room id in notifications
And of course expose this fact via capabilities xD

### PR DESCRIPTION
**Pull request by nickvergessen**
Changes the object id from room id to the token, so you can query the room to get the full information for it

Fix #1001

### CODE REVIEW

**Comment by mario** [comment]
Please add capability as this is a breaking change.

**Comment by nickvergessen** [comment]
A capability doesn't help really, because when you receive a notification, and then the server is updated, it's still with id, although it the capability would say its the token.
Just try to get the room with the value, if it works continue, if not do as before.

**Comment by mario** [comment]
The only question is if $chat should be named $conversation instead. Otherwise looks decent.

**Comment by mario** [comment]
Ooops, sorry for closing.

**Pull request merged**
