### PR TITLE
Set permissions on Matterbridge config and log

### LINKED ISSUE #5727: All bridges with all passwords are exposed in /tmp directory with no proper permission
I looked at the processes and found a matterbridge process running, with the /tmp/bridge-9c6xtgyo.toml parameter. I thought OK, as non-root user surley this is somehow properly protected so no other users are able to see the passwords. And nope, everything exposed in plaintext with 644 permission....

NextCloud should write the config to it's own data/nextcloud directory AND use a proper file permission.

I thought about trying this i.e. on uberspace. There are like 30 users with ssh access on the server. Everybody can easily get login data in plaintext in /tmp, nice.

```
[nonrootuser@server tmp]$ lsl /tmp/*toml
644 -rw-r--r-- 1 www-data www-data 619 Jun  9 00:43 /tmp/bridge-9c6xtgyo.toml
[nonrootuser@server tmp]$ cat /tmp/*toml
[matrix.0]
	Server = "https://matrix.localhost"
	Login = "cooluser"
	Password = "verysecret"
	PrefixMessagesWithNick = true
	NoHomeServerSuffix = true
	RemoteNickFormat = "[{PROTOCOL}] <{NICK}> "

[nctalk.1]
	Server = "https://server.localhost/nextcloud"
	Login = "bridge-bot"
	Password = "YPkMtxA+()n+wOxxasxasasasx"
	PrefixMessagesWithNick = true
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
	name = "myGateway"
	enable = true

[[gateway.inout]]
	account = "matrix.0"
	channel = "somechannel"

[[gateway.inout]]
	account = "nctalk.1"
	channel = "9c6xtgyo"

[nonrootuser@server tmp]$
```

versions
```
apps/talk_matterbridge/appinfo/info.xml
	<version>1.22.3</version>

apps/spreed/appinfo/info.xml
	<version>10.0.8</version>

occ --version
Nextcloud 20.0.10
```

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #5727

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Feels like snake oil since either only NC is run by www-data as the system is properly isolated or a lot more services and then it will not help.
But fine by me

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/pull/4782 

We can close this other PR then?

**Review by eneiluj — APPROVED** [review]
Yes we can close #4782

**Comment by gsantner** [comment]
May I suggest to use `nextcloud/data/bridge-bot/` instead of `/tmp`? This folder seems to be created by the bridge anyway

```
root@server:/var/www/server.local/nextcloud/data# ls
admin  appdata_octkr6c71351  bridge-bot  files_external  index.html  nextcloud.log  owncloud.db
root@server:/var/www/server.local/nextcloud/data# ls bridge-bot/
cache
root@server:/var/www/server.local/nextcloud/data# tree bridge-bot/
bridge-bot/
└── cache

1 directory, 0 files
root@server:/var/www/server.local/nextcloud/data#
```

**Comment by nickvergessen** [comment]
Doesn't work when external storage is mounted on the root, as the file needs to be local on the server.
Anyway there is already another issue where this is discussed

**Comment by gsantner** [comment]
Ah, makes sense

**Pull request merged**
