### PR TITLE
Correctly forward the password to the controller method

### LINKED ISSUE #1768: Password protected public conversation errors on password submission
## Steps to reproduce
1. make new conversation
2. set a password
3. open link incognito
4. enter password
5. HTTP 405 returned

### Expected behaviour
guest user should be able to view and participate in the chat

### Actual behaviour
server returns HTTP 405 (method not allowed). I'm assuming the router isn't allowing POST requests to submit the password?

Screenshot 2019-05-03 17 28 05

## Browser
tried FF and Chrome

**Microphone available:** NA

**Camera available:** NA

**Operating system:** Windows & OSX

**Browser name:** Firefox & Chrome

**Browser version:** FF 67.

### Browser log

not a client side issue

## Spreed app

**Spreed app version:** 6.0.0

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:**

**Nextcloud Version:** 16.0.0

**List of activated apps:** 

https://hastebin.com/qavuyiyuzo.css

**Nextcloud configuration:** 

https://hastebin.com/dutafequya.json

### Server log (data/nextcloud.log)

relevant lines: no crashes or anything
https://hastebin.com/ehopetuyuz.nginx

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1768 

- [ ] Requires https://github.com/nextcloud/server/pull/15394

### CODE REVIEW

**Comment by danxuliu** [comment]
@nickvergessen I have noticed that when a wrong password is used [the error message](https://github.com/nextcloud/spreed/blob/86ec1dd446f8907e08c6c1d1380685b7b901a7fd/templates/authenticate.php#L12) is not shown. Do you want to fix it here? Or should I open an issue for it?

**Comment by nickvergessen** [comment]
Merging this one as it doesnt break anything

**Comment by nickvergessen** [comment]
> I have noticed that when a wrong password is used the error message is not shown. Do you want to fix it here? Or should I open an issue for it?

new thing.

**Comment by danxuliu** [comment]
>  >  I have noticed that when a wrong password is used the error message is not shown. Do you want to fix it here? Or should I open an issue for it?
>
> new thing.

OK, issue here: #1778

**Pull request merged**
