### PR TITLE
😄 Frequently used emojis

### PR DESCRIPTION
**Pull request by marcoambrosini**
Collab with @skjnldsv 😀

Screenshot 2022-10-03 at 12 36 02

### CODE REVIEW

**Comment by nickvergessen** [comment]
I guess you want to summon the backport bot?

**Review by nickvergessen — APPROVED** [review]
List still does not refresh without a page reload, but fine by me for now.

**Comment by skjnldsv** [comment]
> List still does not refresh without a page reload, but fine by me for now.

It does for me :+1:

**Comment by szaimen** [comment]
This is so great, thanks a lot for this 🎉🎉🎉

**Pull request merged**
