### PR TITLE
Hide chat tab for folders

### PR DESCRIPTION
**Pull request by ma12-co**
Based on https://github.com/nextcloud/server/pull/18449

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Will merging this into master of talk break anything (problem) or will it just always show the tab (wouldnt mind)?

**Comment by danxuliu** [comment]
> Will merging this into master of talk break anything (problem) or will it just always show the tab (wouldnt mind)?

It will probably break, as [the constructor parameters changed](https://github.com/nextcloud/server/pull/18449/files#diff-b375c9e422692b79bf11c9f41bbe21beR38) (but I have not tested).

**Comment by ma12-co** [comment]
> It will probably break, as the constructor parameters changed (but I have not tested).

I have tested with that branch checked out in the server @danxuliu

**Comment by danxuliu** [comment]
> I have tested with that branch checked out in the server

Yes, what I mean is that it will break without that branch ;-)

**Comment by ma12-co** [comment]
But isn't that in already?

**Comment by nickvergessen** [comment]
but it was merged after beta3, so if we want to have somethign working, we have to wait until beta3 compatible package has been built

**Pull request merged**
