### PR TITLE
Process call recordings and call transcriptions notifications independently

### PR DESCRIPTION
**Pull request by Ivansss**
### ☑️ Resolves

* Fix https://github.com/nextcloud/server/issues/40253

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by Antreesy — COMMENTED** [review]
Call chains seem to be fine (for recording/transcription), but I'm afraid that we could miss some other notification usecases

**Comment by SystemKeeper** [comment]
I would assume that the timestamp for a recording and the transcript differs? The notification should then only be processed if the datetime matches:

https://github.com/nextcloud/notifications/blob/9e4bfdcf04d3a17402f4b22166e1afd4fc7ff833/lib/Handler.php#L322-L325

I tested this on a 27.0.2 installation, and it is working correctly for me. These are the notifications generated:

```
> SELECT app,timestamp,object_type,subject,subject_parameters,message,message_parameters actions FROM oc_notifications WHERE user = 'marcel.mueller';
+--------+------------+-------------+------------------------+---------------------+---------+---------+
| app    | timestamp  | object_type | subject                | subject_parameters  | message | actions |
+--------+------------+-------------+------------------------+---------------------+---------+---------+
| spreed | 1693940282 | recording   | record_file_stored     | {"objectId":850850} |         | []      |
| spreed | 1693940435 | recording   | transcript_file_stored | {"objectId":850851} |         | []      |
+--------+------------+-------------+------------------------+---------------------+---------+---------+
```

and after I shared the recording, the transcript-notification is still visible:

image

And the code was already there in 17 🤔

**Comment by SystemKeeper** [comment]
Updated the instance to the latest 27.1 RC.

```
> SELECT app,timestamp,object_type,subject,subject_parameters,message,message_parameters actions FROM oc_notifications WHERE user = 'marcel.mueller';
+--------+------------+-------------+------------------------+---------------------+---------+---------+
| app    | timestamp  | object_type | subject                | subject_parameters  | message | actions |
+--------+------------+-------------+------------------------+---------------------+---------+---------+
| spreed | 1693941375 | recording   | record_file_stored     | {"objectId":850861} |         | []      |
| spreed | 1693941632 | recording   | transcript_file_stored | {"objectId":850862} |         | []      |
+--------+------------+-------------+------------------------+---------------------+---------+---------+
```

so the timestamps are different.

I am able to reproduce the issue if I have a second tab open. In this case I get the following log in the console:

> Deferring notification refresh from browser storage are notify_push event to give the last tab the chance to do it

When I then open the notification popup and click on the share button, both notifications vanish. After the next notification refresh, the remaining one is back again. So for me, this looks like a frontend issue, not a backend one.

**Comment by danxuliu** [comment]
> So for me, this looks like a frontend issue, not a backend one.

[It seems so](https://github.com/nextcloud/notifications/pull/1657) :-)

**Pull request closed without merging**
