### PR TITLE
Support standalone signaling server for chat

### PR DESCRIPTION
**Pull request by fancycode**
Implements #624. Based on #887 which should be merged first.

### CODE REVIEW

**Comment by fancycode** [comment]
This is a first improvement in that the polling gets removed, the messages are still loaded from PHP.

In a future step, this could be changed further so that the messages are sent through the WebSocket and no more PHP calls are necessary (besides loading the initial list of past messages).

**Comment by nickvergessen** [comment]
You guys forgot the backport label :(

**Comment by fancycode** [comment]
This will also need a backport of #887 then.

**Comment by fancycode** [comment]
Btw, what are the guidelines for backporting issues? From what I understand from the past, only bug fixes should be backported but no new features.

**Comment by nickvergessen** [comment]
In this app we backport everything which is not server-version dependent.
So that all features are always available in the latest supported server version (atm 13).

The diff between master + stable13 (or in the future stable14) should only be code that is necessary for server master, e.g. a lot of CSS changes are necessary and personal settings module was changed.

**Comment by fancycode** [comment]
Ok, thanks for clarification. I'll add the `backport-request` label accordingly in the future.

**Pull request merged**
