### PR TITLE
Only check path for being accessible when the storage is a object home

### PR DESCRIPTION
**Pull request by mejo-**
Forward-ported https://github.com/nextcloud/server/pull/24103

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by mejo-** [comment]
We stumbled upon this in Deck, where sharing files from groupfolders on object storage was broken for a customer.

**Comment by mejo-** [comment]
Related Deck PR: https://github.com/nextcloud/deck/pull/6062

**Review by juliushaertl — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
