### PR TITLE
Share from Files wording fix (better consistency)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Just check the commit. The instance's name is useless. Elsewhere, in that kind of context, "... from Files" is used instead.

Test from reviewers are welcome.

### ☑️ Resolves

* Fix #…

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Screenshot before | Screenshot after

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [ ] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

---

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not possible
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by Antreesy** [comment]
cc @nickvergessen as was changed in original discussion: https://github.com/nextcloud/spreed/pull/7491#discussion_r909310699

Can see in source code of Groupware/Office apps, that there is a translation 'from Files'

**Comment by Antreesy** [comment]
It makes sense for me, but I want a confirmation, what was the reason to made it in the first place

**Comment by nickvergessen** [comment]
Since we use the code in the desktop client, "Files" is ambiguous and might cause confusion, so I think we have to stay with the product name.

**Review by Antreesy — APPROVED** [review]
Tested in browser:
image
Desktop:
image

**Pull request merged**
