### PR TITLE
Replace custom component with new RichContenteditable

### PR DESCRIPTION
**Pull request by danxuliu**
Requires https://github.com/nextcloud/nextcloud-vue/pull/1433

The RichContenteditable component provides its own template for candidate mentions, so the Mention component is no longer used in the input field. However, it is still used when rendering messages, so it can not be removed. It would be good to avoid having duplicate logic (for example, to select the icon for a guest mention).

Pending:
- [x] Proper handling of new lines
- [x] Fill user data for MentionBubble (so once you select a mention the user name is shown in the text instead of the id)
- [ ] Use the same icon for guests as what will be shown in the chat (instead of always using the user icon)
- [x] Send messages when pressing Enter (take into account #4259 too)
- [x] Pasting files
- [ ] Shortcut to focus chat
- [x] Dark mode
- [ ] Check if the exported mixin from RichContenteditable can be used to solve the duplicated logic mentioned above
- [x] handle `isCompositing` event attribute to prevent sending message when using input methods: https://github.com/nextcloud/spreed/pull/5939 (ideal is to streamline this in the vue lib directly)

### CODE REVIEW

**Comment by PVince81** [comment]
for new lines, see https://github.com/nextcloud/spreed/pull/4259/commits/1adf641f87a4ba9cb333728aeac2ea93e67c2fc0
might save some time

**Comment by nickvergessen** [comment]
That commit should go into the lib directly, so behaviour is consistent across all points of nextcloud

**Comment by marcoambrosini** [comment]
not quite ready for review 😅

**Comment by ShGKme** [comment]
### Replacement completion

- [x] Fix styling:
  - [x] Fix paddings
  - [x] Fix max-height
  - [x] Add hover/active/focus styles
  - [x] Remove unnecessary deep overriding
  - [x] Use variable instead of constant when applicable
- [x] Migration:
  - [x] Fix placeholder: `placeholder-text` → `placeholder`
  - [x] Fix disabling: `active-input` → `disabled`
  - [x] Remove `parsedText` (now there is no difference with `text`)
- [x] Fix focus after joining a chat (with `nextTick`)
- [x] Add missed shortcuts:
  - [x] `ESC` - blur input
  - [x] `c` - focus input (once)
- [x] Remove the old `AdvancedInput`
- [x] Uninstall `vue-at`
- [x] l10n (no changes)
- [x] Linting

### Checklist

- [x] No visual differences with the old `AdvancedInput`
  - [x] +Dark theme
- [x] States:
  - [x] Active/focus/hover
  - [x] Disabled
- [x] Sending messages
- [x] Multiline
  - [x] +Max lines
- [x] Pasting files
- [x] Focus when a chat is loaded
- [x] Emoji picker
- [x] Mentions
- [x] l10n
- [x] Shortcuts:
  - [x] `ESC` - blur
  - [x] `c` - focus only once
  - [x] `Enter` on mentions/emojies doesn't send a message (worked in `NcRichContenteditable`)

**Comment by ShGKme** [comment]
Emoji Picker has a problem: it is supposed to replace the selection in the input, but the selection is lost after the emoji picker opens. So an emoji is always added to the end. Also, it checks `<br>` in the text while `\n` is used now. It adds a new black line if the emoji is picked on an empty line.

But all those problems are not caused by this PR.

https://github.com/nextcloud/spreed/blob/8144b9f0b4234dab7c3dba364a8bba8ab5b55087/src/components/NewMessageForm/NewMessageForm.vue#L700-L736

**Review by marcoambrosini — APPROVED** [review]
- [ ] The focus should return on the input after adding an emoji via emoji picker

Other than that I'd say that even with the caveats @ShGKme mentions, this is an awesome improvement and we should finally get it in.

**Comment by ShGKme** [comment]
> * The focus should return on the input after adding an emoji via emoji picker

It doesn't work on both `master` and `stable25`, requiring total `addEmoji` rewriting. I'd make it in a separate PR.

**Comment by ShGKme** [comment]
Ref: https://github.com/nextcloud/spreed/issues/4265

**Comment by nickvergessen** [comment]
> It doesn't work on both master and stable25,

In that case it does not block getting this in.

**Comment by nickvergessen** [comment]
So, who hits the green button?

**Comment by nickvergessen** [comment]
We are not backporting this one

**Comment by ShGKme** [comment]
> We are not backporting this one

I guess the backport bot was triggered by an old message after the merge...

**Pull request merged**
