### PR TITLE
Add backend url to connection error

### PR DESCRIPTION
**Pull request by SystemKeeper**
### ☑️ Resolves

For easier debugging I suggest we include the used backend url in the error message:
Bildschirmfoto 2023-12-10 um 20 28 13

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]
Looks correct by the code, can't see any case it may break something in signaling

**Review by fancycode — COMMENTED** [review]
:+1: Makes sense.

**Pull request merged**
