### PR TITLE
style: design adjustments for Nc30

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix some topic from daily design review
* Tested with `nextcloud-vue@main`, so need to release for some upstream changes 
* [x] Search box 
  - [x] text moves on hover `upstream`
  - [x] buttons are too far
* [ ] List items in conversation list
  - [ ] Spacing on the left too much `upstream` ?
  - [x] Avatar circle is slightly cut off `upstream`
  - [x] Avatar circle should have transparant bg + same bg on hover
* [ ] Create new conversation dialog
  - [ ] Use JS autosize for description so it auto resizes `upstream`
  - [x] lock horizontal resizing
* [x] NewMessage input
  - [x] emoji doesn't have hover feedback
* [x] MessageButtonsBar
  - [x] lift a bit for sticky position
  - [ ] if date and buttons are on the same level, buttons dissapear (hover event at date should be disabled)

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
image | image
image | image
before | after

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [x] 🖌️ Design was reviewed, approved or inspired by the design team

### CODE REVIEW

**Comment by ShGKme** [comment]
Making list items huge again seams like design reverting

**Comment by Antreesy** [comment]
> Making list items huge again seams like design reverting

Do we maybe have overwriting somewhere?

**Comment by Antreesy** [comment]
Merging to get for the daily review

**Pull request merged**
