### PR TITLE
Admin settings

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Move to own section
- [x] Allow multiple STUN servers
- [x] Allow multiple TURN servers
- [x] Migrate existing configs to the new one
- [x] Requires https://github.com/nextcloud/server/pull/6759/files

### CODE REVIEW

**Comment by nickvergessen** [comment]
@Ivansss ready to review

**Comment by nickvergessen** [comment]
Added the green checkmark instead, it's less intrusive

**Comment by blizzz** [comment]
When you add a second STUN server, the green checkmark always appears next to all input boxes, not only the one that was changed. Same for TURN. Unless the input is invalid.

**Comment by nickvergessen** [comment]
I did this intentionally, so you know changes to all fields are saved

**Comment by Ivansss** [comment]
Looks a bit confusing in the TURN case when your are adding a second server.
You set the TURN server URL and when you jump to set the Shared Secret, it checks the whole form and you see the green tick in the first TURN server.

**Pull request merged**
