### PR TITLE
Add support for Talk sidebar in Files app

### PR DESCRIPTION
**Pull request by danxuliu**
:construction: :construction: :construction: :warning: :warning: :warning:  **WIP: DO NOT MERGE** :warning: :warning: :warning: :construction: :construction: :construction:

Requires nextcloud/server#11647

This pull request adds initial support for the Talk sidebar in the Files app.

It is currently a work in progress; the code is not ready for review yet, although feedback about the feature itself is welcome.

In the Files app, when the user shows the details view for a file shared with other users, now a _Chat_ tab is shown (call support will be added in another pull request). This chat is accessible by all the users that have access to that file (through a user, group, circle or room share), and although it is shown in the main Files app it is mainly targeted to communicate while collaboratively editing the file (like with Collabora Online, which [now uses the sidebar of the Files app](https://github.com/nextcloud/richdocuments/pull/223)).

talk-sidebar-files-chat

Note that there is a single room for each file, no matter which or how many shares it has; there are no separate rooms based on the shares, like two different rooms for two different user shares, another room for a group share, etc. In the same way that all the users can collaboratively edit the file the room is also accessible by all of them.

However, for the time being, only registered users have access to the room for a file, and only if they have direct access to the file (through a user, group, circle or room share); the Talk sidebar is not shown in the public share page, and neither guests nor users can join the room even if they know its token and they can access the file due to a link share. This restriction could be addressed in a later pull request but, for simplicity, this initial version enforces it.

The rooms associated to files are persistent public rooms, but without any persistent participant; all the users join and leave in each session, so the rooms are not added to the room list. They only appear there when the user is currently in the room, that is, when she has the _Chat_ tab is open for the file in the Files app.

In a similar way notifications are sent to the user only when she is currently in the room. This is the expected behaviour in my opinion (except for mentions, which should be notified even if not currently in the room); if some people is working on a file in general it would not make sense to notify everyone with access to that file for example that a conversation started if they are not already working on it.

Pending:
- [ ] Rooms for files are never removed yet. A new `BackgroundJob` should be added for that; it would check whether the file associated to a room exists or not and, if it does not exist, remove the room.
  - Another approach would be to listen to file deletion events, but that would introduce a lot of unneeded overhead, as once the file is deleted the room would be no longer accessible anyway (so it does not really matter if it lives a bit longer), and this would make file deletion slower due to the extra database queries.

Enhancements for future pull requests:
- Add support for calls
- The autocomplete should show all the users that can access the room instead of only those that are currently active in the room (although those currently active in the room should have higher priority).
  - Mentions should be notified (if the user has access to the file) even when not currently in the room.
- Do not create the room if it is not needed. Right now the room is created just by opening the _Chat_ tab; it would be better to create it only if any user actually wrote anything in the room. The PHP changes are trivial, although the JavaScript ones are more involved.

### CODE REVIEW

**Comment by danxuliu** [comment]
@nextcloud/designers Some UX/UI questions:
- The _Chat_ tab subverts the design of the details view in the Files app. When the sidebar content is too tall a scroll bar is shown for the whole sidebar. In the case of the chat, however, this would be a bad approach: the chat is shown from oldest to newest, so the sidebar would always be scrolled to the bottom, and a lot of scrolling would be needed to go back to the file info and the other tabs. Moreover, when the loading of old messages by scrolling up is implemented (soon ;-) ) it would be a bit cumbersome to use too, as it could load messages when the user just wants to go to the file info. Due to this, the _Chat_ tab has its own inner scrollbars, so the file info and the form to send a new message are always shown and only the list of messages itself is scrolled (although the regular scrolling behaviour is restored when changing to any other tab). If you have any better idea please share it :-)
  - The only way I found to be able to show inner scrollbars in the _Chat_ tab was by applying a special CSS class to the tab container so it used `overflow: hidden`. Again, if you know a cleaner way code is welcome ;-) Otherwise, nextcloud/server#11647 will be required for the Talk sidebar.

- There is no _Participants_ tab, so it is not possible to know who is currently in the room. Technically it would be possible and easy to add it, but I thought that adding another tab just for that was too much, and it also felt a little _disconnected_ from the chat due to the other set of unrelated tabs. So, how to communicate the user who else is in the room? Is it even needed? Note that Collabora Online already provides information about the users currently editing the file, and other collaborative editing apps would probably provide that information too.

- Should the _Chat_ tab be always shown in the Files app? Or would it be better to show it only when Collabora Online (or any other app that explicitly enabled the Talk sidebar) is shown?
  - Showing an hiding the tab when an editor is opened and closed would probably require changes in the code of the details view in the Files app

- Currently the Talk sidebar is enabled for any file shared with another user. Should it be configurable? Like making possible to disable the feature per-system or maybe per-user? A reason to make possible for individual users to disable the feature would be to avoid the overhead introduced by the feature when editing if they use a low-end system or a bad connection (although I have not tested if the overhead could be really problematic or not, it is just speculation).

**Comment by jancborchardt** [comment]
> There is no Participants tab, so it is not possible to know who is currently in the room. Technically it would be possible and easy to add it, but I thought that adding another tab just for that was too much, and it also felt a little disconnected from the chat due to the other set of unrelated tabs. So, how to communicate the user who else is in the room? Is it even needed? Note that Collabora Online already provides information about the users currently editing the file, and other collaborative editing apps would probably provide that information too.

An addition about this one we also discussed in the sidebar standardization meeting: We should try to integrate the "Participants" here with the "Sharing" tab. Even if the first version just simply adds them to the bottom in a separate section.

**Comment by nickvergessen** [comment]
No, we need to release something with this on thursday. It will be changed again with 16 most likely because of linked-collaboration-resources anyway.

For now we will live without a participants view

**Comment by jancborchardt** [comment]
Right right, we talked about that. Thanks for the reminder @nickvergessen! :+1:

**Pull request closed without merging**
