### PR TITLE
Show default non-user avatar for guests when disabling video

### PR DESCRIPTION
**Pull request by Ivansss**
Before
screen shot 2016-12-15 at 19 15 28
After
screen shot 2016-12-15 at 19 16 01

### CODE REVIEW

**Comment by jancborchardt** [comment]
Should be the question mark instead of X though, right? Do you use latest server master?

**Comment by jancborchardt** [comment]
cc @rullzer

**Comment by Ivansss** [comment]
> Should be the question mark instead of X though, right? Do you use latest server master?

Yes, the server of that screenshots has not the latest master.
It will display a question mark :)

**Comment by jancborchardt** [comment]
:+1: awesome :)

**Pull request merged**
