### PR TITLE
Do not reuse media constraints between independent media requests

### PR DESCRIPTION
**Pull request by danxuliu**
When getting the user media for the first time both audio and video are requested. If video is not available then the user media is got again requesting only audio. However, as the media constraints were reused in any following user media request as soon as video failed once it was never requested again. Therefore if a camera was plugged in later it was ignored until Talk was restarted.

Now getting the user media always tries first with both audio and video and then fallbacks to trying only with audio, even if video was not available in a previous request.

Besides that, now an error message is shown to the user if the video could not be got (except if the reason is that there is no camera).

## How to test (scenario 1)
- Start a call without a camera
- Leave the call
- Plug in the camera (and wait a little so the browser finds it)
- Start a call again

### Result with this pull request
The camera is available in the call.

### Result without this pull request
The camera is not available in the call.

## How to test (scenario 2)
- Start a call with a camera that can not be used

### Result with this pull request
The camera is not available in the call, but an error is shown to the user.

### Result without this pull request
The camera is not available in the call and no error is shown to the user.

### CODE REVIEW

**Comment by nickvergessen** [comment]
I never so far saw the fixup bot failing... there is a first time for everything :D

**Comment by danxuliu** [comment]
Backport to stable18 will probably work once https://github.com/nextcloud/spreed/pull/3899 is merged.

**Pull request merged**
