### PR TITLE
Reconnection

### PR DESCRIPTION
**Pull request by Ivansss**
- [x] Add UI for ice connection states.
- [x] Use ICE-restart for re-connection attempts.

### CODE REVIEW

**Comment by nickvergessen** [comment]
@Ivansss can you add screenshots?

**Comment by Ivansss** [comment]
Connecting
screen shot 2017-05-15 at 11 20 31 2
Peer connection failed
screen shot 2017-05-15 at 11 22 06
Connected (video disabled)
screen shot 2017-05-15 at 11 25 50

**Comment by jancborchardt** [comment]
Nice! :) On »Connection failed« can we also display that text directly over the avatar instead of only the icon?

Also, ideally use the white error icon since it’s more visible: `icon-error-white` (https://github.com/nextcloud/server/blob/master/core/img/actions/error-white.svg )

**Comment by nickvergessen** [comment]
My problem with the error thing is, that it might be hidden on colorful/messy avatars.
Not sure what's the best to do about it. Maybe adding the  error icon to the name makes it more clear?

**Comment by Ivansss** [comment]
The avatar will be half-transparent when peer connection failed.So  I think when changing it to white it will be visible enough.

**Pull request merged**
