### PR TITLE
Sidebar polishing

### LINKED ISSUE #399: Sidebar improvements
## Todos
- [x] Currently the complete list is refreshed for the moderator when they change another participant => #439 
- [x] When a user is promoted/demoted by another moderator, the sidebar should rerender. => #439 
- [x] Renaming should be in the sidebar #440 
- [x] Share link should be in the sidebar #440 
- [x] Adding participants should be in the participants tab view #440 
- [x] Guests are displayed wrongly in the sidebar => #410

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Clipboard with call link
- [x] Move share option
- [x] Move rename
- [x] Move password input
- [x] Move add participant

Fix #399

### CODE REVIEW

**Comment by nickvergessen** [comment]
@danxuliu I have a little issue here.
1. As moderator 1 open the rename option and start changing the name.
2. In a second window as a second moderator I change the name.
3. For moderator 1 the sidebar re-renders and the name changing is aborted.

Can we somehow block re-rendering while the user is performing certain actions?

**Comment by danxuliu** [comment]
>  Can we somehow block re-rendering while the user is performing certain actions?

Marionette does not seem to have a way to cancel or prevent the rendering of a view, so the model events would have to be disconnected while those actions are being performed and connected again once they are finished.

Thus, I would suggest a different approach: restoring those parts of the UI that were being modified once they have been rendered again (saving the state in `onBeforeRender` and restoring it in `onRender`). See the attached file for a diff that fixes the scenario you mentioned above:

[restoreInputOnRender.diff.txt](https://github.com/nextcloud/spreed/files/1392947/restoreInputOnRender.diff.txt)

**Comment by nickvergessen** [comment]
Ah, now I understood the modelEvents.

I changed it, so it only re-renders when the password field is empty and the name field is not visible.

**Comment by nickvergessen** [comment]
@jancborchardt can you fix the CSS of the "Add participant" input in the right sidebar please?

**Pull request merged**
