### PR TITLE
Add push to talk and push to mute

### LINKED ISSUE #603: Implement Push-To-Talk and Push-To-Mute
Ref: https://github.com/nextcloud/talk-android/issues/65

Basically, on Android if you have mic disabled, holding it pulsates the icon and allows sound thus performing push to talk. Lifting your thumb again disables the sound obviously.

### Push to talk

GIVEN my mic is muted
WHEN I press spacebar
AND keep spacebar pressed
THEN my mic is active

GIVEN my mic is active
AND my spacebar is pressed
WHEN I release the spacebar
THEN my mic goes back to muted

### Push to mute

GIVEN my mic is active
WHEN I press spacebar
AND keep spacebar pressed
THEN my mic is muted

GIVEN my mic is muted
AND my spacebar is pressed
WHEN I release the spacebar
THEN my mic goes back to active

### PR DESCRIPTION
**Pull request by ma12-co**
How to test: start a call with an active mic and press spacebar.

fix #603 

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Comment by nickvergessen** [comment]
Please document? Keyboard shortcuts in settings and maybe even the tooltip of the audio button?

**Comment by ma12-co** [comment]
For the settings I was waiting for them to be in

**Comment by nickvergessen** [comment]
When you push-to-talk and a moderator mutes you before you "release the key", you will be unmuted afterwards and have "push to mute". :/

**Pull request merged**
