### PR TITLE
[stable28] chore(deps): bump @nextcloud/vue from 8.11.3 to ^8.14.0

### PR DESCRIPTION
**Pull request by ShGKme**

### CODE REVIEW

**Comment by Antreesy** [comment]
Rebased, bumped, didn't test

**Comment by nickvergessen** [comment]
Isn't 8.14 the version with the style changes that should only go into main?

**Comment by Antreesy** [comment]
> Isn't 8.14 the version with the style changes that should only go into main?

Style changes comes with 8.13 already, but it's not affecting stable branches, since it relies on server variables.
And server already updated: https://github.com/nextcloud/server/commit/8cbdcfeff66ec5d8562380d6c7ec5022b35e0889

**Review by Antreesy — APPROVED** [review]
Tested

**Pull request merged**
