### PR TITLE
Actually trigger users{Left,Joined} event

### PR DESCRIPTION
**Pull request by leonklingele-work**
We need these events for [presentation resume support](https://github.com/nextcloud/spreed/pull/387/commits/19783330906ac4f6ea15ba651a16fe7369449a40#diff-f9a8399f04091748fa56c9d2b7ff747bR362)

### CODE REVIEW

**Comment by fancycode** [comment]
Just saw this because I got a rebase conflict in another branch. Methods prefixed with `_` should be considered internal and not be called from outside the class where the methods are defined.

If you need application-side events about newly connected users, a better event would be `createdPeer` on the webrtc object (see https://github.com/nextcloud/spreed/blob/master/js/webrtc.js#L68). At the time the `userJoined` event is triggered, a `peer` for the user is not required to be present yet, which might then cause issues in the presentation code.

Please revert this change and @leonklingele-work please listen on the `createdPeer` in the presentations code - you will get the new peer as parameter and don't need to look it up again.

**Comment by leonklingele-work** [comment]
Why do we then listen for the `usersJoined` event [here](https://github.com/nextcloud/spreed/blob/1e888e3df14df8eb856b03c25b0fb1058378d2b8/js/webrtc.js#L111) even if its `users` parameter might not be fully populated?

**Comment by leonklingele-work** [comment]
Oh, I see. nvm

**Comment by fancycode** [comment]
`users` is populated in this event, but the `peer` objects will not be created for users yet.

**Pull request merged**
