### PR TITLE
Add button to expand tabs in the sidebar

### PR DESCRIPTION
**Pull request by danxuliu**
Due to the scroll bar being shown only for the tabs the call details are always visible. In short screens this may not leave too much space for the tabs, making them uncomfortable to use.

To improve that now a button is added automatically to every tab added to the sidebar; clicking on the button toggles the associated tab between its normal size and an expanded size that fills the whole sidebar.

I have tried other approaches, like hiding the call details when scrolling in one direction and showing it back when scrolling on the opposite direction, but in the end the button one was the simplest, most reliable and less bug/quirk prone.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hum, this is adding a confusing mode which needs another action/icon on top.

Rather than that, it seems like here we should:
- [ ] Clean up the stuff on top to have less content above the tabs:
   - [ ] Move »Join call« and »Share link« into same row
   - [ ] Make sure the password only shows up in a popover bubble and not in a separate row 
- [ ] Reduce the margin below the new comment input:
```
#commentsTabView .newCommentRow {
    margin-bottom: 0;
}
```
- [ ] Not quite sure that limiting the scroll bar in the first place was a good idea? https://github.com/nextcloud/spreed/pull/550

**Comment by jancborchardt** [comment]
Aaaand see: More design work & clean up to reduce possible height of room details #562 :)

**Comment by nickvergessen** [comment]
> bildschirmfoto von 2018-01-10 13-02-41

**Comment by danxuliu** [comment]
@nickvergessen I know that it is going to sound surprising... but that is by design. If the icon is in a lower position it would seem to be part of the _Add participant_ field. If it is in a higher position it could overlap with the tab header. The idea was to _float_ it there so it is seen as a separate element... but if you think that it is a bug it seems that the idea failed miserably :-P

**Comment by danxuliu** [comment]
Closing. See https://github.com/nextcloud/spreed/issues/493#issuecomment-357139674

**Pull request closed without merging**
