### PR TITLE
Ignore webdav udpates for 4.x

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Wait, no, why?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/5088#issuecomment-780551486

**Comment by skjnldsv** [comment]
No, it's fixed in latests 4.0.x :)
I chatted with the dev :)

**Comment by skjnldsv** [comment]
https://github.com/perry-mitchell/webdav-client/issues/238

**Comment by nickvergessen** [comment]
Ah okay

**Pull request closed without merging**
