### PR TITLE
WIP: Private reply

### PR DESCRIPTION
**Pull request by jakobroehrl**
grafik
solves: https://github.com/nextcloud/spreed/issues/2800
This is only a 1st try, I don't know how hard it is do finish it. 
### Questions/Todo
- [x] change the chat
- [x] post quoted msg
- [ ] send new msg
- [ ] use another icon?

### CODE REVIEW

**Comment by nickvergessen** [comment]
> What should happen, if the user clicks on the "Reply private" Button? Change the chat and show the quote there? If yes, how can I change the chat?

The thing is we prohibit this. You can not quote messages from chat A in chat B, to avoid leaking of messages when people are removed from chats etc. So my suggestion (same as for forward) would be to just copy the original text message with a `> ` in front to the input, after changing to the one-to-one conversation:

```
> What should happen, if the user clicks on the "Reply private" Button? Change the chat and show the quote there? If yes, how can I change the chat?
```

But switching is not that easy, because you might not have the one-to-one chat before, so you first need to create it or rejoin it in case you left it. But all this can be done with a call to
https://github.com/nextcloud/spreed/blob/bd78555cc31e653171ec68a1f87eafe2304d7bba/src/services/conversationsService.js#L129-L137

From that function you should always get back the room data, so you can afterwards trigger a join for that token, but @ma12-co might be better in telling you where that code is

**Comment by jakobroehrl** [comment]
@jancborchardt Should I use another icon?

**Comment by nickvergessen** [comment]
Converting to draft for easier sorting.

**Comment by nickvergessen** [comment]
> @jancborchardt Should I use another icon?

🏓

**Comment by jakobroehrl** [comment]
@nickvergessen 
When could we pick up the work here?
see: https://github.com/nextcloud/spreed/pull/4477#issuecomment-717810331

**Comment by jakobroehrl** [comment]
see: https://github.com/nextcloud/spreed/pull/4855

**Pull request closed without merging**
