### PR TITLE
Handle all user status changes in case of "End meeting for all" in 1 …

### PR DESCRIPTION
**Pull request by nickvergessen**
…execution

- [x] Requires https://github.com/nextcloud/server/pull/31106
- [x] Missing listener call to the correct event
- [x] Needs a lib update

### CODE REVIEW

**Comment by nickvergessen** [comment]
Turning to draft until server is in

**Comment by nickvergessen** [comment]
Rebased and lib bumped

**Review by vitormattos — COMMENTED** [review]
Integration tests?

**Comment by nickvergessen** [comment]
> Integration tests?

You fine with creating an issue about this?

**Review by CarlSchwan — APPROVED** [review]

**Comment by nickvergessen** [comment]
> You fine with creating an issue about this?

Reported at https://github.com/nextcloud/spreed/issues/6947

**Pull request merged**
