### PR TITLE
Sort rooms when joining or creating rooms.

### LINKED ISSUE #142: Directly add new call at top of list
Initially when adding a new call, it is added at the bottom of the list. Only after a few seconds it moves up. This is a bit strange and it should just directly appear on top.

cc @Ivansss

### PR DESCRIPTION
**Pull request by Ivansss**
Fix #142

### CODE REVIEW

**Comment by Ivansss** [comment]
@nickvergessen what do you think?

**Comment by nickvergessen** [comment]
I would do it explicitly by calling `$room->ping($this->userId, $newSessionId, time())` in `ApiController::joinRoom`
Also make sure that it's called for guests?

**Comment by nickvergessen** [comment]
👍

**Comment by jancborchardt** [comment]
Thanks a lot @Ivansss, good detail improvement :)

**Pull request merged**
