### PR TITLE
Add client links to personal settings

### PR DESCRIPTION
**Pull request by juliushaertl**
image

@nextcloud/talk 

cc @karlitschek

### CODE REVIEW

**Comment by mario** [comment]
Quick question: do we always show this or only when you have Talk installed?

**Comment by fancycode** [comment]
> Quick question: do we always show this or only when you have Talk installed?

It's in the talk app, so I'm assuming it will only be shown if the app is installed and enabled.

**Comment by mario** [comment]
@fancycode you're probably right :)

**Comment by juliushaertl** [comment]
Hmm that is strange:

> Invalid appinfo.xml file found: Element 'admin': This element is not expected. Expected is one of ( personal, personal-section ).

I'll have a look.

**Comment by karlitschek** [comment]
looks good!

**Comment by karlitschek** [comment]
maybe we should rename 'sync clients' to 'clients' ?

**Comment by mario** [comment]
Good idea. I'd guess the icon would need to be changed as well then.

**Comment by juliushaertl** [comment]
> maybe we should rename 'sync clients' to 'clients' ?

Maybe a more non-technical term would be even better then, how about calling it just "Apps" and using a phone icon for the section? cc @nextcloud/designers

**Comment by jancborchardt** [comment]
A good non-technical term which is also short enough for the navigation would be simply "Mobile & desktop". ("Clients" is definitely not a word people use.)

**Comment by juliushaertl** [comment]
PR for the section rename is in https://github.com/nextcloud/server/pull/9585

CI failure should also be fixed now.

**Pull request merged**
