### PR TITLE
Move requests from CallInfoView to room model

### PR DESCRIPTION
**Pull request by danxuliu**
This pull request is a refactoring that has almost no behaviour changes, except for a minor difference: now when a room is renamed, if the internal signaling server is used all the rooms are fetched instead of only the renamed one, and if the external signaling server is used the rooms are fetched only once instead of twice.

It needs to be backported to _stable16_, as it serves as the base for further fixes.

### CODE REVIEW

**Comment by nickvergessen** [comment]
> It needs to be backported to stable16, as it serves as the base for further fixes.

Which exactly? Since 17 is due soon, I would also then reduce the backports for 16 (as usual).

**Comment by danxuliu** [comment]
Things related to room synchronization and also UI bugs. Yes, I would also reduce the backports to _stable16_ too, but I also want _stable16_ to be left in good shape, and backporting those things right now it is not a big effort and it will make easier to backport future things if needed.

**Comment by nickvergessen** [comment]
Time to fix up

**Pull request merged**
