### PR TITLE
More design fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
- Use dark icons when not in a call (when white background)
- Switch position of app-sidebar-trigger (show on top) and fullscreen icon (show below)
- Fix submit arrow being outside of the input box

Please review @danxuliu @Ivansss @nickvergessen :)

### CODE REVIEW

**Comment by Ivansss** [comment]
Dark icons are not very visible when the camera is on 😕 
Also, it seems that they never change to white when in call.

**Comment by Ivansss** [comment]
Depending on the window size and the video resolution, full screen and right side bar icons could even be completely invisible.

screen shot 2018-01-10 at 00 11 00

screen shot 2018-01-10 at 00 10 45

**Comment by jancborchardt** [comment]
@Ivansss whoops, had some CSS in there which actually prevented the icons from ever becoming white. :) Now they are black whenever `.incall` is _not_ set.

**Comment by jancborchardt** [comment]
@Ivansss pushed the changes: https://github.com/nextcloud/spreed/pull/553/commits/c3e7f09de20c73c375e85845ea6ab4c71c4f4239#diff-9c227ff7cd07ef67bd28fd246b54f5b7R382

As said I need you to add the »video-disabled« class which is on #hideVideo also to the #mute element directly before it whenever video is disabled. :) Then we’re good.

**Pull request merged**
