### PR TITLE
Cannot disable sip

### PR DESCRIPTION
**Pull request by nickvergessen**
🙈 I wonder why `LockingSettings.vue` and `SipSettings.vue` are so different when they do the same thing :D

### CODE REVIEW

**Comment by PVince81** [comment]
> see_no_evil I wonder why `LockingSettings.vue` and `SipSettings.vue` are so different when they do the same thing :D

because they grew from some initial confusion and eventually it seems I only adjusted a single one later on

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by nickvergessen** [comment]
Which is good and which is bad? so I can use either and do a string replace?

**Comment by PVince81** [comment]
> Which is good and which is bad? so I can use either and do a string replace?

I don't remember. But one of them might not properly reset the checkbox state in case of error.

**Comment by PVince81** [comment]
I had some WIP for error handling and trying to reset the states here: https://github.com/nextcloud/spreed/pull/4671

**Comment by nickvergessen** [comment]
Seems this is only broken in 21, works fine in 20.
So it's a regression from  #4576

**Pull request merged**
