### PR TITLE
Also reload the conversation list every 30s with standalone signaling

### LINKED ISSUE #1431: Room list does not update with read status on external signaling server
## Steps to reproduce
1. Have a room with unread messages
2. Join another room
3. Read the unread message in another tab/device

### Expected behaviour
Unread marker disappears

### Actual behaviour
Room list is never refreshed

cc @fancycode

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1431

### CODE REVIEW

**Comment by fancycode** [comment]
Looks hackish :see_no_evil:  A better way would be to trigger an event from the server to the user so he can refresh the list whenever it is needed (e.g. when the list of read messages changes in a room).

If you don't want to implemented that right now, please add a TODO with a reference to #1431 so it can be fixed correctly in the future.

**Comment by nickvergessen** [comment]
Well the problem is a bit more complex and the optimal solution requires more coding.
I will later create a new issue for it, because that should then also be used for the internal signaling, (which also uses the 30s loop atm).

**Comment by nickvergessen** [comment]
Posted at https://github.com/nextcloud/spreed/issues/1810

**Pull request merged**
