### PR TITLE
Fix typo in trial

### LINKED ISSUE #3802: l10n: Trial or trail?
Shouldn't it be "trial"

https://github.com/nextcloud/spreed/blob/21202807638028d31c2185c1c042d5279f828f29/src/components/AdminSettings/HostedSignalingServer.vue#L42

https://github.com/nextcloud/spreed/blob/21202807638028d31c2185c1c042d5279f828f29/src/components/AdminSettings/HostedSignalingServer.vue#L49

### PR DESCRIPTION
**Pull request by nickvergessen**
Follow up to #3620

Fixes #3802

### CODE REVIEW

**Comment by rakekniven** [comment]
Fixes #3802

**Comment by danxuliu** [comment]
I removed what looked like the result of using `git add -u` ;-)

**Comment by MorrisJobke** [comment]
Sorry :/

**Pull request merged**
