### PR TITLE
🤖 Commands

### LINKED ISSUE #1179: chat integration via slash command
The uses of tag for external apps permit integration and interaction helping to promote single workspace like SLACK a /command will help to this. From my point of view it not necessary to be fancy,  just a system() call and userid like variable and a text response will make integration apps easy for every one..... Just and idea.

cheers
a good guide https://api.slack.com/slash-commands

### PR DESCRIPTION
**Pull request by nickvergessen**
This is a first step towards the option to allow writing bots.

1. Example input: `/calculate 42+23` 
2. User input + some meta data is passed on to a script called via shell_exec/exec and the output is posted as a comment to the user/all

Fix #1179

---

### Tasks
- [x] Allow/block guests
- [x] Allow management of commands via CLI
- [x] Allow messages to be only visible to some users
- [x] Invoke the scripts
- [x] Hardcode help/list commands
- [x] Allow apps to define commands
- [x] Write calculator as example command
- [x] Respect enabled flag
- [x] Allow aliases
- [x] Write docs about the parameters
- [x] Add an admin section which lists the commands
- [x] Adjust tests
- [ ] Make the admin list beautiful ( @skjnldsv )
- [ ] UI hint about commands/mentions
- [ ] UI option to start using a command (automatically adding `/help ` into the input)

---

### Calc example
`./occ talk:command:add calc calculator "/path/to/calc.sh \"{ARGUMENTS_DOUBLEQUOTE_ESCAPED}\"" 1 3`

**calc.sh:**
```sh
while test $# -gt 0; do
  case "$1" in
    --help)
      echo "/calc - A Nextcloud Talk chat wrapper for gnome-calculator"
      echo " "
      echo "Simple equations: /calc 3 + 4 * 5"
      echo "Complex equations: /calc sin(3) + 3^3 * sqrt(5)"
      exit 0
      ;;
    *)
      break
      ;;
 esac
done

set -f
echo "$@ ="
echo $(gnome-calculator --solve="$@")
```

### Echo example

`./occ talk:command:add echo reflection "/path/to/echo.sh \"{ARGUMENTS_DOUBLEQUOTE_ESCAPED}\"" 1 3`

**echo.sh:**
```sh
while test $# -gt 0; do
  case "$1" in
    --help)
      echo "/echo - A test command which returns what you typed"
      echo " "
      echo "Example: /echo hello there"
      echo "Result: \"hello there\""
      exit 0
      ;;
    *)
      break
      ;;
 esac
done

set -f
echo "You typed: $@"
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ref https://developers.google.com/hangouts/chat/reference/message-formats/cards

**Comment by nickvergessen** [comment]
> Ref https://developers.google.com/hangouts/chat/reference/message-formats/cards

@danxuliu I had a look at this. The biggest problem is, that it would require all clients to understand HTML or any other markup we add/support there. So for version 1 I would go with plaintext only (also note that we have a 1k char limit atm). We can still go for a output-markup later on.

**Comment by nickvergessen** [comment]
@skjnldsv when you are back again, can you help turning the admin overview of commands into a nice grid layout similar to the user management. That would be very cool :sunglasses:

**Comment by nickvergessen** [comment]
Ready for review, UI hint and finishing will go in a new PR

**Comment by skjnldsv** [comment]
> @skjnldsv when you are back again, can you help turning the admin overview of commands into a nice grid layout similar to the user management. That would be very cool

of course! Follow-up pr ?

**Comment by nickvergessen** [comment]
> of course! Follow-up pr ?

yes, much appriciated

**Comment by skjnldsv** [comment]
> > of course! Follow-up pr ?
> 
> yes, much appriciated

please ping me once merged, I'll address this :)

**Comment by nickvergessen** [comment]
> Missing: Rendering correctly bot messages that are not for the current user.

Now done, please re-review @Ivansss

**Comment by nickvergessen** [comment]
@skjnldsv it's in :)

**Pull request merged**
