### PR TITLE
Bump Handlebars from 4.0.12 to 4.1.2

### PR DESCRIPTION
**Pull request by danxuliu**
No changes in the compiled templates.

### CODE REVIEW

**Comment by nickvergessen** [comment]
server requires handlebar to be installed globally.
So we could remove that and use also the global one?

**Comment by danxuliu** [comment]
As it is a development dependency I prefer to keep it explicit; otherwise you would need to install the development dependencies of the server in order to compile the Handlebars templates in the app.

In any case, this dependency should go away soon™, so I would keep it for now (I just updated it to reduce noise when calling `npm update`).

**Comment by nickvergessen** [comment]
It's not a development dependency in the server, but the server requires it to be installed globally.
https://github.com/nextcloud/server/blob/master/build/compile-handlebars-templates.sh#L8

But yeah, obsoleted soon so ...

**Comment by nickvergessen** [comment]
conflict

**Pull request closed without merging**
