### PR TITLE
Fix undefined index latest_comment

### PR DESCRIPTION
**Pull request by nickvergessen**
1. Start mentioning someone in a chat
2. See error in log file (if on debug/info)

### CODE REVIEW

**Comment by danxuliu** [comment]
[Backport to stable13](https://github.com/nextcloud/spreed/blob/a76eb9b1a2a4953097063aaf199e9ff80fb10984/lib/Chat/CommentsManager.php#L177)?

**Comment by nickvergessen** [comment]
No, it's only in master

**Comment by danxuliu** [comment]
> No, it's only in master

Do you mean the fix? Because the issue is in _stable13_ too (see link).

**Comment by nickvergessen** [comment]
Right, I thought this was only done after the last release

**Pull request merged**
