### PR TITLE
Add ability to collapse the grid view

### PR DESCRIPTION
**Pull request by PVince81**
To be able to focus on the video / screen of the current presenter.

Fixes https://github.com/nextcloud/spreed/issues/4245

### Todos

- [x] Fix design/positioning of button
- [x] Move microphone/video/etc actions to the bottom of the screen when the grid is collapsed
- [x] Test multiple call modes to make sure it looks fine
- [x] Test with sidebar view - blocked by https://github.com/nextcloud/server/issues/23445

### CODE REVIEW

**Comment by PVince81** [comment]
After talking with @ma12-co we decided to keep my PR and I've taken a similar approach from https://github.com/nextcloud/spreed/pull/4365 and added (and fixed) the slide animation.

Next up is extracting the local call controls to a higher layer to make them always visible and available even when collapsed.

**Comment by PVince81** [comment]
- [ ] sort out isBig attribute and expected logic
- [ ] wire up other missing attributes

**Comment by PVince81** [comment]
current state when open:
image

and collapsed:
image

**Comment by PVince81** [comment]
most stuff sorted out, but one thing remaining:

- [ ] network quality warning broken when grid is collapsed: quickest would be to move it back to the media controls location as it creates an extra temporary icon.

I do wonder if there is another kind of interaction we could use to show that warning and not clutter that bottom right corner with a bubble.

**Comment by PVince81** [comment]
next challenge: 
image

**Comment by PVince81** [comment]
ok, it will look like this:
image

**Comment by PVince81** [comment]
- [ ] BUG: missing mute and video buttons in sidebar mode

(tested using this PR merged with https://github.com/nextcloud/spreed/pull/4291)

**Comment by PVince81** [comment]
I've fixed the sidebar mode. It required me to move the LocalMediaControls from the Grid to the CallView.

I've also tested the "network connection warning" mode and it looks fine in sidebar mode.

**Comment by PVince81** [comment]
image

**Review by ma12-co — CHANGES_REQUESTED** [review]
shouldn't this transition be applied to the .grid-main-wrapper div?
At the moment the transition feels a bit weird, it seems like .grid-main-wrapper comes in without transition and its content slides up in it

**Review by ma12-co — COMMENTED** [review]
* missing hover feedback, I'd say we should have it like the buttons in the topbar;
* when active, the button has white background;
* Missing height and width of 44px;

Very nice work :+1:

**Comment by PVince81** [comment]
- [ ] BUG: grid view video sizes are not correct / layout borken
- [ ] BUG: once grid view fixed, the bottom right video will not always have 300px width, so need to find a way to adjust
- [ ] TODO: https://github.com/nextcloud/spreed/pull/4363#pullrequestreview-509422426

**Comment by PVince81** [comment]
- [ ] BUG: when "waiting for others to join" the stripe mode seems engaged, it shouldn't

**Comment by PVince81** [comment]
- [ ] should we make one to one mode also collapsible ?
    - keep the chevron button but don't use stripe mode

**Comment by ma12-co** [comment]
>  should we make one to one mode also collapsible ?

Yes, I'd say it's a desirable thing to have, especially when the other participant is screen-sharing

**Comment by PVince81** [comment]
grid view is fixed.
in that mode now LocalMediaControls are present inside the LocalVideo. otherwise it uses the outside instance.

next up: one on one view and the remaining bits.

For one on one I'll see if I can reuse the grid/stripe view but with its left part disabled

**Comment by ma12-co** [comment]
> next up: one on one view and the remaining bits.

Do you want to do it in this pr of follow-up?

**Comment by PVince81** [comment]
@ma12-co already done. I want to address all checkboxes within this PR.

Feel free to have a quick design review.

- [ ] BUG: "waiting for others" has black background

**Comment by PVince81** [comment]
- [ ] retest sidebar mode

**Comment by PVince81** [comment]
button styles fixed now

**Comment by PVince81** [comment]
for the transition I tried different containements but the top part didn't animate while the bottom part slid down.
I think this is because we used `translate` so it would only translate the stripe's absolute position without affecting the page's layout. Need to look into maybe animating another property.

**Comment by PVince81** [comment]
Seems it might be possible to temporarily set `position: absolute; bottom 0;` on the ".wrapper" element while running the transition. This forces the top panel to expand directly before we start the slide down.

I'll study transitions more in detail to find out where exactly to put that as my trials did not succeed yet.

**Comment by PVince81** [comment]
I've fixed the slide animation now with a small hack. I didn't want to reorganize all the containers for now.
We could look into the latter separately.

Tests collapsing:
- [x] TEST: "waiting for others"
- [x] TEST: one to one
- [x] TEST: one to many
- [x] TEST: grid view still works (and no collapse button there)
- [x] TEST: test with screen share on then collapse
- [x] TEST: sidebar mode still works as before

**Review by ma12-co — COMMENTED** [review]
I get this error when switching to grid: 
Screenshot from 2020-10-19 13-05-18

**Comment by PVince81** [comment]
when testing I had the latest nextcloud-vue master included.
retrying with the latest spreed master

**Comment by PVince81** [comment]
Got it, the exact steps are:

1. Start a call with three people
1. Collapse the strip
1. Switch to grid view
1. Switch back to speaker view

The reason is that `isStripe()' is abused to re-generate the grid in `makeGrid`, and the latter function is trying to access the grid object while it's not visible. I'll try adding a check there to avoid calling `makeGrid` when collapsed.

Too many states :-S

**Comment by PVince81** [comment]
@ma12-co I've fixed the issue when switching back and forth to grid while collapsed

**Review by ma12-co — APPROVED** [review]
Amazing :) 
One last cool thing would be a tooltip that shows up on hover that says something like "Hide videos" and "Show videos"

**Comment by PVince81** [comment]
it's not videos if you only see avatars there, so not sure about the text.
maybe we can look into tooltips separately as I noticed there are more tooltips missing in the call view

**Comment by danxuliu** [comment]
Since this pull request when the call view is shown in the sidebar the media controls are a bit off from the video (I have tested with nextcloud/server@fd178b9^ and also rebasing #4291 and using it against nextcloud/server@766590d204^, so it should not be a problem of an outdated style from server):

**Before:**
Files-Sidebar-Controls-Before

**After:**
Files-Sidebar-Controls-After

Is that intended, or known?

**Comment by PVince81** [comment]
I didn't observe this before. Can you make a ticket and provide steps to reproduce and maybe also window size ?
With all the different tests I made I didn't see that.

The reason is that now the controls are not part of the video box any more, they are outside. But how did you manage to have the video box smaller than usual ?

**Comment by ma12-co** [comment]
We really need to implement tests for the call view. There are so many scenarios that I's becoming impossible to test all of them  whenever someone changes something there

**Comment by PVince81** [comment]
I've raised https://github.com/nextcloud/spreed/issues/4440 for adding automated tests for the frontend

**Comment by PVince81** [comment]
@ma12-co while we might be able to test the code and logic, we can't test layout and styling stuff, so if a background color looks off or a container is not stretched correctly, we'd still need some manual testing to find that out. However we wouldn't need to retest all the logic.

**Pull request merged**
