### PR TITLE
Add different messages on emptycontent depending on room type.

### LINKED ISSUE #52: Message when group/room empty
The default message that appears when no group/room is joined is fine: 'Time to do your hair! :) Then join a room or create a new one'

But a different message should appear when be alone in a group. Something like: 'You are alone in this group. Join a different one or invite someone'

### PR DESCRIPTION
**Pull request by Ivansss**
- Fix #52

### CODE REVIEW

**Comment by Ivansss** [comment]
@jancborchardt please take a look, probably it will need some css changes :)

**Comment by nickvergessen** [comment]
Three small things:
1. The copy icon should be next to the link-box:
> calls_-_nextcloud_-_2016-11-25_11 25 35

2. Also I can not manually copy the link, because the `div#videos` is above `div#emptycontent`

3. When you are in an empty group call which also has no other participants
 > Waiting for others to join the room …

doesn't make a lot of sense. Should say something like "add users to this call..."

**Comment by Ivansss** [comment]
> 2. Also I can not manually copy the link, because the div#videos is above div#emptycontent

@jancborchardt what do you think about this? should we overlap div#emptycontent on top of div#videos?

**Comment by nickvergessen** [comment]
Works, merging so we can release it

**Comment by jancborchardt** [comment]
Awesome @Ivansss, so this also fixes https://github.com/nextcloud/spreed/issues/139 :)

**Pull request merged**
