### PR TITLE
Fix connection quality warning shown due to stalled stats

### PR DESCRIPTION
**Pull request by danxuliu**
Requires #5884 ~~(kept as draft until that is merged, but ready for review nevertheless)~~

The stats reported by the browser can sometimes stall for a second (it is unclear whether the browser does not update the stats or Janus does not send them, though). When that happens the stats are still reported, but with the same values as in the previous report. As there were no transmitted packets the "very bad quality" state was (wrongly) triggered.

To solve this now if there were no transmitted packets in the last report the analysis is kept on hold. If in the next report the number of packets has changed then the previous report is considered to have stalled and the new values are distributed between the previous and current report. If the number of packets is still zero then the previous report is considered to have been legit and the previous and current values are added as normal.

Besides the main fix this pull request also fixes the stats being wrongly reset when calling "setAnalysisEnabledXXX(true)" twice. This happens whenever the audio or video is enabled while being already enabled. This happens, for example, when another participant joins and the current media state is sent; whether that should happen or not is a different matter, but in any case, calling "setAnalysisEnabledXXX(true)" twice should not reset the stats.

## How to test
- Add a log to know when the stats reported zero transmitted packets (without this pull request, by adding [an else clause](https://github.com/nextcloud/spreed/blob/2bba6b48760ead80bdc0ec1abba4a28f49703f6f/src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js#L401); with this pull request, by using [the else clause in `_addStats()`](https://github.com/nextcloud/spreed/commit/ae7df361616930c9ee3715439d10e73c4ae83f5b#diff-7a158e361f2d1d4260e85fa2256fcd4d4b64d2db206d3bf3406cd6366c01cabfR507))
- Setup the HPB
- Start a call
- Leave the call running for a while; sometimes joining and leaving the call with another participant causes the stats to stall

### Result with this pull request
Eventually the logs will show that the stats were stalled (zero transmitted packets in a single report), but there will be no logs about the connection quality warning

### Result with this pull request
Eventually the logs will show that the stats were stalled (zero transmitted packets in a single report) and there will be logs about the connection quality warning (high lost packet ratio, ~0.45 and then ~0.375, the lost packet ratio values will be similar to _[0, 0, 0, 0, 1.5]_ and then _[0, 0, 0, 1.5, 0]_)

### CODE REVIEW

**Comment by PVince81** [comment]
the base PR was merge, time to rebase ?

**Comment by danxuliu** [comment]
> the base PR was merged, time to rebase ?

Done.

**Review by PVince81 — APPROVED** [review]
:+1: code looks fine.

This is becoming quite complex, feels like adding some JS tests is overdue...

**Comment by danxuliu** [comment]
> This is becoming quite complex, feels like adding some JS tests is overdue...

Totally. Feel free to add them.

**Comment by PVince81** [comment]
need to wait for https://github.com/nextcloud/spreed/pull/5911 before backporting

**Pull request merged**
