### PR TITLE
Use the contacts menu in the participant list

### LINKED ISSUE #1795: Allow to create private 1-1 conversation from participant list
In the participant option menu, an entry to create or go to the existing chat room would be a nice feature :)

Capture d’écran_2019-05-09_08-55-52

### PR DESCRIPTION
**Pull request by nickvergessen**
@skjnldsv layout is broken becuase sidebar navigation and contacts menu collide, can you help solve this?

Fix #1795 

## Contacts menu in chat mention
Bildschirmfoto von 2019-05-15 14-22-57

## Contacts menu in participant list
Bildschirmfoto von 2019-05-15 14-22-52

### CODE REVIEW

**Comment by ma12-co** [comment]
@nickvergessen could you describe a bit more how to reproduce the issue?

**Comment by nickvergessen** [comment]
So without this PR when you click on the user avatar in the right sidebar nothing happens.
With this PR the pop up is shown, but the icons of the options seem to be broken a lot.

**Comment by ma12-co** [comment]
I just fixed the overflow which was hidden on the popup container and a scrollbar appeared, but the icons seem fine to me, how should they look?
Screenshot from 2019-07-02 14-34-46

**Comment by ma12-co** [comment]
Ok, I just saw what you mean.. I fixed another bug then :)
I'll check the avatars now

**Comment by ma12-co** [comment]
Great Joas, one last thing: do you also see the left part of the menu hidden? 
Screenshot from 2019-07-02 17-50-02

**Comment by nickvergessen** [comment]
Yeah, it's from `.popovermenu.contactsmenu-popover {` which adds `margin: 0;`
If I set this to 4px the popup is out of position but with border.

maybe @skjnldsv can have a look

**Comment by skjnldsv** [comment]
No idea about this one, I did not create it.
We're now all using the dedicated vue component :see_no_evil:

**Comment by nickvergessen** [comment]
Fixed the missing border. Good to merge now

**Pull request merged**
