### PR TITLE
Recognize voice messages, object and file shares as unread messages

### LINKED ISSUE #6621: new voice message hard to recognize
voice message is not bold:
image

text is bold:
image

attachment is bold:
image

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6621

### CODE REVIEW

**Comment by nickvergessen** [comment]
To backport for first patch version of 23

**Comment by danxuliu** [comment]
I have added some integration tests. They show that the unread counter for the sender is not cleared when a file is shared, but I do not why; it could be related to the difference between the verb and the message type (`object_shared` and `file_shared`), but it is just a guess, I have not actually checked.

**Comment by nickvergessen** [comment]
> They show that the unread counter for the sender is not cleared when a file is shared

The problem is we don't know if you shared from files app (should not mark read as there could be other messages in the meantime) or from inside talk (could mark read). But also opening in the web does not mark read until another message is being posted.

**Comment by danxuliu** [comment]
> > They show that the unread counter for the sender is not cleared when a file is shared
> 
> The problem is we don't know if you shared from files app (should not mark read as there could be other messages in the meantime) or from inside talk (could mark read).

Right, good point :+1: I have updated the tests to reflect that.

**Comment by vitormattos** [comment]
Looking the tests sounds ok.
The broken static analysis test is about outdated dependency?

**Comment by vitormattos** [comment]
parts of broken static tests I fixed on #6661

**Review by vitormattos — APPROVED** [review]

**Pull request merged**
