### PR TITLE
Implement link previews

### PR DESCRIPTION
**Pull request by juliushaertl**
- [x] Requires https://github.com/nextcloud/server/pull/33494
- [x] Requires https://github.com/nextcloud/vue-richtext/pull/743
- [ ] ~~Decide if the link metadata should be fetched upfront when fetching the message list maybe~~ => Moved to https://github.com/nextcloud/spreed/issues/7833
- [ ] ~~Figure out a proper way to set the width~~ => Moved to https://github.com/nextcloud/spreed/issues/7832

Screenshot 2022-08-30 at 08 59 24

### CODE REVIEW

**Comment by nickvergessen** [comment]
For me links are not clickable anymore?
Bildschirmfoto vom 2022-08-31 08-58-46

**Comment by juliushaertl** [comment]
From the design review with @jancborchardt but might be a follow up:

- [ ] Talk could show this preview already when you paste a link in the composer, above your text, much like e.g. Signal does (similar style as for replying to others)

**Comment by nickvergessen** [comment]
Moved the other open questions also to new issues so they can be done as a follow up

**Comment by nickvergessen** [comment]
Will bump the lib to 2.0.0 and fix eslint

**Comment by juliushaertl** [comment]
@nickvergessen Quick update, I did a follow up for the frontend bits and missed that i included the event in there. https://github.com/nextcloud/server/pull/33755 adds that and I prepared a commit to either merge afterwards or cherry pick to this PR: f627c84ec

**Comment by nickvergessen** [comment]
But that is only for the "special" handling of files/talk/... not for general link previews, right?

**Comment by juliushaertl** [comment]
Yes, we can also add the event in a follow up.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Created https://github.com/nextcloud/spreed/issues/7837

**Comment by Renari** [comment]
Does anyone know how to enable this? This was marked as completed but for me link previews still show like this.



instead of this:


This issue for this feature was here:
https://github.com/nextcloud/server/issues/32979

And was marked as a duplicate of this.

**Pull request merged**
