### PR TITLE
Fix unwanted background changes in some buttons

### LINKED ISSUE #5049: Strange hover highlights
There is strange hover feedback on the "Share file to chat" option when the user has no quota and hovers the message list

### PR DESCRIPTION
**Pull request by ma12-co**
fix #5049

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Screenshot  or description which buttons are affected?

**Comment by nickvergessen** [comment]
Ah didnt see the linked issue

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Also affects the sidebar open/close handle. it's fine while not in a call. But I think in the call view we actually need the hover, to make the button visible  (not only when you know where to hover). Just imagine a white presentation or wall background (Ref https://github.com/nextcloud/spreed/issues/5016 )

**Comment by ma12-co** [comment]
Done

Screenshot from 2021-02-03 15-22-32

**Comment by PVince81** [comment]
Please rebase to get some master changes. This is how I tested it.

- Call view looks fine.
- Ghost hover is gone

Still, there's a hover inconsistency between the attachment button and the emoji picker button:
image
image

@ma12-co mind fixing that as well ?

**Comment by ma12-co** [comment]
> Still, there's a hover inconsistency between the attachment button and the emoji picker button:

Fixed it here for now @PVince81

**Comment by PVince81** [comment]
I just switched computers and now I'm on my "small screen with bigger fonts" and noticed this:
image

We should add a bit of padding here.

But as this is unrelated, let's do it separately.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
