### PR TITLE
❤️ Message reactions front-end

### LINKED ISSUE #1920: Reactions to chat messages
Something similar to Slack:

[Source](https://thenextweb.com/apps/2015/07/09/how-did-we-ever-live-without-this/)

### PR DESCRIPTION
**Pull request by marcoambrosini**
closes #1920  

Signed-off-by: marco <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by marcoambrosini** [comment]
next items 

- [ ] Make unread marker not care about mention messages
- [ ] If reacting to last message, scroll to bottom
- [ ] Reply feature not working
- [ ] Hovering of submenus broken
- [ ] Fix tests

**Comment by marcoambrosini** [comment]
-[ ] Only fetch reaction details when hovering the reactions bar

**Comment by marcoambrosini** [comment]
[more features and fixes coming in part 2](feature/noid/reactions-part-two)

**Review by nickvergessen — APPROVED** [review]
Works in general and can be merged once `.DS_Store` has been deleted

**Comment by nickvergessen** [comment]
Was part of https://github.com/nextcloud/spreed/pull/6860/commits/f30ff9a2fef49f30b1ae239525787bf4c24b1ba4 removed it there.

Rebased, can merge after CI is done

**Pull request merged**
