### PR TITLE
Add upload editor in files sidebar mode

### PR DESCRIPTION
**Pull request by danxuliu**
Follow up to #3988

Extracted from #4291 for tidiness and easier backporting.

### CODE REVIEW

**Comment by danxuliu** [comment]
Mmmm, this needs more work (I tested this in _stable20_, but _master_ should be the same).

- Open the Files app
- Share two files
- Reload the Files app (to work around the bug in the server about FileInfo not being properly updated when a file is shared)
- Open the sidebar for the first file
- Join the conversation
- Upload a file, but close the modal by clicking outside it
- Open the sidebar for the second file
- Join the conversation

The modal will be shown again.

**Comment by PVince81** [comment]
oh, so this was always missing ? otherwise we just hide the upload button for now

**Comment by danxuliu** [comment]
> oh, so this was always missing ?

It seems so :-)

> otherwise we just hide the upload button for now

The latest pushed commits should fix the described issue (and do a small cleanup). But my development machine is doing funny things so I could not properly test it :-(

**Comment by PVince81** [comment]
but if https://github.com/nextcloud/spreed/pull/4291 is not merged first, then this PR here won't be testable ?

**Comment by danxuliu** [comment]
> The latest pushed commits should fix the described issue (and do a small cleanup). But my development machine is doing funny things so I could not properly test it :-(

Mmm, no, it does not fix the described issue. It changes it, but there is still an issue :-P (the chat tab is empty for the second file).

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
> the chat tab is empty for the second file

here after rebase not happening any more, it was likely the bug we already fixed (somehow I can't find the PR any more)

however the upload dialog doesn't appear after selecting files in the file picker

**Comment by PVince81** [comment]
I've re-tried this and the upload dialog seems to work now. Maybe I had some caching issues.

**Review by PVince81 — APPROVED** [review]
:+1: tested both in sidebar mode and regular mode, upload works

**Pull request merged**
