### PR TITLE
perf(autoloader): Force own autoloader

### PR DESCRIPTION
**Pull request by ChristophWurst**
And don't register any generic PSR-4 nor PSR-0 loader in server.

https://github.com/nextcloud/server/blob/473c546b5c562e19ba8f9d3aef9cd64d2458cda7/lib/private/legacy/OC_App.php#L284-L290

### Blackfire comparison graph on IO wait
Bildschirmfoto vom 2023-01-20 13-51-25

### Blackfire recommendations before
Bildschirmfoto vom 2023-01-20 13-53-14

### Blackfire recommendations after
Bildschirmfoto vom 2023-01-20 13-50-49

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
:sloth:  | :snail: 

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> metrics.composer.autoload.find_file.count 117 <= 50

Server and this app have authorative autoloaders. But I think the generic autoloader in server tries to load this app's files before the shipped autoloader gets a change.

**Comment by nickvergessen** [comment]
Thanks, I was always tempted to add one, but I disliked the "ah forgot to run `bash build/autoload...`" from server. I didn't know it's possible to do it for 3rdparty but not the own classes :)

**Comment by nickvergessen** [comment]
Seems CI doesn't like it
grafik

**Comment by ChristophWurst** [comment]
that means `composer i` didn't happen

**Comment by nickvergessen** [comment]
> that means composer i didn't happen

Right, it was run only after the app was enabled.
Fixed now

**Review by nickvergessen — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Tip: https://github.com/nextcloud/mail/pull/8020 to relax the autoloader on dev setups and make it find new files too

**Pull request merged**
