### PR TITLE
More design work & clean up to reduce possible height of room details

### PR DESCRIPTION
**Pull request by jancborchardt**
- Cleaning up the h3 and rename style to not jump on rename 
- Put »Join call« and »Share link« on one line, proper layout and saving space :)

@danxuliu if you think it’s necessary or can do it, we could also move the Password input into a 3-dot menu popover (icon right next to copy link). But this is already much better. :)

screenshot from 2018-01-10 10-21-05 - screenshot from 2018-01-10 10-21-45

Ref https://github.com/nextcloud/spreed/pull/558#issuecomment-356522526

### CODE REVIEW

**Comment by jancborchardt** [comment]
Added some screenshots and put some proper layout in the room info. :) I really like it, what do you think @nickvergessen @Ivansss @danxuliu?

**Comment by nickvergessen** [comment]
Looks a bit stupid when you are not a moderator (button is veryyyyyyyyyyyyyyyyyyy long)
and the copy link icon is on a single row instead of the room name:
> bildschirmfoto von 2018-01-10 10-30-11

**Comment by Ivansss** [comment]
I find it a bit weird

screen shot 2018-01-10 at 10 29 55

**Comment by jancborchardt** [comment]
@nickvergessen will look into fixing that, ok.

@Ivansss as said above: if you think it’s necessary or can do it, we could also move the Password input into a 3-dot menu popover (icon right next to copy link). But this is already much better. :)

**Comment by Ivansss** [comment]
I know this change was done to reduce the height of the header.
But I still prefer all things related with sharing at the bottom of "Join call" button.

screen shot 2018-01-10 at 10 50 32

If the call is shared the set/change password will be always visible, so the height of the header will be the same in both cases.

But this is just my opinion 😊 what do you guys think?

**Comment by jancborchardt** [comment]
@nickvergessen fixed everything you mentioned. :)

> If the call is shared the set/change password will be always visible, so the height of the header will be the same in both cases.

@Ivansss that is precisely why I mentioned twice now ;) that the password should be in a popover, like we had in the 3-dot-menu in the sidebar. It really should not be displayed the whole time. And then the header will always be shorter, and the same height in any case.

**Comment by nickvergessen** [comment]
We have apps for mobile and all others should have big enough screens to handle this?
So we move it to 3.1 and fix it properly?

**Comment by jancborchardt** [comment]
Well, these fixes are already better than the current state in many respects. The thing to postpone (if needed) is only the move of the password input to a popover. But even without that this is good to merge.

**Comment by danxuliu** [comment]
@nickvergessen 
>  We have apps for mobile and all others should have big enough screens to handle this?

But the chat is not implemented yet in the mobile apps, or is it?

@jancborchardt 
> these fixes are already better than the current state in many respects

Like @Ivansss I prefer the sharing options below the _Join call_ button too :-P

**Comment by nickvergessen** [comment]
Okay, so lets keep the current for 3.0 and fix it in a good looking way for 3.1 (which is only some days away, we will release independent from server)

**Comment by jancborchardt** [comment]
Talked with @Ivansss, we will leave it for 3.0 like current, and for 3.1 do it like this here, with a »Lock« icon next to the Copy link icon, which will open a popover bubble for the password.

**Comment by jancborchardt** [comment]
(This also fixes a bug which only occurs with very long room names where the edit button is shown below the name and makes the whole layout jump btw.)

**Comment by schiessle** [comment]
> if you think it’s necessary or can do it, we could also move the Password input into a 3-dot 

I would give it a try. The password input field is way to eye-catching

**Comment by nickvergessen** [comment]
Conflicting and needs major changes, closing for now, please redo in little steps so we can merge them quickly.

**Pull request closed without merging**
