### PR TITLE
Better chat notification handling

### LINKED ISSUE #1575: Notifications for chats are not showing when browser tab/window is inactive
## Steps to reproduce
1. Join a chat and stay in room but change browser tab
2. Make someone in the room send you a message
3. No notification raised

### Expected behaviour
As the browser tab or window is not active, user should be marked as inactive and the receive notification.

### Actual behaviour
No notification is raised because of user not being marked "inactive" on window change.
So you are to miss all messages from other until you go back to Nextcloud talk tab/window

## I removed many of items asked in this bug in order to keep it clear. Those were not revelant.
If you miss any information, please feel free to ask.

## Browser ALL

**Operating system:** Ubuntu
**Browser name:** Firefox/Chrome

**Browser version:** 65 for Firefox

## Spreed app

**Spreed app version:** 5.0.2

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Maria

**PHP version:**

**Nextcloud Version:** 15.0.4

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Dont remove all chat notifications when pulling for new messages
- [x] Also notifier users which are active in the chat
- [x] Remove all chat notifications when joining a room
- [x] Mark chat notifications of read messages done

Fix #1575

### CODE REVIEW

**Comment by nickvergessen** [comment]
Saving this commit here:

<details>
```patch
From af32fced57848dfe38eb98b43724febe4c1c9147 Mon Sep 17 00:00:00 2001
From: Joas Schilling <coding@schilljs.com>
Date: Tue, 9 Jul 2019 17:28:09 +0200
Subject: [PATCH] Mark chat notifications as solved when they are read by an
 active session and older than 1 minute

Signed-off-by: Joas Schilling <coding@schilljs.com>
---
 lib/Notification/Notifier.php           | 15 +++++++++++++++
 tests/php/Notification/NotifierTest.php |  5 +++++
 2 files changed, 20 insertions(+)

diff --git a/lib/Notification/Notifier.php b/lib/Notification/Notifier.php
index 58c252facc..e48d3928e5 100644
--- a/lib/Notification/Notifier.php
+++ b/lib/Notification/Notifier.php
@@ -30,6 +30,7 @@
 use OCA\Spreed\Manager;
 use OCA\Spreed\Participant;
 use OCA\Spreed\Room;
+use OCP\AppFramework\Utility\ITimeFactory;
 use OCP\Comments\ICommentsManager;
 use OCP\Comments\NotFoundException;
 use OCP\IL10N;
@@ -65,6 +66,8 @@ class Notifier implements INotifier {
 	protected $commentManager;
 	/** @var MessageParser */
 	protected $messageParser;
+	/** @var ITimeFactory */
+	protected $timeFactory;
 	/** @var Definitions */
 	protected $definitions;
 
@@ -77,6 +80,7 @@ public function __construct(IFactory $lFactory,
 								INotificationManager $notificationManager,
 								ICommentsManager $commentManager,
 								MessageParser $messageParser,
+								ITimeFactory $timeFactory,
 								Definitions $definitions) {
 		$this->lFactory = $lFactory;
 		$this->url = $url;
@@ -87,6 +91,7 @@ public function __construct(IFactory $lFactory,
 		$this->notificationManager = $notificationManager;
 		$this->commentManager = $commentManager;
 		$this->messageParser = $messageParser;
+		$this->timeFactory = $timeFactory;
 		$this->definitions = $definitions;
 	}
 
@@ -167,6 +172,16 @@ protected function parseChatMessage(INotification $notification, Room $room, Par
 			throw new \InvalidArgumentException('Unknown object type');
 		}
 
+		if ($participant->getSessionId()) {
+			$pingAge = $this->timeFactory->getTime() - $participant->getLastPing();
+			$messageAge = $this->timeFactory->getTime() - $notification->getDateTime()->getTimestamp();
+			if ($messageAge > 60 && $pingAge < $messageAge) {
+				// Remove chat notifications after 60 seconds when the user has a active session in the conversation
+				$this->notificationManager->markProcessed($notification);
+				throw new \InvalidArgumentException('Outdated notification');
+			}
+		}
+
 		$subjectParameters = $notification->getSubjectParameters();
 
 		$richSubjectUser = null;
diff --git a/tests/php/Notification/NotifierTest.php b/tests/php/Notification/NotifierTest.php
index 3109c92493..9efc13ecfa 100644
--- a/tests/php/Notification/NotifierTest.php
+++ b/tests/php/Notification/NotifierTest.php
@@ -29,6 +29,7 @@
 use OCA\Spreed\Notification\Notifier;
 use OCA\Spreed\Participant;
 use OCA\Spreed\Room;
+use OCP\AppFramework\Utility\ITimeFactory;
 use OCP\Comments\IComment;
 use OCP\Comments\ICommentsManager;
 use OCP\IL10N;
@@ -62,6 +63,8 @@ class NotifierTest extends \Test\TestCase {
 	protected $commentsManager;
 	/** @var MessageParser|MockObject */
 	protected $messageParser;
+	/** @var ITimeFactory|MockObject */
+	protected $timeFactory;
 	/** @var Definitions|MockObject */
 	protected $definitions;
 	/** @var Notifier */
@@ -79,6 +82,7 @@ public function setUp() {
 		$this->notificationManager = $this->createMock(INotificationManager::class);
 		$this->commentsManager = $this->createMock(ICommentsManager::class);
 		$this->messageParser = $this->createMock(MessageParser::class);
+		$this->timeFactory = $this->createMock(ITimeFactory::class);
 		$this->definitions = $this->createMock(Definitions::class);
 
 		$this->notifier = new Notifier(
@@ -91,6 +95,7 @@ public function setUp() {
 			$this->notificationManager,
 			$this->commentsManager,
 			$this->messageParser,
+			$this->timeFactory,
 			$this->definitions
 		);
 	}
```
</details>

**Comment by nickvergessen** [comment]
With
> Also notifier users which are active in the chat

I'm not entirely sure how to proceed. I'd like to suppress the notification when the window is active, but not sure if the notification app allows something like this. Currently there is another thing on the todo list:

> Mark chat notifications as read after 1 min when the user has a session in conversation - this allows us to pop the browser notification and we still dont leave a mess behind afterwards

But it also feels weird. should basically only happen when the window is active. because if you had it open in the background and then shutdown your maschine, I wouldn't know why the mobile app should have the notification wiped. I think it makes more sense to move the removing to ChatController::setReadMarker() instead. Is this properly invoked already from the web? cc @PVince81

**Comment by nickvergessen** [comment]
Ah, auto-mark read in chat controller and the endpoint use the same function, so I will just go with an event in there. will work for both cases as well as the mobile clients

**Comment by nickvergessen** [comment]
Should be good for review now and improves the handling quite a lot.

**Review by PVince81 — APPROVED** [review]
:+1: tested, works

Tested by having read and unread messages and I could see the notifications either stay (when unread in the message list) or disappear (when read in the message list). Of course had to wait for notifications to be pulled.

Also confirmed that notifications get cleared when leaving a room.

**Comment by nickvergessen** [comment]
> Also confirmed that notifications get cleared when leaving a room.

It shouldn't but I guess it does because of the readmarker?

**Review by Ivansss — CHANGES_REQUESTED** [review]
Needs re-thinking.
Always sending push notifications even when the user is active in a mobile app will generate a weird user experience.

**Comment by PVince81** [comment]
> > Also confirmed that notifications get cleared when leaving a room.
> 
> It shouldn't but I guess it does because of the readmarker?

Possibly. But I think this behavior is acceptable.
I actually wanted to try the item you listed where you clear notifications when joining. So even if notifications are kept after leaving, if you'd rejoin an open conversation, it would clear them anyway.

**Comment by ASerbinski** [comment]
I've been testing these changes, and there is one fairly minor piece missing; when a message is specifically marked as read, it doesn't actually delete the notification. It is necessary to actually exit the conversation and re-enter it in order for the notification(s) to be deleted.

For example to reproduce;

Text chat conversation is open between two users in browsers, User1 sends a message to User2. User1 sees the "single check" mark that the message has been sent, User2 receives a notification (possibly on phone) and the message appears at the bottom of the chat window. User2 scrolls down to read the message, marking it as read, User1 now sees the "double check" mark indicating that the message has been read. The notification received by User2 has **NOT** been dismissed -- it remains.

I believe that the event of marking the message actually as read should also trigger the dismissal of the notification.

Aside from that, this seems perfect to me. I especially like how mobile notifications continue even if the conversation is open in the browser.

**Comment by nickvergessen** [comment]
That's a different issue: https://github.com/nextcloud/spreed/issues/5829
I could only notice it in one-to-one chats yet, but have no fixed reproduction steps which work reliably to reproduce and fix the issue

**Comment by ASerbinski** [comment]
> That's a different issue: #5829 I could only notice it in one-to-one chats yet, but have no fixed reproduction steps which work reliably to reproduce and fix the issue

No, that is not correct. It worked before but was broken by this commit: https://github.com/nextcloud/spreed/pull/1970/commits/6838a7f73a603d406b4cb497b7e6221404eaf97a

**Comment by nickvergessen** [comment]
But that commit is not merged, this Pull Request is still open :P

**Comment by ASerbinski** [comment]
> But that commit is not merged, this Pull Request is still open :P

Yes, that commit is part of THIS PR, which is obviously why I am commenting on it here.

**Comment by theoneandonly-vector** [comment]
```nickvergessen added this to the 💚 Next Major milestone on 9 Jul 2019```
any ETA?

**Comment by Smith-fms** [comment]
> Needs re-thinking. Always sending push notifications even when the user is active in a mobile app will generate a weird user experience.

I confirm, its annoying.... There really is room for improvement.

**Comment by theoneandonly-vector** [comment]
Getting the message everywhere is better than nowhere

**Comment by DaleJP** [comment]
I'm really sorry to muddy this thread with something everybody probably knows, but how do I apply this fix? Or at least if someone can give me the search terms to find how to do it. I've been told this could fix my notification problems with Nextcloud Talk and I can't see an obvious way to install it.
I am brand new to github other than for looking at the readme for installation.

**Comment by DaleJP** [comment]
Thanks @Marhy172 ,

I'm stuck at the instruction "download the patch" and even then, I'm not 100% sure in which directory to apply the patch when I have the file. 
Do I download using wget https://github.com/nextcloud/spreed/pull/1970.patch to /var/www/nextcloud/spreed/?
Then, do I apply the fix using patch -p 1 < /var/www/nextcloud/spreed/1970.patch"?

**Comment by Marhy172** [comment]
First of all, I am amateur myself. I use Nextcloud on Raspberry Pi to learn more about internet, networks, Linux, etc. I use dd to backup whole system whenever I make changes I don't fully understand. So consider yourself if it worth to you to follow my steps :) I did it like this:

* downloaded patch to home folder using wget as you (for example /my/home/folder)
* went to root folder of spreed app (probably cd /var/www/nextcloud/apps/spreed/ in yours case?)
* applied downloaded patch from my home folder: patch -p 1 < /my/home/folder/1970.patch

As I written. I had an error while applying the patch like this. So I am not sure if this is the right way to do it for this patch. But it seems notifications works for me and my friends now. Maybe wait if someone more educated answers you :)

**Pull request closed without merging**
