### PR TITLE
fix spelling of "most likely" in multiple files

### PR DESCRIPTION
**Pull request by meonkeys**

### CODE REVIEW

**Review by nickvergessen — CHANGES_REQUESTED** [review]
l10n/ Folder should not be modified. It's handled by transifex

**Comment by meonkeys** [comment]
> l10n/ Folder should not be modified. It's handled by transifex

Ah, thank you @nickvergessen ! I'll remove `l10n/` changes from my PR.

I'm worried only changing `src/components/AdminSettings/TurnServers.vue` will break the linkage with the existing translations... or is this what you prefer?

I created a transifex account in case I need one.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Yeah translations will break, but the old one is still there so they can copy it from there

**Pull request merged**
