### PR TITLE
Disable use of deprecated "Plan-B" semantics if HPB is used.

### LINKED ISSUE #3790: Plan-b is unsupported in Firefox 77.0.1+
## Steps to reproduce
1. Start a call with the HPB with Firefox 77.0.1

### Expected behaviour
:heavy_check_mark: works

### Actual behaviour
:warning: Warning in browser console:
```
WebRTC: Outdated and non-standard {sdpSemantics: "plan-b"} is not supported! WebRTC may be unreliable. Please update code to follow standard "unified-plan".
```

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 19.10

**Browser name:** Firefox

**Browser version:** 77.0.1

### Browser log

<details>
```
WebRTC: Outdated and non-standard {sdpSemantics: "plan-b"} is not supported! WebRTC may be unreliable. Please update code to follow standard "unified-plan".
```
</details>

## Talk app

**Talk app version:** 9.0.1

**Custom TURN server configured:** yes, coturn

**Custom STUN server configured:** no

**HPB:** 0.0.12-1~ubuntu18.04

### PR DESCRIPTION
**Pull request by fancycode**
Only tested with two browsers on Linux, should be also tested between on different OS and browser and mobile apps (cc @Ivansss).

Fixes #3790

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Tested with Firefox, Chromium and Safari

**Comment by danxuliu** [comment]
[In Chromium 96 _plan-b_ semantics will be finally removed](https://bugs.chromium.org/p/chromium/issues/detail?id=857004), and trying to use them will throw a warning and make the connection fail. This can be seen already by launching Chromium 95 with the command line argument `--enable-features=RTCDisallowPlanBOutsideDeprecationTrial` and starting a call in Talk 11 or older; browser console will show `Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported.`. Therefore, this pull request should be backported to at least Talk 11 (Talk 10 might be end of life when Chromium 96 is published).

Regarding older Chromium versions unified plan and plan-b semantics should be compatible as long as a single media track of each kind is used; this should be the case in Talk 10 and 11, as screen shares use their own independent connection and simulcast was not introduced until Talk 12. Therefore, even if _plan-b_ is not enforced this should not be a problem in older Chromium versions (<72); calls in Chromium 68 indeed work, Chromium 62 does not even load Talk UI due to invalid JavaScript :shrug:

Chromium 72, which was the first version in which _unified plan_ was enabled by default in Chromium and [the original reason to still force _plan-b_ due to incompatibilities back then with the HPB](https://github.com/nextcloud/spreed/pull/1582), works fine with Janus 0.11.3 and _unified plan_.

**Comment by nickvergessen** [comment]
> Therefore, even if plan-b is not enforced this should not be a problem in older Chromium versions (<72); calls in Chromium 68 indeed work, Chromium 62 does not even load Talk UI due to invalid JavaScript shrug

Only the last 2 browser versions in time of the release for each browser are supported.

**Pull request merged**
