### PR TITLE
Implement password policy checker

### LINKED ISSUE #3089: Enforce password policy for shared links
The password policy under Administration/Security is not applied on shared links in talk.
image

Since it is a general security setting (and not only for sharing files), it should apply to every shared link including talk rooms. 

**Describe the solution you'd like**
1) The password field in talk should respect the settings in Administration/Security/Password policy
image

2) There should be an option (like in Administration/Sharing) to enforce password protection for talk conversations. This would prevent users from creating rooms without a password.
image

3)  People invited by mail should get a second e-mail with a custom password for this talk conversation (like sharing via mail). 
image

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #3089

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Noticed two things

1. I can't remove a password which was correctly set anymore (GUI reflects a removed password):

https://user-images.githubusercontent.com/1580193/173200095-8626bb2f-d5f0-4f6c-998f-93876f412c44.mp4

3. When the password validation fails, the GUI still reflects a successful change:

https://user-images.githubusercontent.com/1580193/173200147-61f93d43-3eb4-46a6-9470-6f421e3a020b.mp4

**Comment by SystemKeeper** [comment]
3. Conversation is still created, although an error occured:


https://user-images.githubusercontent.com/1580193/173200683-4efa80d9-e246-4ebb-9ae5-c46a8217deeb.mp4

**Comment by nickvergessen** [comment]
Yeah noticed too that there are many issues with the field.
Also when you open the settings and the conversation has a password already, the input is not visible 🙈

**Comment by nickvergessen** [comment]
> Conversation is still created, although an error occured:

That is actually a sad issue, as we currently set the password after the creation. Basically boils down to:
https://github.com/nextcloud/spreed/issues/2874

**Comment by SystemKeeper** [comment]
Oh I see. Then this problem is out of scope for this PR and currently expected.

**Comment by nickvergessen** [comment]
Or we use this moment to implement it

**Review by vitormattos — APPROVED** [review]

**Review by vitormattos — CHANGES_REQUESTED** [review]
Only need fix cs

**Comment by nickvergessen** [comment]
> Also when you open the settings and the conversation has a password already, the input is not visible :see_no_evil:

@marcoambrosini maybe you can help with the missing input field?

**Comment by SystemKeeper** [comment]
Haven’t tested, but isn’t there special handling for removing the password (eg setting the password to „“) needed?

**Comment by nickvergessen** [comment]
I had wrapped the event dispatch in an if checking for non empty string.... But seems it got removed by a rebase or something

**Review by vitormattos — APPROVED** [review]

**Pull request merged**
