### PR TITLE
fix: Fix some minor things found by stan

### PR DESCRIPTION
**Pull request by nickvergessen**
### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Error: lib/Chat/MessageParser.php:0:0: UnusedBaselineEntry: Baseline for issue "UndefinedVariable" has 1 extra entry.

haha oops

**Review by danxuliu — APPROVED** [review]

**Pull request merged**
