### PR TITLE
Wrap rooms creation in transaction

### PR DESCRIPTION
**Pull request by tcitworld**
### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by nickvergessen** [comment]
Why is that? There is no benefit from a transaction over a single query.

**Comment by tcitworld** [comment]
Yup, it's a read-after-write issue. I thought the read was there for a good reason, but I can change that to try and reconstruct the object.

**Comment by nickvergessen** [comment]
We are currently heavily changing the affected code. Maybe you do a PR with a transaction for stable25 if it is having a real world negative impact at the moment on live servers, and we afterwards fix it properly for 26+ with direct construction of the object.
Can you raise a ticket for it, so we don't forget to track it?

**Comment by nickvergessen** [comment]
Master part is now in #8520

**Comment by nickvergessen** [comment]
25 rebased in https://github.com/nextcloud/spreed/pull/8531

**Pull request closed without merging**
