### PR TITLE
Keyboard navigation for conversation search

### LINKED ISSUE #2816: Hitting enter on a search should select the first entry
Applicable to:
* Conversations filter/creating
* User list on conversation creation
* Participants filter/adding

Found myself trying that all the time when i populated my 19 dev environment today.

Cc @nextcloud/designers-talk 
Also works like that e.g. here on github.

### PR DESCRIPTION
**Pull request by nickvergessen**
I was unable to manage a "fake hover" state which I guess should then also be keyboard navigateable.
But at least I got enter to work 😬

Fix #2816

### CODE REVIEW

**Comment by nickvergessen** [comment]
Now works based on the unified search focus functions. We have the mixin here locally until it's merged in the vue lib.

**Review by ma12-co — COMMENTED** [review]
The keyboard navigation is not working for me

**Comment by nickvergessen** [comment]
Did you forget to build? it works very fine here.

**Comment by ma12-co** [comment]
let me retry :)

**Review by ma12-co — APPROVED** [review]

**Pull request merged**
