### PR TITLE
Fix the background job checking the schema

### LINKED ISSUE #5336: CheckReferenceIdColumn: must be instance of OC\DB\Connection
Talk 11.1.0
NC 21.0.0.18

In Nextcloud log when the cronjob is run:
> Argument 1 passed to OC\\DB\\SchemaWrapper::__construct() must be an instance of OC\\DB\\Connection, instance of OC\\DB\\ConnectionAdapter given, called in /var/www/nextcloud/apps/spreed/lib/BackgroundJob/CheckReferenceIdColumn.php on line 59

<details>

```
{
  "Exception": "TypeError",
  "Message": "Argument 1 passed to OC\\DB\\SchemaWrapper::__construct() must be an instance of OC\\DB\\Connection, instance of OC\\DB\\ConnectionAdapter given, called in /var/www/nextcloud/apps/spreed/lib/BackgroundJob/CheckReferenceIdColumn.php on line 59",
  "Code": 0,
  "Trace": [
    {
      "file": "/var/www/nextcloud/apps/spreed/lib/BackgroundJob/CheckReferenceIdColumn.php",
      "line": 59,
      "function": "__construct",
      "class": "OC\\DB\\SchemaWrapper",
      "type": "->",
      "args": [
        {
          "__class__": "OC\\DB\\ConnectionAdapter"
        }
      ]
    },
    {
      "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
      "line": 80,
      "function": "run",
      "class": "OCA\\Talk\\BackgroundJob\\CheckReferenceIdColumn",
      "type": "->",
      "args": [
        null
      ]
    },
    {
      "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
      "line": 61,
      "function": "execute",
      "class": "OCP\\BackgroundJob\\Job",
      "type": "->",
      "args": [
        {
          "__class__": "OC\\BackgroundJob\\JobList"
        },
        {
          "__class__": "OC\\Log"
        }
      ]
    },
    {
      "file": "/var/www/nextcloud/cron.php",
      "line": 128,
      "function": "execute",
      "class": "OCP\\BackgroundJob\\TimedJob",
      "type": "->",
      "args": [
        {
          "__class__": "OC\\BackgroundJob\\JobList"
        },
        {
          "__class__": "OC\\Log"
        }
      ]
    }
  ],
  "File": "/var/www/nextcloud/lib/private/DB/SchemaWrapper.php",
  "Line": 41,
  "CustomMessage": "--"
}
```
</details>

When looking at the server, it actually passes a `Connection` to the `SchemaWrapper`, see [here](https://github.com/nextcloud/server/blob/5db40a37a14705f9d145a1262f06d6998da9e838/core/Command/Db/AddMissingColumns.php#L54-L59)

In `CheckReferenceIdColumn` it's a IDBConnection:
https://github.com/nextcloud/spreed/blob/768258ccdc111ce33da3f448feafb934fb483bcc/lib/BackgroundJob/CheckReferenceIdColumn.php#L47-L56

I think the commit [here](https://github.com/nextcloud/server/commit/8b64e92b9262d2a2eec6345685ce421050f95c66#diff-b868f3fc169b78b9222fb4822eba2940dc6eccb4b8ea9df464366be45f059ef8) could be related?

Reported by Jani21 [here](https://help.nextcloud.com/t/nc-21-keine-talk-push-bei-1-1-vermutlich-cron-problem/109992) and seeing this myself

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5336

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by nickvergessen** [comment]
meh, psalm

**Comment by nickvergessen** [comment]
added an ignore on the inner and bumped the package to fix unrelated things I got reported locally.

**Comment by PVince81** [comment]
restarted build

**Pull request merged**
