### PR TITLE
Move conversation menu options to a dialog

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/nextcloud/spreed/issues/4007

- [x] REQUIRES: release of nextcloud-vue with [scroll container fix](https://github.com/nextcloud/nextcloud-vue/pull/1573)

### Current state

See https://github.com/nextcloud/spreed/pull/4576#issuecomment-731219492

### Old state from first attempt

image

image

### Tasks

- [x] move sharing settings
- [x] add/copy "copy link" also to the settings tab
- [x] move lobby settings to settings tab
- [x] move SIP options to settings tab
- ~~remove lobby + locking panels while in call~~
- [ ] disable locking checkbox while in a call => will do separately in https://github.com/nextcloud/spreed/pull/4671
- [x] improve design
- [x] add more hints

### Tests

- [x] retest permissions and switches
   - [x] owner/moderator
   - [x] guest moderator
   - [x] non-moderator

### CODE REVIEW

**Comment by PVince81** [comment]
See screenshot above for the current state.

- I've used the "Action*" components as they look nice and align well, I hope I can keep them as I don't want to juggle with "regular" elements.

- It seems it's getting crowded quickly, should we move the sections to separate tabs ?

@nextcloud/designers-talk

**Review by ma12-co — COMMENTED** [review]
I'd suggest using the AppSettingsDialog vue component for conversation settings too, and get rid of the sidebar settings tab!

**Comment by PVince81** [comment]
Now it's in a dialog:
image

- [ ] TODO: in that context I think we can remove "Copy link"
- [ ] BUG: when clicking on "Moderation settings" the dialog scrolls down permanently despite being no scrollbar! Probably a bug in the original component :-/
- [ ] Make toast notification visible on top of the modal / background.

**Comment by PVince81** [comment]
it seems something is wrong with the app settings component, it doesn't scroll properly:
image

@ma12-co I didn't add any CSS, shouldn't the dialog work out of the box ?

**Comment by PVince81** [comment]
@ma12-co can you have a look at the scrollbar thing ?

**Comment by PVince81** [comment]
here's a fix for the scrollbar issue: https://github.com/nextcloud/nextcloud-vue/pull/1573

**Comment by PVince81** [comment]
@ma12-co as discussed, I've added some text hints.

As advised by @nickvergessen I've merged the SIP section into the moderation one.

Now it seems that with only two sections, the left navigation bar is redundant so maybe we can disable it for this dialog.

Let me know what you think.

**Comment by nickvergessen** [comment]
Mind to update the screenshot in the first post?

**Comment by PVince81** [comment]
screenshots updated.

**Comment by PVince81** [comment]
- [ ] try renaming the moderation section to "Meeting settings"

**Comment by PVince81** [comment]
I've removed all the Action* and replaced them with plain old HTML elements, but following a similar structure.

New WIP state:

image

image

- [ ] fix margins/paddings
- [ ] fix DatePicker visually broken
- [ ] submit button a bit shifted

**Comment by PVince81** [comment]
- [ ] properly reset checkboxes to their previous values in case of error (see https://github.com/nextcloud/spreed/pull/4576/commits/176a099d0beb3ab6e2f9771fc65f093ff10340e7 for a possible approach to use for all)

**Comment by PVince81** [comment]
Rebased.

And I've split error handling and special cases which did not exist before to a follow up PR: https://github.com/nextcloud/spreed/pull/4671

I'd like to already merge this PR here as it's the same functionality as before but moved to the dialog.

**Comment by PVince81** [comment]
hmmm, still requires a release of nextcloud-vue for https://github.com/nextcloud/nextcloud-vue/pull/1573

when I tested I had nextcloud-vue master linked

**Comment by PVince81** [comment]
nextcloud-vue update here https://github.com/nextcloud/spreed/pull/4680, it will take a bit longer as we need to adjust some components affected by the update

**Comment by nickvergessen** [comment]
vue update is in

**Comment by PVince81** [comment]
Rebased and did a quick retest.

One difference from before the rebase is that now the SIP checkbox has a condition for displaying.
To make it appear you need to fill in all the fields in the SIP section in the admin settings for Talk.

**Comment by PVince81** [comment]
ready to review :-)

**Comment by PVince81** [comment]
restarted CI

**Review by ma12-co — APPROVED** [review]

**Comment by nickvergessen** [comment]
Merged too early...

The SIP changes were not merged and they need a backport

**Comment by PVince81** [comment]
I'm fine reverting and rebasing later.

seems there's only a conflict in top bar markup, this line https://github.com/nextcloud/spreed/pull/4689/files#diff-841f2c9a1004d8fafe1e1f6fe44412b062860ea277a4ddc071068f7f2a162e7dR146

**Comment by nickvergessen** [comment]
"only", its not an ActioItem anymore :P

**Comment by PVince81** [comment]
here we go, the revert PR: https://github.com/nextcloud/spreed/pull/4701

**Pull request merged**
