### PR TITLE
Add notes about OCS-APIRequest header requirement

### PR DESCRIPTION
**Pull request by aaronsegura**
Signed-off-by: Aaron Segura <aaron@aaronsegura.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
We can of course add it in Talk in all places, but I think that should be covered in the general section of the dev docs:
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html#testing-requests-with-curl

**Comment by nickvergessen** [comment]
The JSON requirement however should go into our docs (XML is broken and can not send some of the data structures we have)

**Comment by nickvergessen** [comment]
So fine for me if we want to do this

**Comment by nickvergessen** [comment]
@aaronsegura you want to extend this?

**Comment by aaronsegura** [comment]
@nickvergessen Sorry, I'm not sure what you're asking of me.  Do you mean to add more info about the JSON requirement and OCS-APIRequest header in the general section?  I can do that, but I won't be able to get to it until next week.  Currently traveling.

**Comment by nickvergessen** [comment]
Added it in the last commit of https://github.com/nextcloud/spreed/pull/7505

**Comment by aaronsegura** [comment]
@nickvergessen  I don't see anything about the OCS-APIRequest header requirement in #7505.  That it is a requirement isn't very clearly explained in the general section of the dev docs.  The requirement *is* explained on other seemingly random pages [[example]](https://docs.nextcloud.com/server/24/developer_manual/client_apis/OCS/ocs-status-api.html) [[example]](https://docs.nextcloud.com/server/20/developer_manual/client_apis/OCS/ocs-share-api.html), but is never explained anywhere in the Talk API documentation that I could find.

**Comment by nickvergessen** [comment]
Yeah, but it basically applies to all client apis so maybe it should be added to https://docs.nextcloud.com/server/24/developer_manual/client_apis/OCS/index.html

**Pull request closed without merging**
