### PR TITLE
Don't trimm displayname in selection

### LINKED ISSUE #3888: First name not shown correctly on invitation box
## Steps to reproduce
1. Set up NC19 with LDAP and users that have name prefixes (such as Dr. Simon King)
2. Invite them to your chat

### Expected behaviour
The bubble with the first name should appear

### Actual behaviour
the bubble appears, as first name it shows "Dr."
bug

I opened up a ticket on server that first name and last name should be pulled as seperate LDAP attributes, see nextcloud/server#21762. This will also help to solve this issue.
## Talk app

**Talk app version:** 9.0.1

## Server configuration

**Nextcloud Version:** 19.0.0

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #3888

### CODE REVIEW

**Comment by nickvergessen** [comment]
Right, no backport to 18, this is new in 19

**Comment by ma12-co** [comment]
We need to find a better solution here

Screenshot from 2020-07-24 14-01-06

**Comment by johkoenig** [comment]
@ma12-co please file a bug report. This is not the right place.

**Pull request merged**
