### PR TITLE
Fixes for keyboard navigation

### PR DESCRIPTION
**Pull request by danxuliu**
Draft until #2117 is merged (first commit of this pull request is _Do not select again an already selected tab_)

"Requires" (that is, the password button works better with) nextcloud/server#16863

This pull request fixes several elements not being focusable (or being focusable when they should not be) or highlighted when focused:
- Tab headers in the sidebar
- Select2 containers (_Add participant_ and _New conversation..._)
- _Copy link_ and password buttons
- Edit button in room name and guest name
- Sidebar trigger
- Participants in the _Participants_ tab of the sidebar

This can be tested by navigating through the main Talk UI by pressing tab and checking that
- the items are properly highlighted when focused
- pressing Enter or space when an element is focused triggers the action associated to that element

Some things to keep in mind:
- The link element in the tab header should be changed to a _span_, but I kept it as a link for now [to be closer to the server](https://github.com/nextcloud/spreed/issues/1390).
- When a Select2 list is open pressing tab adds the current item instead of changing to the next element. However, note that the Select2 list can be closed by pressing _Esc_ and then pressing tab works as expected.
- When pressing enter on the _Copy link_ button the focus is lost; this seems to be caused by the tooltip changing the parent element when shown or something like that, but I have not investigated it.
- After focusing the edit button in room name or guest name pressing Enter shows the input. However, if Enter is kept pressed it shows and hides the input again and again. Unfortunately the browsers constantly trigger _keydown_ and _keyup_ events when a key is kept pressed, so once the input is shown that elements receives the repeated Enter _keyup_ events; theoretically the _repeat_ property should be set on the event to make possible to distinguish it, but in practice it seems that is is not set, so this can not be detected nor handled (or, at least, I could not find how to do it ;-) ).
- The tab order can still be improved, as the button to show the sidebar and the button to enable fullscreen are not navigated one after the other (due to their position in the DOM). However that involves a deeper change and I did not want to mess with explicit tab order, so for now I left it as is.
- I have not enabled keyboard navigation on the avatars or mentions in the chat view to trigger the contacts menu, as I think that would make the navigation much slower for little gain (as the contacts menu can be triggered from the participants list)
- The message list in the chat view is not highlighted when focused (focusing it allows to scroll using the keyboard); maybe it would be good to add a dashed border or something like that, but only if it was focused with keyboard navigation and not by clicking on the list. Probably this could be accomplished by tweaking [this _Keyboard-Only focus_ technique](https://www.kizu.ru/keyboard-only-focus/) (StackOverflow has [a nice summary](https://stackoverflow.com/questions/31402576/enable-focus-only-on-keyboard-use-or-tab-press/45191208#45191208)), but it may need some JavaScript too to redirect the key events from the wrapper to the message list itself. In any case... that type of highlighting of scrollable elements it not widespread as far as I know, so for the time being I left it as is.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Is this required for the lobby PR? Doesn't look like

**Comment by danxuliu** [comment]
It is.

I have rebased but cancelled the Drone job (it would have passed, as the changes in master did not affect this pull request) as well as removed the call to backport bot for now.

**Comment by nickvergessen** [comment]
Works surprisingly well. It's only weird that when the participant/room list reloads you have to start at the top again when you where in that sector.

**Comment by danxuliu** [comment]
> It's only weird that when the participant/room list reloads you have to start at the top again when you where in that sector.

Right, it is caused by rendering the views again; the element with the focus is removed, so the browser moves the focus back to the closest parent. It happens too in the `CallInfoView` when the room type changes and things like that. Could be fixed, yes, but... well, future ;-)

**Pull request merged**
