### PR TITLE
Prevent infinite loop in datachannel open re-transmission

### LINKED ISSUE #3819: Infinite loop while re-sending pending DataChannel messages
Sometimes when the joining/initiating a call the browser freezes.
I was able to narrow it down to a "bad" data channel readyState ("connecting") in peer.js when onopen callback is called and there are pending messages for the channel. What happens is that during the re-transmission in sendDirectly the check for opened channel is failing and the message is queue in the pending messages. Which causes a new iteration on the loop with the "new" message, which is again queued, and so on.

I did a quick change adding a check to prevent re-transmission of pending messages when the datachannel readyState is not "open" (see https://github.com/vhristov/spreed/commit/3c9e4c97745e19e36021314500b256c0523bbd0f), but I am not sure what are the side effects of it. So far for the last few days it seems to be working on my side without any issues observed. Calls seems to be working properly, without a need to mute/unmute (which was necessary when I simply commented out the re-send code).

## Steps to reproduce
Connect to a call with someone

### Expected behaviour
Call works

### Actual behaviour
Browser tab sometimes freezes 

## Talk app

**Talk app version:** 
9.0.0, 9.0.1, latest stable19

**Custom Signaling server configured:** 
I have seen the issue on both internal signaling and recently opensourced version of HPB (both with and without MCU)

**Custom TURN server configured:** 
I have seen the issue both with and without turn (local calls and remotes)
**Custom STUN server configured:** 
yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** 
both Windows 10 and Ubuntu 20.04

**Browser name:**
Chrome Version 81.0.4044.129 on Ubuntu
Latest Chrome on Windows (not exactly sure of the version)
I believe i have also seen the issue on firefox but not 100% sure.

**Browser version:** 
(see above)

### Browser log
Added extra logging in the peer.js in "channel.onopen":
```
const dc = self.getDataChannel(channel)
window['console'].log('channel onopen channel: ', channel.label, 'status: ', dc.readyState)
```
I observe the following:

```
webrtc.js:832 status datachannel is open
peer.js:321 channel onopen channel:  status status:  connecting
webrtc.js:832 simplewebrtc datachannel is open
peer.js:321 channel onopen channel:  simplewebrtc status:  connecting
webrtc.js:832 [object RTCDataChannel] datachannel is open
peer.js:321 channel onopen channel:  [object RTCDataChannel] status:  open
```
(the log is collected with the commit mentioned above, otherwise there is no way to get it)

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache with Nginx ingress SSL termination

**Database:** PostgreSQL 11.8

**PHP version:** 7.4

**Nextcloud Version:** 19.01

**List of activated apps:**

<details>

```

  - accessibility: 1.5.0
  - activity: 2.12.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - metadata: 0.11.1
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.2.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
```

</details>

**Nextcloud configuration:**

<details>

```

{
    "system": {
        "trashbin_retention_obligation": "30, 60",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Movie"
        ],
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.com",
            "192.168.1.0\/8",
            "10.0.0.0\/24",
            "*"
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/domain.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "spreed"
        ],
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

```
</details>

### Server log (data/nextcloud.log)
Nothing of interesting

### PR DESCRIPTION
**Pull request by vhristov**
fix #3819

### CODE REVIEW

**Comment by nickvergessen** [comment]
For me thisshows the avatar now instead of the video until I toggle the camera state twice.

**Comment by vhristov** [comment]
While I was unable to reproduce the issue with no video, I am pretty confident I might have an idea what could be the root cause.
My initial assumption that I get a second onopen called when the readyState changed is just wrong... This could cause the stream start commands to be not sent.

I can see a few possible solutions to resolve the issue:
1. Blindly re-send the queue when onopen is called - here I assume that the data connection should have been established
2. Do one setTimeout and resend there - assuming the connection state is updated just after the call 
3. Do a setTimout/setInterval and poll on the readyState between onopen and onclose (or queue is empty) and do the resend if the readyState is opened.

I think my personal preference goes to number "3"
What do you say?

**Comment by nickvergessen** [comment]
@danxuliu any opinion on those 3 suggestions?

**Review by danxuliu — COMMENTED** [review]
@vhristov Sorry for the delay, and thanks a lot for the detailed description.

I think that I found what is going on. The problem is that both ends open a data channel with the same name, and when the data channel from the remote end is received [it overwrites the variable that holds the local data channel](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L470). Events from both data channels are still listened to, so if the local data channel is then opened the handler will still work and [the pending messages will be tried to be sent](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L304-L314). However, the stored data channel will be the remote data channel rather than the local one. If the remote data channel is not opened yet then [the messages will be enqueued again](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L284-L291). But `sendDirectly` pushes to the same array read by the `onopen` handler, which causes an infinite loop.

With all this I would like to propose another way of fixing the issue :-)

Instead of [iterating through the "live" list of pending messages](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L308-L312) I would copy it, clear it, and then try to send the pending messages:
```
const pendingMessages = self.pendingDCMessages[channel.label].slice()
self.pendingDCMessages[channel.label] = []
for (let i = 0; i < pendingMessages.length; i++) {
	self.sendDirectly(channel.label, pendingMessages[i].type, pendingMessages[i].payload)
}
```

With this change if the data channel that was opened is the same that is stored in `this.channels[channel.name]` the messages will be sent. If not (that is, if the local data channel was opened but the remote one is the one stored in `this.channels[channel.name]`) then the messages will be either sent (if the remote data channel is already open) or enqueued again and sent once the remote data channel is opened. As the other end listens to messages on both the local and remote data channels (this applies not only to the web UI, but also to the [Android](https://github.com/nextcloud/talk-android/blob/1053ccde64437e853728e5f06f483e3c3b428359/app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.kt#L161) and [iOS](https://github.com/nextcloud/talk-ios/blob/de36d265bf8c0fc81a5ce533d9e404e7b0799a4b/VideoCalls/NCPeerConnection.m#L253) apps) it would not matter on which data channel they are sent.

Alternatively I think that it could be fixed too by not overwritting the local data channel with the remote one, but given that it has been working like that since forever I would rather address the infinite loop itself.

Finally, the reason that your change did not work as expected is that `getDataChannel` expects the channel name, but in `const dc = self.getDataChannel(channel)` a channel object was given. Due to this a new data channel with label `[object RTCDataChannel]` was created and that was the one being checked rather than the actual opened data channel :-)

Therefore using `const dc = self.getDataChannel(channel.label)` will probably work too, although personally I would prefer to just split the iteration on the array from its modification as mentioned above (given that `getDataChannel` does more things than just getting the data channel, like creating it if it does not exist).

Sorry again for the delay. And, by the way, I loved the detailed commit message :-)

**Comment by vhristov** [comment]
Updated the pull request with the proposed changed.

> I think that I found what is going on. The problem is that both ends open a data channel with the same name, and when the data channel from the remote end is received [it overwrites the variable that holds the local data channel](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L470). Events from both data channels are still listened to, so if the local data channel is then opened the handler will still work and [the pending messages will be tried to be sent](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L304-L314). However, the stored data channel will be the remote data channel rather than the local one. If the remote data channel is not opened yet then [the messages will be enqueued again](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L284-L291). But `sendDirectly` pushes to the same array read by the `onopen` handler, which causes an infinite loop.

If we have something like this:
flow
- At *t0* local-to-remote connection is created
- At *t1* we become aware of remote-to-local connection and the channel is overwritten
- At *t2* we get onopen for local-to-remote
- At *t3* remote-to-local becomes connected

If I understand correctly when t2 is between t1 and t3 the infinite loop will happen?

> With all this I would like to propose another way of fixing the issue :-)
> 
> Instead of [iterating through the "live" list of pending messages](https://github.com/nextcloud/spreed/blob/64c0b7e18d7485cf58c672f5d08055498d7f1f0c/src/utils/webrtc/simplewebrtc/peer.js#L308-L312) I would copy it, clear it, and then try to send the pending messages:
> 
> ```
> const pendingMessages = self.pendingDCMessages[channel.label].slice()
> self.pendingDCMessages[channel.label] = []
> for (let i = 0; i < pendingMessages.length; i++) {
> 	self.sendDirectly(channel.label, pendingMessages[i].type, pendingMessages[i].payload)
> }
> ```
I created a quick change yesterday and tested with this proposal and it seems to not cause any issue with an infinite loop. 


> Alternatively I think that it could be fixed too by not overwritting the local data channel with the remote one, but given that it has been working like that since forever I would rather address the infinite loop itself.
I personally would not like such a risky change :)

> Finally, the reason that your change did not work as expected is that `getDataChannel` expects the channel name, but in `const dc = self.getDataChannel(channel)` a channel object was given. Due to this a new data channel with label `[object RTCDataChannel]` was created and that was the one being checked rather than the actual opened data channel :-)
Ooops...
> Therefore using `const dc = self.getDataChannel(channel.label)` will probably work too, although personally I would prefer to just split the iteration on the array from its modification as mentioned above (given that `getDataChannel` does more things than just getting the data channel, like creating it if it does not exist).
I went to the route of copy the queue. This way it seems to me it could be a bit more robust.

> Sorry again for the delay. And, by the way, I loved the detailed commit message :-)
Thank you

**Comment by danxuliu** [comment]
> Updated the pull request with the proposed changed.

Thanks!

> If I understand correctly when t2 is between t1 and t3 the infinite loop will happen?

Exactly.

> I personally would not like such a risky change :)

Glad that we agree :-)

> I went to the route of copy the queue. This way it seems to me it could be a bit more robust.

And again ;-)

**Review by danxuliu — APPROVED** [review]
Tested* and works :+1: And a detailed commit message again :heart:

*I added logs to ensure that I was testing the scenario that caused the infinite loop before ;-)

Thanks a lot @vhristov! :-)

**Pull request merged**
