### PR TITLE
add karma/jasmine config for js unit testing

### PR DESCRIPTION
**Pull request by ChristophWurst**
can be run via ``node_modules/karma/bin/karma start``. Can we add that to drone too? cc @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
> can be run via node_modules/karma/bin/karma start. Can we add that to drone too? cc @LukasReschke

Sure. Let me take care of that later. Can you fix the eslint stuff or add it to the exclude? :)

**Comment by LukasReschke** [comment]
@ChristophWurst No idea what is going on here. Can you check https://drone.nextcloud.com/nextcloud/spreed/34/10? https://github.com/nextcloud/spreed/pull/54/commits/41628111e0b3fb0550a61dec860e450d03e609a0 is the code that is responsible for that.

**Comment by ChristophWurst** [comment]
Well, ``/drone/src/github.com/nextcloud/spreed/js`` + ``../../core/vendor/jquery/dist/jquery.js`` becomes ``/drone/src/github.com/core/vendor/jquery/dist/jquery.js`` 💥 

So basically we shouldn't use server's jquery when testing, but load our own.

**Comment by LukasReschke** [comment]
Also: I see that this generates some kind of coverage statistics. Would it be possible to upload that also to Codecov?

Ref https://github.com/karma-runner/karma-coverage 😄

**Comment by ChristophWurst** [comment]
Btw. wouldn't it be sufficient to only run drone for pushes? If we enable it for PRs too it runs twice on PRs, which really is a waste of time and CI power.

**Comment by ChristophWurst** [comment]
Apparently node/npm inside that docker image are pretty old: ``npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})``.

For comparison, I have node v6.8.1 and npm 3.10.8 locally 😨. @LukasReschke any chance to update that?

**Comment by ChristophWurst** [comment]
Yuk! Node/npm on Debian 😨 https://github.com/nextcloud/docker-ci/blob/b188b4392ee03e1bf64188ece5a48a93814e70f7/jsunit/Dockerfile

**Comment by LukasReschke** [comment]
@ChristophWurst Well, if you tell me the commands I have to execute to get a newer NPM inside Debian ;-) - Then we can easily create a new tag of the Docker with the new deps.

**Comment by LukasReschke** [comment]
> Btw. wouldn't it be sufficient to only run drone for pushes? If we enable it for PRs too it runs twice on PRs, which really is a waste of time and CI power.

Required for coverage stuff. Anyways, we'll throw some more hardware against CI which should make this a non-issue.

**Comment by ChristophWurst** [comment]
@LukasReschke https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions should work for our debian image

**Comment by ChristophWurst** [comment]
@LukasReschke it's finally fixed. Please review ;-)

**Comment by ChristophWurst** [comment]
> Also: I see that this generates some kind of coverage statistics. Would it be possible to upload that also to Codecov?

Sure. It's put into `coverage`. The format is adjustable.

**Comment by LukasReschke** [comment]
THX. Merged.

**Pull request merged**
