### PR TITLE
Make background black again

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by PVince81** [comment]
Why ? Screenshots before/after ?

As far as I remember this explicit background was needed for the stripe to not look shitty in some scenarios, perhaps when there are less participants. Maybe recent changes removed the need to have it that way ?

**Comment by nickvergessen** [comment]
> Why?

Because the call screen should be "dark" 

It was introduced by "Add ability to collapse the grid view" (without discussion or comment):
https://github.com/nextcloud/spreed/commit/b885bddae6426e2a841d62f8e909cf6ed0b1e3c3

If this is colored at all, we could use `#444444` like in the empty call view:
https://github.com/nextcloud/spreed/blob/732200a0586dc6df39e29755b15103fe21a5c3e9/src/components/CallView/shared/EmptyCallView.vue#L165

But the current gray is way to light and feels totally out of place


> Screenshots before/after ?

Before | After
---|---
Bildschirmfoto von 2021-01-26 08-52-05 | Bildschirmfoto von 2021-01-26 08-51-57

Before | After
---|---
Bildschirmfoto von 2021-01-26 08-51-38 | Bildschirmfoto von 2021-01-26 08-51-50

**Comment by PVince81** [comment]
in the first set of screenshots the grey background was added to make it clearer that it's a stripe, I think it was a request from @ma12-co 
in grid mode it indeed looks better with black

@ma12-co are you fine with the change above ?

**Comment by nickvergessen** [comment]
Added screenshots of `#444444` above as well

**Comment by ma12-co** [comment]
> I think it was a request from @ma12-co
 
No no :)

I agree that the gray is too light. Out of the 3 screenshots I prefer #444444

**Comment by nickvergessen** [comment]
My only problem with `#444444` is that it's the background of the "promoted placeholder" just without the icon + shadow

**Comment by ma12-co** [comment]
Please change the bkg to the whole callview (first few lines of css in callview.vue)

**Comment by nickvergessen** [comment]
Fixed, ready again

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
