### PR TITLE
Inject MimeTypeLoader into RoomShareProvider to not query it on each …

### PR DESCRIPTION
**Pull request by MorrisJobke**
…createShareObject call

Found during some profiling.

Bildschirmfoto 2020-10-29 um 22 46 17

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Looks fine to me :+1:

**Comment by PVince81** [comment]
ohhhh, failure on master now https://github.com/nextcloud/spreed/actions/runs/341270807

**Comment by PVince81** [comment]
raised as https://github.com/nextcloud/spreed/issues/4512

sometimes I have the feeling that touching some files might wake up Psalm...

**Comment by MorrisJobke** [comment]
> sometimes I have the feeling that touching some files might wake up Psalm...

Most likely because it can now properly infer the type. Before it was only inferable from a private namespace method call? Need to check how server code is injected into psalm inside apps to properly understand this.

**Comment by MorrisJobke** [comment]
> Most likely because it can now properly infer the type. Before it was only inferable from a private namespace method call? Need to check how server code is injected into psalm inside apps to properly understand this.

Ah wait ... this is the mime type loader not the event dispatcher ... then yes: no idea why it is triggered.

**Pull request merged**
