### PR TITLE
Don't try to reconnect the socket when we closed it intentionally

### PR DESCRIPTION
**Pull request by nickvergessen**
Extracted from #3292

### CODE REVIEW

**Comment by nickvergessen** [comment]
Maybe I mixed soemthing up, but the real problem I had which is why I did this was when the connection is terminated because we switch the HPB because of the clustering. But maybe the code works there as well

**Comment by danxuliu** [comment]
Yes, but the commit is covering two different cases: prevent reconnecting when the signaling is disconnected, and prevent reconnecting when the page is about to be unloaded.

As far as I understand it, prevent reconnecting when the signaling is disconnected is what is needed for the HPB clustering. That is OK, and it is not related to my comment. I only refered to prevent reconnecting when the page is about to be unloaded, as I think that could be handled easier just by checking the code from the close event, with no needs for `beforeunload` events, timers and so on.

**Comment by nickvergessen** [comment]
Feel free to add/change it

**Comment by nickvergessen** [comment]
Updated and much less intrusive now!
Thanks for the pointer to the close code @danxuliu

**Comment by nickvergessen** [comment]
The commit `Fix signaling toasts not being permanent ` should be dropped in favor of a rebase since #3449

**Comment by nickvergessen** [comment]
Rebased and dropped it

**Pull request merged**
