### PR TITLE
Fix duplicated audio elements

### PR DESCRIPTION
**Pull request by danxuliu**
This is a regression introduced [during the move of the call view to Vue.js](https://github.com/danxuliu/spreed/commit/56c6aeb1d240716a938af2a40ad1b901be2109d4).

SimpleWebRTC automatically created audio and video elements when a new stream was added. Before the move to Vue.js those elements were the ones used by the views, but it was changed so the views created and managed their own elements. However, although the elements created by SimpleWebRTC were ignored they were still active.

Ironically this turned out to be a feature, because the elements created by the views are destroyed when their view is removed. This happens, for example, when closing the sidebar in the Files app during a call, which stopped the audio being played by the audio element created by the Video view. However, as the audio element created by SimpleWebRTC was not affected by this the audio still played as expected even if there was no Video view.

Now all this has been fixed: the audio element is created by the model instead of the view (so it can play even if there is no view for that participant) and SimpleWebRTC no longer creates audio and video elements.

## How to test
- For easier testing it is recommended to use Firefox' fake streams
- Share a file by link in the Files app
- Copy the link
- Reload the Files app (to be able to join the conversation of the file just shared, required due to a bug in the Files app)
- Join the conversation in the Chat tab for the shared file
- Start a call
- In a private window, open the link to the share
- Join the conversation in the sidebar of the public share page
- Enable the microphone
- Close the sidebar in the Files app

### Result with this pull request
The sound keeps playing at the same volume once the sidebar is closed.

### Result without this pull request
The sound keeps playing once the sidebar is closed, but at a lower volume. If the sidebar is opened again the sound plays at a higher volume. If it is closed it lowers again, and if it is opened it rises again, and...

### CODE REVIEW

**Comment by nickvergessen** [comment]
> ### Result without this pull request
> The sound keeps playing once the sidebar is closed, but at a lower volume. 

I guess it actually is the other way around, so without this PR when the file sidebar is open it is double the volume? Anyway a nice finding

**Comment by danxuliu** [comment]
> I guess it actually is the other way around, so without this PR when the file sidebar is open it is double the volume?

Yes and no. Without this pull request the volume is higher in relation to the volume with this pull request (everywhere, not only in the file sidebar). But with `The sound keeps playing once the sidebar is closed, but at a lower volume` I meant that it was lower in relation to when the sidebar was open also without this pull request.

**Comment by nickvergessen** [comment]
So I tested a bit, and while it seems to work mostly, sometimes the volume still changes heavily.
But I assume it's due to fake streams being monoton, so if you are lucky you get the counter wave of the 2nd signal meaning everything gets more silent, or you stack them, meaning everything gets louder...

**Comment by nickvergessen** [comment]
At least when only one microphone is on, it seems to work much better than without this pr

**Pull request merged**
