### PR TITLE
format app description

### PR DESCRIPTION
**Pull request by jancborchardt**
Markdown like bolding and linking does not work in the app description in the management, makes the entry look strange.

Also I cut the part »And in the works for the [coming versions]« because that makes the entry wayyy too long.

@nickvergessen @Ivansss please review.

### CODE REVIEW

**Comment by nickvergessen** [comment]
This is for the app store and it does support markdown.

The app management page promised to also support it:
https://github.com/nextcloud/server/pull/1594

And I think it's more important that it looks nice on the app store then in the app management. Also tons of other apps also use markdown already, so let's just increase the pressure on nextcloud to fix the parsing to also support markdown in the app management.

**Comment by jancborchardt** [comment]
> let's just increase the pressure on nextcloud

This is not how it works. ;) We _are_ Nextcloud. And we can’t have the description of an advertised app less nice than necessary in the apps management. This is a good middle ground.

Please review @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
I would say that we provide a readable (this PR) for stable versions and go for the server PR with master.

**Comment by jancborchardt** [comment]
We don’t have any stable branch right now, how do we proceed then? How about we merge this now, and I’m happy to change it back as soon as the server capability is there?

**Comment by nickvergessen** [comment]
Has been merged in 12 and will be backported for [11.0.2](https://github.com/nextcloud/server/pull/3117)

So I'm closing this.

**Comment by jancborchardt** [comment]
Yup, nice! :+1:

**Comment by MorrisJobke** [comment]
Looks really nice now:

bildschirmfoto 2017-01-17 um 09 26 44

👍

**Pull request closed without merging**
