### PR TITLE
Always start with disabled media by default

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
@jancborchardt @ma12-co thoughts on this?
We get quite some requests from bigger installations for this, while in the "home" case the old behaviour might be the desired one. I can understand both worlds but don't want to have something like a "this is a big instance" setting, or even a setting per conversation.

**Comment by jancborchardt** [comment]
Yeah, we can do it this way or the other – don't really mind either way. Starting without video always is fine as it preserves bandwidth and privacy.

The real problem is that at the moment there is no way to get a preview of your webcam in the app without also broadcasting it.

**Comment by nickvergessen** [comment]
Then lets do it after https://github.com/nextcloud/nextcloud-browser-storage/pull/2 has a release which breaks the browser storage key values anyway

**Comment by jancborchardt** [comment]
Ah right, just one note: For 1on1 calls, _audio_ should be on by default, right? Otherwise I foresee a lot of confusion and possibly reports about sound not working.

**Comment by ma12-co** [comment]
I don't like this.. I like the current behavior (remembering of the current state) and my Idea for the future was to implement a split button showing the last used option.

59698241-45f45e00-91bd-11e9-8b17-eafd8d0eb7d8


The option in the button would be:

* Join with audio 
* Join with video 
* Join silently
... Or something like that

To satisfy the needs of bigger installation, "silent join" could be enforced by moderators on a per conversation basis in the conversations settings tab (sidebar). But for most people hitting the call button means opening your mic or video if it's a video call. We've had many reports about how counter intuitive the old behavior was.

**Comment by PVince81** [comment]
relates to the "split button" bit of https://github.com/nextcloud/spreed/issues/3270

**Comment by nickvergessen** [comment]
Closing as the split button is not an option.

**Pull request closed without merging**
