### PR TITLE
improved icon choice for moderator promotion

### PR DESCRIPTION
**Pull request by wiswedel**

### CODE REVIEW

**Comment by danxuliu** [comment]
@wiswedel I have made two small changes to your commit:
- recompile the Handlebars templates, as [they were not passing the Drone check](https://drone.nextcloud.com/nextcloud/spreed/2290/1/2) (I guess that you modified them manually; for the record, you can do it automatically with `make compile-handlebars-templates` ;-) )
- change the _promote_ icon from `icon-star-dark` to `icon-star`, as `icon-star-dark` has always the same colour, while [the `icon-start` gets a yellow tint when hovered](https://github.com/nextcloud/server/blob/0cdc671484232ef23b2d77dacaf07a5cb06719b0/core/css/icons.scss#L292).

**Comment by wiswedel** [comment]
>     * I guess that you modified them manually; for the record, you can do it automatically with `make compile-handlebars-templates` ;-) )

@danxuliu Yeah, I didn't know that. Thanks for the hint.

**Comment by wiswedel** [comment]
@danxuliu Can you please help me with that failing test? What do I have to do?

**Comment by danxuliu** [comment]
@wiswedel That test fails sometimes because it takes too long to run, so it reaches the time limit set for Drone jobs and it is aborted. Even if there was an actual failure in that test it would not have been caused by your changes (as they were only style changes and the test is for the sharing APIs), so nothing that you need to worry about ;)

**Comment by wiswedel** [comment]
>  Promote to moderator (Edit pencil): Because it gives the participant edit rights for conversation settings.

Aah. That's what I call thought around the corner ☺️

> But I still think that we need new icons for this feature.

Maybe something like this?
image

**Comment by jancborchardt** [comment]
The biggest issue with it, which still exists, is that the icons are not symmetric. One is a pencil, one is a star. Why not use `icon-edit` for both actions and be done with it? :)

**Comment by Ivansss** [comment]
> Why not use icon-edit for both actions and be done with it? :)

That's what we have on the iOS app. We use icon-edit for both options.
Let's do the same here for consistency then.

But I don't see any problem on adding a different icon for this particular Talk feature.
Something like @wiswedel suggested in https://github.com/nextcloud/spreed/pull/1843#issuecomment-496223325

Or something like this:
Screen Shot 2019-05-29 at 12 52 28

**Pull request merged**
