### PR TITLE
fix(NewMessage): typing indicator alignment for wide screens

### LINKED ISSUE #12466: TypingIndicator misaligned when screen is too wide
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

image

seen with Safari 17.5 in master

### PR DESCRIPTION
**Pull request by sanskar-soni-9**
### ☑️ Resolves

* Fix #12466 

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
240613_09h49m00s_screenshot | 240613_09h06m05s_screenshot

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by Antreesy** [comment]
Might be only for Next Major (30), since I changed the chat width for wide screens here. Will try to check soon, thanks

**Review by Antreesy — APPROVED** [review]
Decent solution, tested with different width.

Could be a bit complicated to backport it to recent version, but we'll try to

**Review by DorraJaouad — APPROVED** [review]
Nice workaround

**Comment by nickvergessen** [comment]
I thought its main only?

**Comment by Antreesy** [comment]
> I thought its main only?

Posted a screenshot from stable29. Not that critical though

**Pull request merged**
