### PR TITLE
Notification levels

### LINKED ISSUE #1099: Option for notification levels
The levels should be:
* Always (default for one2one rooms)
* On mention (default for other rooms?)
* Never

Maybe even "Temporary mute" (1h, 8h, 24h, 1 week seem to be most common)

Basically a follow up to #875

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1099 

- [x] Add DB + model change
- [x] Add endpoint
- [x] Respect the setting
- [x] Add UI to change the setting

### CODE REVIEW

**Comment by fsxadmin** [comment]
oooo we are so excited! please make this happen for the major release, thank you! After this, we will consider the enterprise licensing

**Comment by nickvergessen** [comment]
@jancborchardt currently we go for 3 options:
* Never notify
* On mention
* Always

where/how should users be able to set this? In the `…` menu of the conversation list? Or the right sidebar top section? 

Additionally, should we show something similar to the grey mute icon Whatapp and others are showing when a conversation is set to "never"?
screenshot_20181005-163735

**Comment by fsxadmin** [comment]
fo9r sure in the ... shown here: 
image

**Comment by fsxadmin** [comment]
Thanks for your diligence @nickvergessen !!

**Comment by nickvergessen** [comment]
Ready for review. I also think that the dropdown menu is the right place, since it also handles the favorite state, so it looks like the following screenshot for now:

> bildschirmfoto von 2018-10-08 15-10-53

I'm fine with other icons and/or a new layout (putting the icons in one row with hover title, or whatever)

**Comment by Ivansss** [comment]
Notification's text should change when someone writes in a group/public room.
At the moment you receive: "{user} sent you a private message"
It should be something like: "{user} wrote a message in {room name}"

**Comment by nickvergessen** [comment]
> Notification's text should change when someone writes in a group/public room.
At the moment you receive: "{user} sent you a private message"
It should be something like: "{user} wrote a message in {room name}"

done

**Comment by jancborchardt** [comment]
Looks great @nickvergessen! :) Also yes for the mute-icon like in Signal and WhatsApp.

The default notification setting for every channel should be on @-mention initially.

**Comment by mario** [comment]
@jancborchardt people waited forever to get ALWAYS notifications in 1-to-1 conversations. Why take it away from them?

**Comment by nickvergessen** [comment]
Default remains the current behaviour:
* One2one: Always
* Others: Mention

**Comment by mario** [comment]
Awesome

**Comment by jancborchardt** [comment]
Totally missed this – just for the record, when I said "for every channel" I meant "for every _group_ channel". So the defaults @nickvergessen mentioned are :+1:

**Comment by errotu** [comment]
First of all, thanks a lot to everyone here for your great work!

We are introducing Talk at the moment in our organization and there have been several complaints with regard to the notification level (it actually took me a while to figure out the "notification if mentioned"-level, since this is not the default option I know from other messengers):
Would it be possible to introduce a feature to change the default behaviour server-wide or in ones own personal settings? We are working with many groups and it's quite incommodious to change it every single time for every group again.

Once again, thanks a lot for all your work!

**Comment by jancborchardt** [comment]
@errotu could you open a new issue with your request? :) Listing comparisons with how other messengers are doing it are very welcome too.

**Comment by errotu** [comment]
@jancborchardt Thanks for the quick reply! I have now opened #2085.

**Pull request merged**
