### PR TITLE
Openapi update

### PR DESCRIPTION
**Pull request by nickvergessen**
## 🛠️ API Checklist

- Using https://github.com/nextcloud/openapi-extractor/pull/24

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by nickvergessen** [comment]
Setting to draft as https://github.com/nextcloud/openapi-extractor/pull/24 is still not merged

**Review by provokateurin — APPROVED** [review]

**Comment by provokateurin** [comment]
I think we should wait a bit more if I find any more problems while doing the server PR.

**Comment by nickvergessen** [comment]
> I think we should wait a bit more if I find any more problems while doing the server PR.

I need to get rid of this branch. Can do follow up bumps if needed, but the branch starting with `o` is breaking my autocomplete tabbing with `origin` for way too long already 👯

**Comment by provokateurin** [comment]
Ok :+1:

**Pull request merged**
