### PR TITLE
Use dashes as list bullets in changelog

### LINKED ISSUE #1817: Lists in changelogs use asterisks instead of dashes
It’s a tiny detail nitpick, but asterisks as list bullets look very strange – simple dashes `-` would look nicer and simpler.
system messages talk dash instead of asterisk

### PR DESCRIPTION
**Pull request by Art4**
This PR will fix #1817. But I'm not sure what to do now to update the translation on transifex.

### CODE REVIEW

**Comment by nickvergessen** [comment]
that should happen automatically. but translators have to redo the translations :see_no_evil:

**Comment by nickvergessen** [comment]
Also thanks for your contribution, in this case it is not too important. For future changes please sign your commits. See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work for more information.

You can do this manually for now:
```
git commit --amend -s
git push --force origin <your branch>
```

But I guess you did the commit via the web interface of github?

**Comment by Art4** [comment]
> For future changes please sign your commits.

Yeah, I've seen it after creating the PR. Sorry.

> But I guess you did the commit via the web interface of github?

Yes, I did.

>  but translators have to redo the translations :see_no_evil: 

Is search/replace over the translation files an option?

**Comment by nickvergessen** [comment]
> Is search/replace over the translation files an option?

The sync to transifex just uploads new english strings and then downloads all other languages, so it will get lost.
But since the old string is still there in stable16, it should be good enough as they can copy paste them.

**Pull request merged**
