### PR TITLE
fix(TopBar): hand raised button animation

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Ref: https://github.com/nextcloud/spreed/issues/12800
### 🖼️ Screenshots / Screencasts

animation

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [x] 🖌️ Design was reviewed, approved or inspired by the design team
- [x] ⛑️ Tests are included or not possible
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Review by DorraJaouad — COMMENTED** [review]
The raised hand animation looks good, I like it :D. 
Rergarding media settings (not related to this PR but to https://github.com/nextcloud/spreed/pull/12815), there is a space created in devices selector to keep the same height with the other tab. It seems a bit off.  Maybe a delimiter to indicate that it slides and that space is not random would be good there. 
image

**Comment by ShGKme** [comment]
> there is a space created in devices selector to keep the same height with the other tab.

Making it height-stable was the goal from the design review 🙈

> Maybe a delimiter to indicate that it slides and that space is not random would be good there.

🤔 Can try in a separate PR (not related to raised hand)

**Comment by DorraJaouad** [comment]
> Making it height-stable was the goal from the design review 🙈

Yes, I want to indicate that in the UI too and not remove it

**Review by DorraJaouad — APPROVED** [review]
✨

**Comment by ShGKme** [comment]
@DorraJaouad Like this?

image

**Pull request merged**
