### PR TITLE
Add UI feedback when local participant is not connected

### PR DESCRIPTION
**Pull request by danxuliu**
When the connection with other participants is lost those participants are shown dimmed and with a loading spinner. However, when the MCU is used that only covers receiving audio and video from those participants. Other participants can not hear or see the local participant until the sender peer object has connected. Therefore now the local video / avatar is dimmed and shows a loading spinner like done with the remote participants when the sender peer object is not connected.

When the MCU is not used the connections are peer to peer between partipants, so the already existing dimming and loading spinner on the remote participants views already show whether those participants can hear and see the local participant or not.

Note that currently if you are alone in a call and a forced reconnection to the signaling server is triggered the sender peer object will not be reconnected, although it will be automatically reconnected once someone else joins the call. So if you leave Janus stopped for long enough in the test steps below you could see that the dimming and the loading spinner disappear. Nevertheless they will reappear until the connection is established once another participant joins the call.

**Before:**
Local-Participant-Disconnected-Before

**After:**
Local-Participant-Disconnected-After

## How to test
- Setup the HPB
- Start a call
- Stop Janus

### Result with this pull request
Eventually the local video / avatar is dimmed and a loading spinner is shown on it

### Result without this pull request
The local video is shown as before

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Conflicting files
src/components/CallView/shared/LocalVideo.vue

**Review by nickvergessen — APPROVED** [review]
Works otherwise

**Comment by danxuliu** [comment]
Rebased, fixed and tested.

**Pull request merged**
