### PR TITLE
Move the message hover position

### PR DESCRIPTION
**Pull request by Simounet**
### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
message-hover-position-before | message-hover-position-after

### 🏁 Checklist

- [X] 🌏 Tested with different browsers / clients:
  - [X] Chromium (Chrome / Edge / Opera / Brave)
  - [X] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [X] Not risky to browser differences / client

### Purpose

Being able to get the info from the check icon and send date even when hovering the message. Until now, if it's my first message, I can't be sure if it's the sent or read status.

### CODE REVIEW

**Comment by nickvergessen** [comment]
As easy as it sounds, we had it in the past and reverted it, as it creates flickering and issues when you hover the last message and it's single line. Buttons are cut of, or scrolling misbehaves, etc. :see_no_evil: 
grafik

Ref https://github.com/nextcloud/spreed/issues/9016 and many other things.
So feels quite dangerous.

**Comment by Simounet** [comment]
I understand you being extra cautious about this sort of "little" things. I saw the video with the flickering but I can't see why it would produce this kind of issue with an absolute position. Did you have other options in mind? To me, actions should not be displayed on hover, hidden from the user.
Should we use the extra space on the right side of the message on desktop view and absolute position be always display on mobile?

**Comment by DorraJaouad** [comment]
> I can't see why it would produce this kind of issue with an absolute position.

Probably because the absolute positioning is relative to its ancestor only (message item). 

> To me, actions should not be displayed on hover, hidden from the user.

Indeed, it makes it more accessible to keep it shown for user regardless of hover especially for mobile view yet we have the space constraint. As shown below, this is a view from desktop browser and there is no space that fits the message actions :/
<image src="https://github.com/user-attachments/assets/ec17b64f-0fe8-4eb4-b29b-e1f86ba2da31" width="500" />

> Should we use the extra space on the right side of the message on desktop view

The side spaces are not fixed and are adjustable based on window width.

**Comment by DorraJaouad** [comment]
@Simounet Thank you for taking the time to contribute to our project. I am afraid we're unable to merge this pull request as it would remove a critical workaround we implemented to address the existing flickering issue.

We appreciate your effort and want to provide more context. The current workaround is essential for maintaining the stability of our user experience. If you'd like to understand the specifics of the flickering problem or any other issue, we'd be happy to discuss it in more detail in [our public chat](https://cloud.nextcloud.com/call/c7fz9qpr).

We would like to invite you to explore our open issues on Talk. Your insights and code contribution are always welcome.

**Pull request closed without merging**
