### PR TITLE
Show the status on avatars

### PR DESCRIPTION
**Pull request by nickvergessen**
Bildschirmfoto von 2020-08-18 13-15-01

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Yep, it shouldn’t be shown in those little mention chips. (Neither in comments btw, in case that uses the same component.)

Well, then let me change the default for the mention chip

**Comment by nickvergessen** [comment]
Done via https://github.com/nextcloud/nextcloud-vue/pull/1259/commits/6ae3c95dde9defdde6abbf3b5804330a913fbf2f

**Comment by nickvergessen** [comment]
Aparently 2.5.0 has issues, so lets wait for 2.5.1

**Review by ma12-co — COMMENTED** [review]
Nice! I would say that the status circle should be smaller though. Also Imo there's no need for an icon in the yellow and red one.

**Comment by nickvergessen** [comment]
Invisible users are now "offline"

**Comment by nickvergessen** [comment]
Bildschirmfoto von 2020-08-19 18-45-05

Looong status ellipsis now in the mention suggestion and the right sidebar.

**Comment by nickvergessen** [comment]
The page reloads currently when clicking on the `Share file` action menu

**Comment by nickvergessen** [comment]
Bildschirmfoto von 2020-08-24 16-19-08

Double scrollbars when the participant menu is opened. Seems it doesn't respect the boundaries element body or something?

**Comment by nickvergessen** [comment]
Chat in the sidebar breaks the scrolling (it doesnt overflow anymore)

**Comment by jancborchardt** [comment]
Also agree with @nickvergessen that it looks quite off with the huge avatars in the suggestions and the sidebar. We could try that again if we also increase the global text size and also increase the avatar size in the chat list. But otherwise it’s a bit too big.

**Comment by nickvergessen** [comment]
> Also agree with nickvergessen that it looks quite off with the huge avatars in the suggestions and the sidebar. We could try that again if we also increase the global text size and also increase the avatar size in the chat list. But otherwise it’s a bit too big.

That issue has been solved in the meantime, there was a wrong offset making everything go wild.

**Comment by nickvergessen** [comment]
> Add boundarieselement to upload action 

It was already working there, only the participants menu is wrong

**Comment by ma12-co** [comment]
> It was already working there, only the participants menu is wrong

If you made the window small enough it would go underneath the sidebar before this commit for me

**Comment by ma12-co** [comment]
Screenshot from 2020-08-26 13-59-02

**Pull request merged**
