### PR TITLE
add some more spacing to have enough space for the sidebar drawer

### PR DESCRIPTION
**Pull request by schiessle**
Add some spacing to the left and the right to have enough space for the sidebar drawer

Before:

spreed1

After:

spreed2

### CODE REVIEW

**Comment by nickvergessen** [comment]
Well once the text starts to build up from the bottom instead of top it is okay on the left side I'd say.
and on the right side we should just add the white transparency in the same way.

**Comment by schiessle** [comment]
> Well once the text starts to build up from the bottom instead of top it is okay on the left side I'd say.

How does it make a difference whether the text is build up from the bottom or from the top? At some point you always reach the point where it overlaps. I think with some spacing it looks much cleaner than with overlapping content. Also with open sidebars the additional spacing doesn't hurt. At least for my taste it looks quite nice with the additional spacing and much cleaner.

**Comment by danxuliu** [comment]
If a margin is going to be added I would add it too to the new message input (right now the margin is applied only to the list of messages).

However, I am not sure if adding a margin to make room for the sidebar trigger is the best option. Although the _Join call_ button is currently shown in the sidebar [it was supposed to be eventually moved to the top right of the main view](https://github.com/nextcloud/spreed/issues/534) (although maybe the plan has changed now). In that case the margin would need to be twice as large as now, which visually may not look good (although that would be just a matter of taste ;-) ).

Another option would be to show a header at the top of the chat when shown in the main view. This header would show the navigation trigger (in narrow screens), sidebar trigger, and _Start/Join call_ button. As there would be plenty of empty space the header could show the room name, and maybe even the other fields from the room details currently shown in the sidebar (probably in a three-dot menu). The problem would be, however, what to do with that header during a call...

And a different approach without margins or a header would be to blur the background of the icons overlayed on the chat view with CSS filters.

Time to summon @jancborchardt :-)

**Comment by jancborchardt** [comment]
@danxuliu I also thought about a header, and it seems to fix our problem with the space in the sidebar too. :) In a call, the header would simply be white text with shadow (like the icons, or like the Nextcloud logo for guests). The call button could be left of the sidebar-trigger, in the header. Between join call and sidebar trigger could be the 3-dot menu for rename, share link, etc.

But that is a separate issue it seems?

**Comment by danxuliu** [comment]
>  I also thought about a header, and it seems to fix our problem with the space in the sidebar too. :)

Indeed :-)

>  But that is a separate issue it seems?

Yes, but it affects this pull request, as using a header would make these changes no longer needed (unless you want to include them anyway for aesthetical reasons or something like that).

**Comment by nickvergessen** [comment]
Closing as per above

**Comment by schiessle** [comment]
What's the timeline for the header? I think it is a good idea. But if it is something we have some day, I would prefer to go with this small fix for now. If course if you say that we will have the sidebar in 1-2 weeks we can skip this fix.

**Comment by nickvergessen** [comment]
It's scheduled for the next release

**Pull request closed without merging**
