### PR TITLE
fix(activity): Fix parameter type of call activity

### PR DESCRIPTION
**Pull request by nickvergessen**
### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by nickvergessen** [comment]
Way to annoying that psalm doesn't complain just because we loose the type when passing the array though multiple levels...

**Review by provokateurin — APPROVED** [review]

**Pull request merged**
