### PR TITLE
[stable20.1] Enable pagination for main grid view

### PR DESCRIPTION
**Pull request by danxuliu**
Backport of #4958

### CODE REVIEW

**Comment by nickvergessen** [comment]
So not sure if this was also on master, but at least with the dev dummys if you have 10 and a 3*3 grid, on the first page you have 0-7 + you (looking good) and on page 2 you have 8-9+ you.
But that page looks rather bad and your video just jumped to the top:
Page 1 | Page 2
---|---
Bildschirmfoto von 2021-01-21 16-50-27 | Bildschirmfoto von 2021-01-21 16-50-33

**Comment by danxuliu** [comment]
Yes, it is in master too. I was aware of it, but although I do not like it I did not find it so bad :-P

Anyway I think it could be fixed by adding dummy elements (just empty divs) as padding in the last page so the main grid shows the local video always at the bottom right.

**Comment by nickvergessen** [comment]
Sounds good (enough) for now

**Comment by ma12-co** [comment]
I think that this can also be accomplished with css grid rules only

**Comment by danxuliu** [comment]
> I think that this can also be accomplished with css grid rules only

Oh, I have just seen it :facepalm: Anyway the dirty fix is in #4996, feel free to do the proper fix and close that one :-)

**Comment by ma12-co** [comment]
> Oh, I have just seen it facepalm Anyway the dirty fix is in #4996, feel free to do the proper fix and close that one :-)

Yeah sorry to be late with that comment, I just recalled how things were done when looking into it :sweat_smile: 
pr here #4999

**Pull request merged**
