### PR TITLE
[stable27] refactor: make browserCheck an util

### PR DESCRIPTION
**Pull request by SystemKeeper**
Manual backport of https://github.com/nextcloud/spreed/pull/11009 to stable27

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Sorry, selected `main` by accident...

**Comment by ShGKme** [comment]
Should be backported together with https://github.com/nextcloud/spreed/pull/11016

**Review by ShGKme — APPROVED** [review]

**Comment by SystemKeeper** [comment]
> Should be backported together with
> 
> * [Fix use of blockCalls in vue template #11016](https://github.com/nextcloud/spreed/pull/11016)

Good point, added it

**Review by Antreesy — APPROVED** [review]
Tested

**Pull request merged**
