### PR TITLE
Fix forced active action looks

### PR DESCRIPTION
**Pull request by ma12-co**
Peek 2021-02-02 14-50

### CODE REVIEW

**Comment by nickvergessen** [comment]
While this fixes the forced-active, the hover is still "broken" for me?
You run vue master or something?

**Comment by ma12-co** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/1692

Nope not master, the fix for the hover is there ^

**Review by PVince81 — APPROVED** [review]
Tested, works. The blue thing is now visible when it wasn't before. :+1:

**Comment by jancborchardt** [comment]
This should be in the Vue components, no @ma12-co? cc @skjnldsv

**Comment by nickvergessen** [comment]
It's in https://github.com/nextcloud/nextcloud-vue/pull/1692

**Comment by ma12-co** [comment]
I think @jancborchardt  is talking about the hacked buttons into a radio. 
We already have a ActionRadio component in the vue lib. Not sure why this approach has been adopted here in the first place. Maybe for the icons? 
In any event I think we could remove this and use the already existing `actionradio` component, which looks clearer IMO as it's impossible to confuse it with other `ActionButton`. 
Screenshot from 2021-02-22 13-10-16

**Pull request merged**
