### PR TITLE
Leave call and room when logging out

### LINKED ISSUE #1872: "XXX left the call" message is not shown if the user log outs while in the call
## Steps to reproduce
- Start a call with user A
- Log out with user A while in the call
- Join the room with user B*

*It does not matter if you join immediately or wait several minutes to ensure that user A was cleaned from the room due to inactivity.

### Expected behaviour
"user A left the call" message is shown (note that no "Call with XXX" message is shown when there was just one participant in the call).

### Actual behaviour

No "user A left the call" message is shown; note that the call button is "Join call" instead of "Start call", which means that based on the data returned by the server the call is still ongoing.

If user B "joins" the call and then leaves the "Call with user A and user B (Duration XXX)" message would also appear, with XXX being the duration since user A started the call to user B ending it.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1872

### CODE REVIEW

**Comment by danxuliu** [comment]
@nickvergessen [The compatibility test fails](https://drone.nextcloud.com/nextcloud/spreed/2479/4/4) with
```
OC_Hook - Static method of private class must not be called
App is not compliant 
```

**Comment by nickvergessen** [comment]
It's compliance, not compatibility ;)

Accepted risk, we could disable the check altogether, but we can have a look at it now and then.
The other way would be to add an event dispatcher in the place the hook is triggered.

**Comment by nickvergessen** [comment]
Nevermind, see https://github.com/nextcloud/spreed/pull/1951 for a fix

**Pull request merged**
