### PR TITLE
First try to port the JS port

### PR DESCRIPTION
**Pull request by MorrisJobke**
@LukasReschke wants to look at this.

### CODE REVIEW

**Comment by fancycode** [comment]
Could you please describe what this PR is trying to achieve? It looks like it is munging the SDP and moving H.264 to the front of the codecs?

Imho this is something that should be done by the client before sending the message to the server. There you could use for example the `sdputils` from https://github.com/webrtc/apprtc/blob/master/src/web_app/js/sdputils.js#L303

**Comment by MorrisJobke** [comment]
> Could you please describe what this PR is trying to achieve? It looks like it is munging the SDP and moving H.264 to the front of the codecs?

The idea was to move H264 before VP9 because H264 is often available as hardware decoder (and VP9 not, but is pushed by browser vendors as preferred codec somehow) and thus requires way less resources on the clients then. But yes - changing this on the client side also makes sense if this is easily achievable.

**Comment by MorrisJobke** [comment]
It is only a first step, but Lukas did some more changes to the code locally. I just pushed it here so he could continue.

**Comment by Ivansss** [comment]
I agree that this should be done on the client side.
Before setting local session description and remote session description.

This is how we implemented it on iOS:
https://github.com/nextcloud/talk-ios/blob/master/VideoCalls/NCPeerConnection.m#L324
https://github.com/nextcloud/talk-ios/blob/master/VideoCalls/NCPeerConnection.m#L112

**Comment by MorrisJobke** [comment]
> This is how we implemented it on iOS:

Nice 👍

**Comment by nickvergessen** [comment]
If anyone wants to take this over, feel free to.
For now I raised a new issue about this:
https://github.com/nextcloud/spreed/issues/1223

**Pull request closed without merging**
