### PR TITLE
fix: Set all rich object parameter values to string

### PR DESCRIPTION
**Pull request by provokateurin**
### ☑️ Resolves

Replaces https://github.com/nextcloud/spreed/pull/11991.
Only strings are allowed as values.

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]
Works fine on iOS

**Review by nickvergessen — CHANGES_REQUESTED** [review]
PS: requires review from all requested persons
So blocking until everyone else approved

**Review by Antreesy — APPROVED** [review]
Adjusted frontend component to match new params. Nothing else is blocking

PS: backport to 27 might end up with conflicts, will handle it

**Review by DorraJaouad — APPROVED** [review]

**Comment by mahibi** [comment]
all fine for android talk as well, @nickvergessen

**Pull request merged**
