### PR TITLE
Fix guest avatars

### LINKED ISSUE #5949: Wrong icon for guest user avatar
Guest users have the group icon as avatar

Screenshot 2021-07-05 at 16 00 13

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #5949

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: tested works, but you'll need to adjust the Jest tests (which happened to be the first ever Jest tests in this app)

**Comment by PVince81** [comment]
Fixes https://github.com/nextcloud/spreed/issues/5949

**Review by Ivansss — APPROVED** [review]
Tested and works 👍

**Review by marcoambrosini — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
