### PR TITLE
feat(chat): API specs for "Edit message"

### LINKED ISSUE #11206: ✏️ Edit message - API
- See overview at https://github.com/nextcloud/spreed/issues/11203

---

* PR and todo at https://github.com/nextcloud/spreed/pull/11207

---

### 🚧 Tasks

- [x] System message hidden like with delete
    - https://github.com/nextcloud/spreed/pull/11207
- [ ] Make sure editing of captions for shared files work as well
    - [ ] Don't allow changing from message to caption and vice-versa
- [ ] Visible indicator a message was edited (and by whom/when)
    - [x] Amend to the author name ` (edited)` / ` (edited by moderator-name)`
        - https://github.com/nextcloud/spreed/pull/11207
    - [x] Editor+Time in Message menu as subline of timestamp
        - https://github.com/nextcloud/spreed/pull/11207
    - [ ] Displayname is hardcoded to id
- [ ] Time limitation like for delete?
    - [x] Limit editing to X hours (draft 24 hours, check what others do and discuss again)
        - https://github.com/nextcloud/spreed/pull/11207
    - [ ] Set the limit on deletion to infinite
- [ ] What to do about mention notifications (added a mention, removed a mention)
    - [ ] Should diff mentions and add/remove notifications accordingly
    - [ ] Make sure people don't get 1 for the message and 2 for followup edits
- [ ] What about bots?
    - [x] Can not edit bot messages, moderators can
    - If a message triggered a bot already it's yolo and will not be retriggered with the new content automatically (bot can do based on the system message?)
        -  [ ] Return 202 (also on delete) like with matterbridge
            - https://github.com/nextcloud/spreed/pull/11367
- [ ] 🔖 Capability is added
- [ ] Prevent editing to empty string

### PR DESCRIPTION
**Pull request by nickvergessen**
### ☑️ Resolves

* Fix #11206 

## 🛠️ API Checklist

- [x] Requires https://github.com/nextcloud/server/pull/42209

### 🚧 Tasks

- System message hidden like with delete
    - [x] Implement
- Time limitation like for delete?
    - [x] Limit editing to X hours (draft 24 hours, check what others do and discuss again)
- What about bots?
    - [x] Can not edit bot messages, moderators can
    - If a message triggered a bot already it's yolo and will not be retriggered with the new content automatically (bot can do based on the system message?)

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated

### CODE REVIEW

**Comment by SystemKeeper** [comment]
> * Amend to the author name ` (edited)` / ` (edited by moderator-name)`

This could be tricky on phones, I can see that most of the time the moderator name will  be truncated. Still okay or is wrapping mandatory in this case? (That would be more work, at least on iOS).

> Set the limit on deletion to infinite

That means deletion is always possible or editing a deleted message is always possible?

**Comment by SystemKeeper** [comment]
Maybe it’s obvious, but:

- [ ] Make sure editing of captions for shared files work as well


?

**Comment by nickvergessen** [comment]
As per overview

> * Don't allow changing from message to caption and vice-versa


But yeah will have to be handled explicitly not sure where I dropped it when copying over

**Comment by SystemKeeper** [comment]
The `lastMessage` object on the room list does not include the new `lastEdit*` properties:

Bildschirmfoto 2024-01-07 um 19 18 41
Bildschirmfoto 2024-01-07 um 19 19 12

**Comment by nickvergessen** [comment]
> The `lastMessage` object on the room list does not include the new `lastEdit*` properties:

Fixed

**Comment by SystemKeeper** [comment]
API allows to edit a message to an empty message.

**Comment by DorraJaouad** [comment]
> API allows to edit a message to an empty message.

I think this leads the edit to act like deleting the message ?

**Comment by SystemKeeper** [comment]
Not at the moment at least, right now it’s just an edited, empty message. I don’t think it should act as deleted personally, because you can’t edit a deleted message.

**Comment by Ivansss** [comment]
maybe the backend could handle it as a message deletion if and empty message is sent as "edited message"

**Comment by nickvergessen** [comment]
> API allows to edit a message to an empty message.

It's noted in the API ticket and we will block it.

**Comment by nickvergessen** [comment]
Just want to get the base in soon, so frontend and mobile can start working on the normal cases first, before handling edge cases

**Review by Ivansss — APPROVED** [review]
Base functionality working as expected 👍

**Pull request merged**
