### PR TITLE
chore(deps): Bump @nextcloud/vue from 8.11.2 to 8.11.3

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Fix #…
* Changelog: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.11.3

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it

### CODE REVIEW

**Comment by DorraJaouad** [comment]
One more left :( 
image


Skin color is not applied in frequent emojis 
image
image

**Comment by ShGKme** [comment]
> Skin color is not applied in frequent emojis

Requries https://github.com/nextcloud/spreed/pull/12285

**Comment by Antreesy** [comment]
> One more left :(

Yep, it still depends on vueuse/cire release, which hasn't happened yet

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
Also tested on Talk Desktop

**Review by DorraJaouad — APPROVED** [review]

**Pull request merged**
