### PR TITLE
Bump @nextcloud/vue to ^7.7.1

### LINKED ISSUE #7701: Vue warning in jest for permissions editor
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

```
      [Vue warn]: Error in nextTick: "Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times"
      
      found in
      
      ---> <Modal>
             <PermissionsEditor>
               <ParticipantPermissionsEditor>
                 <Root>
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #7701 in addition _(Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>)_

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by nickvergessen** [comment]
Too many things seem to be breaking, will have to delay this one

**Review by marcoambrosini — APPROVED** [review]
seems ok!

**Comment by nickvergessen** [comment]
But Jest is unhappy and the browser console is glowing red 😿

**Comment by nickvergessen** [comment]
When creating a conversation:
```
Uncaught TypeError: this.$refs.conversationName.focus is not a function
    visibilityChanged SetConversationName.vue:20
```

**Comment by nickvergessen** [comment]
Thanks for fixing @Antreesy

**Pull request merged**
