### PR TITLE
Add Avatar editor to new conversation dialog

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Adds avatar and description editors on conversation create dialog 
* Change styles and elements position for avatar editor
* Change "profile picture" to "conversation picture"
* Minor refactoring and fixes

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image
image | image
image | image

### 🚧 Tasks

- [ ] Visual check
- [ ] Code review

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

### CODE REVIEW

**Comment by nickvergessen** [comment]
I love it!

**Comment by Antreesy** [comment]
@ShGKme FYI: https://github.com/eddyerburgh/jest-transform-stub

Jest doesn't apply transforms to `node_modules` by default. I guess, the same rules are for `jest-transform-stub`
I've restored a deleted line in `moduleNameMapper`

**Review by jancborchardt — APPROVED** [review]
Very nice! :)

Might be good to give the 2 toggles a header too, like "Privacy" or "Conversation visibility". Cause currently they are very close under the picture. But not a blocker.

**Comment by Antreesy** [comment]
Add a label for toggles. Input was moved to save some vertical space:
Private | Public
--- | ---
image | image

**Pull request merged**
