### PR TITLE
Handle errors when accessing local media.

### PR DESCRIPTION
**Pull request by fancycode**
For now uses a custom message for HTTPS-required error in Chrome (#18) and
the "NotAllowedError" error if the used denied access to the devices. All
other errors show the message as reported by the browser.

### CODE REVIEW

**Comment by fancycode** [comment]
cc @LukasReschke

**Comment by karlitschek** [comment]
nice. @Ivansss @ChristophWurst @LukasReschke @jancborchardt

**Comment by LukasReschke** [comment]
Good stuff 👍

**Comment by jancborchardt** [comment]
Awesome! Btw @fancycode since you are part of the Nextcloud organization you can also work on branches of this repository directly :)

**Pull request merged**
