### PR TITLE
Fix leaving room as a self joined user with several sessions

### LINKED ISSUE #8626: Multi-session not working with self-joined users
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. User A creates room R with link share (without password) using Firefox
2. User B logs in to nextcloud and opens the link of room R using a private window in Firefox
3. User B logs in to nextcloud and opens the link of room R using Chromium
4. User B closes the browser or changes to another room using Chromium

### Expected behaviour
The session in the private firefox window should still be available and usable.

### Actual behaviour
The session in the private firefox window is redirected to "Conversation not found".

## Talk app

**Talk app version:** Tested with 14.0.7 and latest master (@ 7dc878f1899d646c925ee5b073a93430cf3e40d5)

**Custom Signaling server configured:** Can be reproduced either way

## Remarks
Key to that problem is that the user is not added by a moderator to the group conversation, but "self-joins" via a public link. When leaving one conversation, the attendee is removed here: https://github.com/nextcloud/spreed/blob/c4e47dcb3d586c860e00b1f50ffa26b2f20d1778/lib/Service/ParticipantService.php#L775-L780 which then results in the "Conversation not found" redirect.

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #8626

Self-joined users are just temporary participants and they need to be removed when they leave a conversation. However, this needs to be done once they have no more sessions in that conversation; otherwise the remaining sessions would be kicked out from the conversation as soon as one leaves it.

Moreover, if the external signaling server is used, when a participant is disinvited it is expected that the client leaves the conversation if still in it. Therefore, self-joined users should not be disinvited when
they disconnect from a conversation, as they can still have other sessions in it.

To ensure that self-joined users will be disinvited when their last session leaves the conversation now a USER_REMOVE event is explicitly triggered when that last session leaves and the user is, in fact, removed from the conversation.

Note that this does not cause the system message about the participant leaving to be sent, as [it is explicitly guarded against self-joined users leaving the conversation](https://github.com/nextcloud/spreed/blob/b71fc1d3d9c99502db1e9b514c4d219592cccae3/lib/Chat/SystemMessage/Listener.php#L305-L309). However, this change will cause other handlers to be called now, like [those to invalidate resources](https://github.com/nextcloud/spreed/blob/de8b51e6060a0a97ff8d2ae1176f0838fd93982c/lib/Collaboration/Reference/ReferenceInvalidationListener.php#L43), but it is very likely that they should have been called and that this change is actually a fix too in that regard.

It would be great to add integration tests to explicitly check this, but I do not if it is possible to simulate different sessions for the same participant in the integration tests.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Unit tests are not happy.

---

On that note, integration tests would be awesome, but I know they don't work at the moment with multiple sessions, so something to be raised again later.

**Comment by danxuliu** [comment]
> Unit tests are not happy.

Fixed.

**Review by vitormattos — COMMENTED** [review]
Will be necessary backport?

**Pull request merged**
