### PR TITLE
Fix popover with latest server change

### PR DESCRIPTION
**Pull request by skjnldsv**
Ref https://github.com/nextcloud/server/pull/6399#issuecomment-330499134

| Before | After | 
|:---:|:---:|
| bildschirmfoto vom 2017-09-19 10-50-32 | bildschirmfoto vom 2017-09-19 10-52-25 |

The fix should not change previous versions of server.

### CODE REVIEW

**Comment by Ivansss** [comment]
@skjnldsv What change in server breaks the popover?
I just try the app in latest master and I could not reproduce this issue.

**Comment by nickvergessen** [comment]
We should also be able to delete a lot of the CSS now and reuse the existing CSS?

btw ref https://github.com/nextcloud/server/pull/6399#issuecomment-330499134

**Comment by skjnldsv** [comment]
@nickvergessen yes we should, but I have far too much work on the other app to work on this now! :/
Can one of you take it? :)

**Comment by skjnldsv** [comment]
Closing in favor of keeping the relative positioning to server.

**Pull request closed without merging**
