### PR TITLE
Register flow operation via dedicated event

### PR DESCRIPTION
**Pull request by nickvergessen**
Maybe that helps with:
https://github.com/nextcloud/spreed/issues/5518#issuecomment-826564931

```
{
  "reqId": "cQy6L3Q7Syn0PWVL9M8d",
  "level": 4,
  "time": "2021-04-25T12:56:49+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "no app in context",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "Error",
    "Message": "Class 'OCA\\Talk\\Flow\\Operation' not found",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 176,
        "function": "boot",
        "class": "OCA\\Talk\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
        "line": 197,
        "function": "bootApp",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
        "line": 1039,
        "function": "loadApp",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Installer.php",
        "line": 151,
        "function": "executeRepairSteps",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
        "line": 431,
        "function": "installApp",
        "class": "OC\\Installer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Updater.php",
        "line": 423,
        "function": "enable",
        "class": "OC_App",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Updater.php",
        "line": 268,
        "function": "upgradeAppStoreApps",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Updater.php",
        "line": 132,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/Command/Upgrade.php",
        "line": 255,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php",
        "line": 255,
        "function": "execute",
        "class": "OC\\Core\\Command\\Upgrade",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 1009,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 273,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 149,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Console/Application.php",
        "line": 215,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/console.php",
        "line": 100,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/occ",
        "line": 11,
        "args": [
          "/var/www/nextcloud/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/spreed/lib/AppInfo/Application.php",
    "Line": 135,
    "CustomMessage": "Could not boot spreedClass 'OCA\\Talk\\Flow\\Operation' not found"
  },
  "userAgent": "--",
  "version": "20.0.3.2"
}
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
Since it complains about line 135, it has the new application class already at the point of update and therefor backporting to 21 should be enough:
https://github.com/nextcloud/spreed/blob/stable20.1/lib/AppInfo/Application.php#L133
https://github.com/nextcloud/spreed/blob/stable21/lib/AppInfo/Application.php#L135

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
