### PR TITLE
Don't flicker the call state when participants are updated while join…

### PR DESCRIPTION
**Pull request by nickvergessen**
…ing/leaving

Joining/Leaving a call is an async process and can take a while,
especially when starting a call and sending a lot of notifications.
Now we keep a force call state list for your session while joining/leaving.

### Steps
1. Apply the following patch
```diff
diff --git a/lib/Controller/CallController.php b/lib/Controller/CallController.php
index 2603922e..4ea1bf7f 100644
--- a/lib/Controller/CallController.php
+++ b/lib/Controller/CallController.php
@@ -86,6 +86,7 @@ class CallController extends AEnvironmentAwareController {
        public function joinCall(?int $flags): DataResponse {
                $this->room->ensureOneToOneRoomIsFilled();
 
+               sleep(10);
                $sessionId = $this->participant->getSessionId();
                if ($sessionId === '0') {
                        return new DataResponse([], Http::STATUS_NOT_FOUND);

```
2. Join a call and see the call view
3. See chat view again after just a sec
4. After some seconds you will toggle back into the call view

With this PR you will always see the call view.

### CODE REVIEW

**Comment by danxuliu** [comment]
I would close this in favour of #3609

**Comment by nickvergessen** [comment]
Feedback from @danxuliu posted on the wrong PR https://github.com/nextcloud/spreed/pull/3609#issue-419858970

> Although in other cases updating the local status before the server acknowledges it makes it feel snappier in the case of the call status it feels strange, as the call view would be shown empty without any hint that joining the call is still in progress.

**Comment by nickvergessen** [comment]
> as the call view would be shown empty without any hint that joining the call is still in progress.

If that is a problem we can fix it by adjusting the empty content message for this case specifically. But I think preparing the user for the incoming change (chat moved to sidebar, etc.) is better done while the user presses the button, instead of "randomly" after the request finished.
This would allow the user to see the new UI already, continue chatting or checking the participants tab etc. instead of (in worst case) starting to write a chat message and then the chat tab is moved to the right sidebar scrabbing all your text, unfocusing the input, etc.

**Comment by danxuliu** [comment]
> If that is a problem we can fix it by adjusting the empty content message for this case specifically.

In most cases that message would be gone too quick to be read, and in the end would cause flickering too.

> But I think preparing the user for the incoming change (chat moved to sidebar, etc.) is better done while the user presses the button, instead of "randomly" after the request finished.
> This would allow the user to see the new UI already, continue chatting or checking the participants tab etc.

In general the time elapsed since you hit the button and the server joins you in the call should not be long, so you would not have time to do all that. Sometimes you might, but you can still do those things in the chat view too.

> instead of (in worst case) starting to write a chat message and then the chat tab is moved to the right sidebar scrabbing all your text, unfocusing the input, etc.

I would say that is a different problem that should be fixed anyway. If a view is moved to a different place the view should keep its previous state. If you have written something in the text input but you did not send the message yet and you join a call the pending text should still be there when the chat is shown in the sidebar.

Due to all this I still think that joining the call synchronously is a better option.

**Comment by nickvergessen** [comment]
@ma12-co this is what we just talked about

**Comment by nickvergessen** [comment]
Github wouldn't let me reopen it after a force push, so new PR at https://github.com/nextcloud/spreed/pull/4086

**Pull request closed without merging**
