### PR TITLE
Add info text when user is not participating in any room.

### LINKED ISSUE #111: Empty sidebar when you are not in any call
When you are not in any call the sidebar is fully white.
Should display a message like "Start a call by searching for a user" or something like that.

### PR DESCRIPTION
**Pull request by Ivansss**
- Fix #111

### CODE REVIEW

**Comment by Ivansss** [comment]
@jancborchardt What do you think about the message?

**Comment by jancborchardt** [comment]
I still think we should open the select2 of »Choose person …« by default:

> Basically opening the dropdown by default is like prefilling the left list with suggestions on who to call. It directly shows faces / avatars to prompt you to call instead of an empty white pane with instructions. It’s more engaging.

Giving people an instruction for what to click is like admitting the interface failed.

**Comment by jancborchardt** [comment]
@Ivansss what do you think about my feedback? :)

**Comment by Ivansss** [comment]
@jancborchardt I don't like very much the idea about opening the select2 😁
A well formatted and explanatory text would be the best option in my opinion.

**Comment by jancborchardt** [comment]
@Ivansss the thing is that texts are rarely read. Just presenting things is the easy flow. We shouldn’t tell people what they need to do if we can just do it for them.

**Comment by Ivansss** [comment]
@jancborchardt I think when people don't know what to do, they will read. It's just a sentence.
When people know what to do, they will just omit it.
I still don't like the idea of opening select2 menu without user interaction because that menu is similar to the left side bar, and that could confuse users.
But let's hear other people's opinions and then we decide what to do :)
@LukasReschke @nickvergessen @MorrisJobke please, let us know what you think.

**Comment by jancborchardt** [comment]
> when people don't know what to do, they will read. It's just a sentence.
> When people know what to do, they will just omit it.

They will be confused and annoyed first. Why do that when we can make it easier directly. This is just not how we do design.

> I still don't like the idea of opening select2 menu without user interaction because that menu is similar to the left side bar, and that could confuse users.

Well – it is similar to the left sidebar because it’s basically the same: A list of people you can contact. That’s the entire idea. We are talking **only** about the first run experience here also, so people don’t even know the left sidebar. ;)

**Comment by nickvergessen** [comment]
Replaced by #210

**Pull request closed without merging**
