### PR TITLE
Remove invitation notification

### LINKED ISSUE #897: Wrong notifications
When a user joins a room to enter chat, the other person (or people) get a notification that somebody invited them to a call.

This is just wrong. There should be no notification in this case. The call notification should only happen once the user actually enters THE CALL.

### PR DESCRIPTION
**Pull request by mario**
Fixes #897.

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
Once this is merged, I'll work on getting notifications to be sent on every message.

**Comment by Ivansss** [comment]
I would not remove this notification until we have something else to notify users about being added to a group conversation, or someone texted them.

**Comment by mario** [comment]
They are still useless :)

But yea, don't merge this until I create proper text notifications. But feel free to review.

**Comment by nickvergessen** [comment]
Closing as per above for now.
We will redo notifications completely for 3.3/4.0

**Pull request closed without merging**
