### PR TITLE
Update version on master

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by danxuliu — CHANGES_REQUESTED** [review]
Missing update to [package-lock.json](https://github.com/nextcloud/spreed/blob/0aabe6d9e136780a8f86dc7fcb1653404afbd07e/package-lock.json#L3).

**Comment by nickvergessen** [comment]
and integration test app

**Review by danxuliu — APPROVED** [review]

**Comment by nickvergessen** [comment]
Failing tests:
https://github.com/nextcloud/spreed/blob/fffa9650c77621cfa2b9a531dacbd76862bcb82c/tests/integration/features/conversation/find-listed.feature#L18-L22

What is this?

**Comment by PVince81** [comment]
- [ ] REQUIRES: guest app update for tests https://github.com/nextcloud/guests/pull/543

**Comment by nickvergessen** [comment]
Merged, so we rebase this one?

**Comment by PVince81** [comment]
@nickvergessen yeah, please rebase this one or restart the tests

**Comment by nickvergessen** [comment]
Ah .... now I merged the commits into one.
Can you backport the test fix to stable21

**Comment by PVince81** [comment]
test fix backport here: https://github.com/nextcloud/spreed/pull/5072

**Pull request merged**
