### PR TITLE
Fixed composition errors, typo and uncommon spelling in de*-files

### PR DESCRIPTION
**Pull request by Somebodyisnobody**
However the guy who fixed "enable video" in de_DE didn't fix that in de.
I improved typography errors, uncommon expressions (that seemed like translated with google)
Overmore I tried to improve the sentence construction in line 69/71. That sounded bad!
It seems as github created a new line in the json-files. I don't know how to undo that.

### CODE REVIEW

**Comment by splitt3r** [comment]
This needs to be done via https://www.transifex.com/ as @nextcloud-bot will override changes with the synced files from there.

**Comment by Somebodyisnobody** [comment]
@splitt3r ok but then you (or someone other) need to do that. I don't want to login/signup on this service.

**Comment by splitt3r** [comment]
Perhaps @rakekniven can hell here?

**Comment by rakekniven** [comment]
Will take care of it.

**Comment by Somebodyisnobody** [comment]
Perfect, thanks

**Comment by rakekniven** [comment]
Fixed on Transifex.

**Pull request closed without merging**
