### PR TITLE
Prefer H264 codec when it is available

### LINKED ISSUE #1223: Prefer hardware based video encoding
A first attempt was started in #1171 

This should be looked into again, after we moved away from SimpleWebRTC (see #1063 ).
Using the current hack from #1171 (which just does it in php instead of a proper js method) already cuts the cpu usage by 25-50%.

### PR DESCRIPTION
**Pull request by nickvergessen**
Previous attempts:
* #1284
* #1171

### To enable it

```
./occ config:app:set spreed prefer_h264 --value yes
```

You should see the following message as debug in your browsers console:
```
'Preferring hardward codec H.264 as per global configuration'
```

Fix #1223

### CODE REVIEW

**Comment by nickvergessen** [comment]
Let's get this also in and backport, now that it has a config option to be enabled for testing @danxuliu

**Comment by szaimen** [comment]
@nickvergessen why shouldn't this setting be the default configuration?

**Comment by nickvergessen** [comment]
Because we need to do more tests in bigger scale before telling browsers "what you think is best is actually not the best"

**Pull request merged**
