### PR TITLE
Allow to give calls a name

### PR DESCRIPTION
**Pull request by nickvergessen**
I think our "Ivan Sein, Roel..." call name is pretty useless for everybody. Instead it would make sense, when it's called "Company Call".
This PR adds an endpoint which allows to set a name for calls. The participant list is still used, when there was no room name set manually.

- [x] On hover the participant list should be displayed instead of the room name again
- [x] UI needs an option to rename a channel

@Ivansss can you help?

### CODE REVIEW

**Comment by jancborchardt** [comment]
Yup, good one! The »Rename« option can go into the 3-dot menu. :)

**Comment by nickvergessen** [comment]
Added an update step that removes the random strings which where in the DB but never displayed.

**Comment by jancborchardt** [comment]
@nickvergessen let me know when I should jump in and fix input field styles or whatnot. :)

**Comment by nickvergessen** [comment]
Ivan is going to do that

**Comment by jancborchardt** [comment]
Ok cool :)

**Comment by nickvergessen** [comment]
Added `Enter` and `Esc` handling, ready to merge from my pov

**Pull request merged**
